export interface AuthorBio {
  name: string;
  bio: string;
  genre: string;
  knownFor: string[];
}

const AUTHOR_BIOS: AuthorBio[] = [
  {
    name: 'Sarah J. Maas',
    bio: 'Sarah J. Maas is a #1 New York Times and internationally bestselling author of romantasy and epic fantasy. Her series include A Court of Thorns and Roses (ACOTAR), Throne of Glass (ToG), and Crescent City. Known for complex heroines, intricate world-building, and slow-burn romance, she has sold over 12 million books worldwide.',
    genre: 'fantasy',
    knownFor: ['ACOTAR', 'Throne of Glass', 'Crescent City'],
  },
  {
    name: 'Rebecca Yarros',
    bio: 'Rebecca Yarros is a #1 New York Times bestselling author and decorated US Air Force veteran spouse whose Empyrean series — beginning with Fourth Wing — became a global publishing phenomenon. Her romantasy novels are known for their dragon-riding world-building, enemies-to-lovers dynamics, and emotional depth.',
    genre: 'fantasy',
    knownFor: ['Fourth Wing', 'Iron Flame', 'Onyx Storm'],
  },
  {
    name: 'Brandon Sanderson',
    bio: 'Brandon Sanderson is a #1 New York Times and internationally bestselling fantasy author renowned for his intricate magic systems and the Cosmere — a shared universe spanning multiple series. His works include The Stormlight Archive, Mistborn, Elantris, Warbreaker, and The Way of Kings. He also completed Robert Jordan\'s Wheel of Time series.',
    genre: 'fantasy',
    knownFor: ['Stormlight Archive', 'Mistborn', 'Cosmere'],
  },
  {
    name: 'Colleen Hoover',
    bio: 'Colleen Hoover (CoHo) is a #1 New York Times bestselling author of contemporary romance and new adult fiction. A former social worker, she self-published her debut Slammed in 2012 and became one of the most popular romance authors in the world, powered significantly by BookTok. Her books include It Ends with Us, Ugly Love, Verity, and Reminders of Him.',
    genre: 'romance',
    knownFor: ['It Ends with Us', 'Ugly Love', 'Verity'],
  },
  {
    name: 'George R.R. Martin',
    bio: "George R.R. Martin is a New York Times bestselling author and the creator of A Song of Ice and Fire, the epic fantasy series that inspired HBO's Game of Thrones. Known for his morally complex characters, political intrigue, and subverted fantasy tropes, Martin is one of the most influential fantasy authors of the 21st century. Fans await The Winds of Winter, Book 6.",
    genre: 'fantasy',
    knownFor: ['A Song of Ice and Fire', 'Game of Thrones', 'Winds of Winter'],
  },
  {
    name: 'Gillian Flynn',
    bio: 'Gillian Flynn is a New York Times bestselling author of psychological thrillers known for their dark, razor-sharp prose and unreliable narrators. Her novels include Gone Girl, Dark Places, and Sharp Objects — all of which have been adapted for film and television. Flynn is also a screenwriter and television producer.',
    genre: 'thriller',
    knownFor: ['Gone Girl', 'Sharp Objects', 'Dark Places'],
  },
  {
    name: 'James Patterson',
    bio: "James Patterson is the world's bestselling fiction author and a #1 New York Times bestseller. Known for his fast-paced thrillers and prolific output — often co-authored — his series include Alex Cross, Michael Bennett, Women's Murder Club, and NYPD Red. He is also a major advocate for children's literacy.",
    genre: 'thriller',
    knownFor: ['Alex Cross', "Women's Murder Club", 'Michael Bennett'],
  },
  {
    name: 'Nora Roberts',
    bio: 'Nora Roberts is a #1 New York Times bestselling author of over 200 romance novels as well as futuristic suspense as J.D. Robb. One of the most prolific and successful romance authors in history, her In Death series (as J.D. Robb) has over 50 installments. She is a member of the Romance Writers of America Hall of Fame.',
    genre: 'romance',
    knownFor: ['In Death series', 'Chesapeake Bay', 'Irish trilogy'],
  },
  {
    name: 'Andy Weir',
    bio: 'Andy Weir is a New York Times bestselling science fiction author known for scientifically rigorous, fast-paced stories. His debut The Martian — self-published in 2011 before becoming a major motion picture — launched his career. He followed it with Artemis and Project Hail Mary.',
    genre: 'sci-fi',
    knownFor: ['The Martian', 'Project Hail Mary', 'Artemis'],
  },
  {
    name: 'Taylor Jenkins Reid',
    bio: 'Taylor Jenkins Reid is a New York Times bestselling author of contemporary fiction known for character-driven stories with Hollywood settings and historical depth. Her books include The Seven Husbands of Evelyn Hugo, Daisy Jones & The Six, Malibu Rising, and Carrie Soto Is Back.',
    genre: 'fiction',
    knownFor: ['The Seven Husbands of Evelyn Hugo', 'Daisy Jones & The Six', 'Malibu Rising'],
  },
  {
    name: 'Emily Henry',
    bio: 'Emily Henry is a #1 New York Times bestselling author of contemporary romance known for her witty banter, emotional depth, and slow-burn love stories. Her books include Beach Read, People We Meet on Vacation, Book Lovers, Happy Place, and Funny Story.',
    genre: 'romance',
    knownFor: ['Beach Read', 'People We Meet on Vacation', 'Book Lovers'],
  },
  {
    name: 'Ali Hazelwood',
    bio: 'Ali Hazelwood is a New York Times bestselling author of STEM romance — nerdy, witty love stories featuring scientists and academics. Her debut The Love Hypothesis launched a wave of academic romance. She also writes the Loathe to Love You and Bride series.',
    genre: 'romance',
    knownFor: ['The Love Hypothesis', 'Love on the Brain', 'Bride'],
  },
  {
    name: 'Leigh Bardugo',
    bio: 'Leigh Bardugo is a #1 New York Times bestselling author and creator of the Grishaverse — one of the most beloved fantasy universes in modern fiction. Her Six of Crows duology is widely regarded as among the best heist fantasy ever written, and the Shadow and Bone trilogy inspired a Netflix series. She is also the author of Wonder Woman: Warbringer.',
    genre: 'fantasy',
    knownFor: ['Six of Crows', 'Shadow and Bone', 'King of Scars'],
  },
  {
    name: 'Cassandra Clare',
    bio: 'Cassandra Clare is a #1 New York Times and #1 internationally bestselling author of the Shadowhunter Chronicles — one of the best-selling YA fantasy series of all time. Her interconnected series include The Mortal Instruments, The Infernal Devices, The Dark Artifices, and The Last Hours. She has sold over 50 million books worldwide.',
    genre: 'fantasy',
    knownFor: ['City of Bones', 'Clockwork Angel', 'Lady Midnight'],
  },
  {
    name: 'Rick Riordan',
    bio: "Rick Riordan is the #1 New York Times bestselling author of the Percy Jackson & The Olympians series and its many sequels and companions. A former middle school English and social studies teacher, Riordan created Percy Jackson to help his son with dyslexia. His Riordan-verse spans Greek, Roman, Egyptian, Norse, and various cultural mythologies. A Disney+ adaptation of Percy Jackson debuted in 2023.",
    genre: 'fantasy',
    knownFor: ['Percy Jackson & The Olympians', 'The Heroes of Olympus', 'The Kane Chronicles'],
  },
  {
    name: 'Diana Gabaldon',
    bio: 'Diana Gabaldon is the New York Times bestselling author of the Outlander series — a sweeping saga that blends historical fiction, time travel, romance, and adventure across 18th-century Scotland. With nine novels and multiple novellas, Outlander has sold over 50 million copies worldwide and inspired a long-running Starz television series.',
    genre: 'fiction',
    knownFor: ['Outlander', 'Dragonfly in Amber', 'The Fiery Cross'],
  },
  {
    name: 'Holly Black',
    bio: "Holly Black is a #1 New York Times bestselling author of dark and vivid fantasy novels for teens and adults. Her Folk of the Air trilogy — The Cruel Prince, The Wicked King, and The Queen of Nothing — brought her to mainstream prominence and became a defining series of modern YA fantasy. She is also the co-creator of The Spiderwick Chronicles with Tony DiTerlizzi.",
    genre: 'fantasy',
    knownFor: ['The Cruel Prince', 'The Wicked King', 'The Stolen Heir'],
  },
  {
    name: 'V.E. Schwab',
    bio: "V.E. Schwab (also known as Victoria Schwab) is a #1 New York Times bestselling author known for lush, character-driven speculative fiction. Her Shades of Magic trilogy follows a rare magician who travels between parallel Londons, while The Invisible Life of Addie LaRue became a literary phenomenon. She is also the author of the Villains duology (Vicious, Vengeful).",
    genre: 'fantasy',
    knownFor: ['A Darker Shade of Magic', 'The Invisible Life of Addie LaRue', 'Vicious'],
  },
  {
    name: 'Pierce Brown',
    bio: 'Pierce Brown is a #1 New York Times bestselling author and creator of the Red Rising Saga — a brutal, brilliantly plotted science fiction epic set in a future where humanity colonizes the solar system under a rigid color-coded caste system. Compared to Game of Thrones for its political complexity and willingness to upend expectations, the series has sold millions of copies worldwide.',
    genre: 'sci-fi',
    knownFor: ['Red Rising', 'Golden Son', 'Morning Star'],
  },
  {
    name: 'Jennifer L. Armentrout',
    bio: "Jennifer L. Armentrout is a #1 New York Times and internationally bestselling author of romantic fantasy, paranormal romance, and new adult fiction. She is best known for her Blood and Ash series, which begins with From Blood and Ash and has become one of the most beloved romantasy series of the decade. Armentrout is an extraordinarily prolific author with over 50 published books across multiple pen names and genres.",
    genre: 'fantasy',
    knownFor: ['From Blood and Ash', 'A Kingdom of Flesh and Fire', 'The War of Two Queens'],
  },
  {
    name: 'Jennifer Lynn Barnes',
    bio: "Jennifer Lynn Barnes is a New York Times bestselling author of YA mystery and thriller novels, as well as a professor of psychology. Her breakout series The Inheritance Games — following Avery Grambs, who unexpectedly inherits a billionaire's fortune — became a massive BookTok phenomenon and one of the best-selling YA series in recent years. Barnes brings her psychology expertise to crafting deeply engaging mysteries.",
    genre: 'thriller',
    knownFor: ['The Inheritance Games', 'The Hawthorne Legacy', 'The Final Gambit'],
  },
  {
    name: 'Julia Quinn',
    bio: "Julia Quinn is a New York Times bestselling author and one of the most beloved names in Regency romance. Her Bridgerton series — eight novels following the eight Bridgerton siblings — gained a massive new audience when Shonda Rhimes adapted it for Netflix, making Quinn a household name. Known for her wit, humor, and swoon-worthy heroes, Quinn holds a degree from Yale and attended Harvard Medical School before pursuing writing full time.",
    genre: 'romance',
    knownFor: ['The Duke and I', 'The Viscount Who Loved Me', 'Romancing Mr. Bridgerton'],
  },
  {
    name: 'Patrick Rothfuss',
    bio: "Patrick Rothfuss is an American fantasy author whose Kingkiller Chronicle — beginning with The Name of the Wind — is widely considered one of the finest fantasy series ever written. His prose is celebrated for its literary beauty and the depth of its world-building, particularly the musical and mythological systems of the world of Temerant. Fans have eagerly awaited The Doors of Stone, the concluding volume, for over a decade.",
    genre: 'fantasy',
    knownFor: ['The Name of the Wind', "The Wise Man's Fear", 'Doors of Stone'],
  },
  {
    name: 'Andrzej Sapkowski',
    bio: "Andrzej Sapkowski is a Polish fantasy author and creator of The Witcher saga, one of the most beloved and commercially successful fantasy franchises in the world. His morally complex Witcher stories — collected in The Last Wish and Sword of Destiny before expanding into the five-novel saga — inspired the award-winning CD Projekt Red video games and a Netflix series. Sapkowski is one of Europe's best-selling fantasy authors.",
    genre: 'fantasy',
    knownFor: ['The Last Wish', 'Blood of Elves', 'Lady of the Lake'],
  },
  {
    name: 'Ana Huang',
    bio: "Ana Huang is a New York Times bestselling author of contemporary romance whose Twisted Series became a global BookTok sensation. Beginning with Twisted Love, the series features wealthy, morally grey alpha heroes and the bold women who match them — a combination that resonated with millions of readers worldwide. Huang is one of the defining voices of the modern BookTok romance era.",
    genre: 'romance',
    knownFor: ['Twisted Love', 'Twisted Games', 'Twisted Hate'],
  },
  {
    name: 'Tahereh Mafi',
    bio: "Tahereh Mafi is a New York Times bestselling author best known for the Shatter Me series, a YA dystopian fantasy celebrated for its intensely lyrical, stream-of-consciousness prose style and its emotionally complex love triangle. Born in Iran and raised in Connecticut, Mafi has become one of the most distinctive stylistic voices in young adult fiction. The Shatter Me series has sold over 4 million copies worldwide.",
    genre: 'fantasy',
    knownFor: ['Shatter Me', 'Unravel Me', 'Ignite Me'],
  },
  {
    name: 'Olivie Blake',
    bio: "Olivie Blake is the pen name of Alexene Farol Follmuth, a New York Times bestselling author of dark fantasy and romantasy. Her novel The Atlas Six — originally self-published before being acquired by Tor — became a viral sensation for its morally complex ensemble cast, dense philosophical themes, and dark academia aesthetic. Blake is also the author of Masters of Death and One for My Enemy.",
    genre: 'fantasy',
    knownFor: ['The Atlas Six', 'The Atlas Paradox', 'The Atlas Complex'],
  },
  {
    name: 'Suzanne Collins',
    bio: "Suzanne Collins is the New York Times bestselling author of The Hunger Games trilogy, which has sold over 100 million copies worldwide and spawned a blockbuster film franchise. Before the Hunger Games, she wrote the Underland Chronicles (beginning with Gregor the Overlander). Her prequel The Ballad of Songbirds and Snakes (2020) and the forthcoming Sunrise on the Reaping (March 2026) continue the Panem universe. Collins was a television writer before turning to novels.",
    genre: 'sci-fi',
    knownFor: ['The Hunger Games', 'Catching Fire', 'Mockingjay'],
  },
  {
    name: 'Robert Jordan',
    bio: "Robert Jordan (pen name of James Oliver Rigney Jr.) was an American fantasy author best known for The Wheel of Time, a 14-novel epic that reshaped the genre and sold over 90 million copies worldwide. Jordan wrote prolifically — as many as 14 hours a day — and was working on the final three books when he died of cardiac amyloidosis in 2007. Brandon Sanderson completed the series from Jordan's extensive notes. The Wheel of Time premiered as an Amazon Prime Video series in 2021.",
    genre: 'fantasy',
    knownFor: ['The Eye of the World', 'The Shadow Rising', 'A Memory of Light'],
  },
  {
    name: 'R. F. Kuang',
    bio: "R.F. Kuang (Rebecca F. Kuang) is an American fantasy and literary fiction author whose work spans brutal military fantasy (The Poppy War trilogy), Oxford historical fantasy (Babel, 2022), and literary satire (Yellowface, 2023). A Marshall Scholar and Oxford graduate, Kuang brings deep historical and literary knowledge to genre fiction and is widely credited with opening doors for Asian voices in Anglo-American fantasy. She is one of the most acclaimed young authors working in any genre.",
    genre: 'fantasy',
    knownFor: ['The Poppy War', 'Babel', 'Yellowface'],
  },
  {
    name: 'Stephen King',
    bio: "Stephen King is one of the best-selling authors of all time, with over 350 million copies of his books sold worldwide. Known as the 'King of Horror,' his work spans horror, thriller, science fiction, and fantasy. The Dark Tower series — his magnum opus — weaves together the mythology of dozens of his other novels into a single connected universe. Major works include It, The Shining, The Stand, Carrie, Misery, and Pet Sematary. King continues publishing multiple books per year into his 70s.",
    genre: 'horror',
    knownFor: ['The Dark Tower', 'The Stand', 'It'],
  },
  {
    name: 'Lynda La Plante',
    bio: 'Lynda La Plante is a British crime writer and screenwriter whose Prime Suspect — starring Helen Mirren — became one of the most critically acclaimed crime dramas in television history. Her Jane Tennison and Anna Travis detective series are bestsellers in the UK and internationally. La Plante began as an actress before turning to writing, and has won numerous BAFTA and Edgar Awards. Her books are known for their gritty procedural realism and complex female leads.',
    genre: 'thriller',
    knownFor: ['Prime Suspect', 'Anna Travis series', 'Tennison'],
  },
  {
    name: 'Tia Williams',
    bio: "Tia Williams is a New York Times bestselling author of contemporary romance and women's fiction. Her novel Seven Days in June became a BookTok sensation for its searing depiction of a chronic pain survivor and a reunion romance between two Black writers. A former beauty editor, Williams is known for her lush prose and emotionally resonant characters. Her books include It Goes Like This and The Perfect Find.",
    genre: 'romance',
    knownFor: ['Seven Days in June', 'It Goes Like This', 'The Perfect Find'],
  },
  {
    name: 'Kelly Yang',
    bio: "Kelly Yang is a New York Times bestselling author of young adult and middle grade fiction. Her debut Front Desk (2018) — inspired by her own childhood as a Chinese immigrant growing up in motels — won the Asian/Pacific American Award for Literature and launched a beloved series. She is a founder of The Kelly Yang Project, which teaches essay writing and critical thinking to children worldwide. Her books champion immigrant stories and social justice themes.",
    genre: 'fiction',
    knownFor: ['Front Desk', 'Parachutes', 'New From Here'],
  },
  {
    name: 'Ia Genberg',
    bio: "Ia Genberg is a Swedish novelist whose debut The Details (original title: Detaljerna) won the Nordic Council's Literature Prize and the International Booker Prize in 2024. Written in precise, crystalline prose, The Details explores female friendship and memory through intimate portraits. Genberg is considered one of Sweden's most distinctive literary voices.",
    genre: 'fiction',
    knownFor: ['The Details'],
  },
  {
    name: 'Alka Joshi',
    bio: "Alka Joshi is a New York Times and USA Today bestselling author of literary fiction. Her debut The Henna Artist (2021) — set in 1950s Rajasthan — became a Reese's Book Club pick and launched the Jaipur Trilogy. Joshi draws on her Indian heritage to explore women's autonomy, art, and ambition in post-independence India. She worked as an advertising executive for over two decades before publishing her first novel at age 62.",
    genre: 'fiction',
    knownFor: ['The Henna Artist', 'The Secret Keeper of Jaipur', 'The Perfumist of Paris'],
  },
  {
    name: 'Saladin Ahmed',
    bio: "Saladin Ahmed is a Hugo Award-nominated fantasy author and comic book writer known for Throne of the Crescent Moon, a Nebula Award finalist set in a Middle Eastern-inspired fantasy world. As a comic writer, he has worked on Marvel's Black Bolt, Ms. Marvel, and Abbott for BOOM! Studios. Ahmed's work centers diverse, non-Eurocentric perspectives in genre fiction and has been translated into a dozen languages.",
    genre: 'fantasy',
    knownFor: ['Throne of the Crescent Moon', 'Black Bolt', 'Abbott'],
  },
  {
    name: 'Donna Andrews',
    bio: "Donna Andrews is an Agatha and Anthony Award-winning mystery author best known for the Meg Langslow series, featuring a blacksmith and amateur sleuth whose cases often involve birds (she raises ostriches). The series spans over 30 books and is beloved for its cozy small-town Virginia setting and humorous tone. Andrews also writes the Turing Hopper series featuring an artificial intelligence detective.",
    genre: 'mystery',
    knownFor: ['Meg Langslow series', 'Murder with Peacocks', 'Owl Be Home for Christmas'],
  },
  {
    name: 'Carolyn Haines',
    bio: "Carolyn Haines is a USA Today bestselling author of the Sarah Booth Delaney Mississippi Delta mystery series, featuring a Southern belle who teams up with the ghost of a flapper-era maid to solve crimes. A former journalist, Haines has written over 50 books across mystery, romance, and mainstream fiction. She also rescues animals and operates the Good Fortune Farm Refuge in Alabama.",
    genre: 'mystery',
    knownFor: ['Sarah Booth Delaney series', 'Bone to Pick', 'Charmed Bones'],
  },
  {
    name: 'Peter Straub',
    bio: "Peter Straub was a two-time Bram Stoker Award winner and World Fantasy Award winner widely considered one of the most literary voices in horror fiction. Ghost Story (1979) is regarded as a masterpiece of the genre, and he collaborated with Stephen King on The Talisman and Black House. Straub's work blended literary sophistication with supernatural horror, and he mentored generations of genre writers before his death in 2022.",
    genre: 'thriller',
    knownFor: ['Ghost Story', 'The Talisman', 'Koko'],
  },
  {
    name: 'Maurice Sendak',
    bio: "Maurice Sendak was one of the most celebrated and influential illustrators and authors in children's literature history. Where the Wild Things Are (1963) won the Caldecott Medal and is one of the best-selling picture books of all time, appearing in virtually every list of greatest children's books. Sendak worked with a distinctive emotional intensity that many considered radical for children's books. His other major works include In the Night Kitchen and Outside Over There.",
    genre: 'fiction',
    knownFor: ['Where the Wild Things Are', 'In the Night Kitchen', 'Higglety Pigglety Pop!'],
  },
  {
    name: 'Caitlin Crews',
    bio: "Caitlin Crews is a USA Today and New York Times bestselling author of over 100 contemporary and category romance novels, primarily for Harlequin Presents. Known for glamorous settings, brooding heroes, and emotionally charged plots, she writes billionaire romance, royal romance, and enemies-to-lovers stories beloved by romance readers worldwide.",
    genre: 'romance',
    knownFor: ['Harlequin Presents', 'The Playboy of Argentina', 'A Baby to Bind His Bride'],
  },
  {
    name: 'Millie Adams',
    bio: "Millie Adams is a pen name for a New York Times and USA Today bestselling romance author known for emotionally intense Harlequin Presents novels. Writing under the Adams name, she delivers passionate category romance featuring powerful heroes, strong heroines, and the kind of sweeping drama that defines the Presents line.",
    genre: 'romance',
    knownFor: ['Harlequin Presents', 'His Secretly Pregnant Cinderella'],
  },
  {
    name: 'Jackie Ashenden',
    bio: "Jackie Ashenden is a New Zealand-based New York Times and USA Today bestselling romance author with over 80 novels to her name, writing primarily for Harlequin Presents and Harlequin Dare. She's known for deeply emotional heroes, intense chemistry, and a penchant for brooding billionaires and alpha males who meet their match.",
    genre: 'romance',
    knownFor: ['Harlequin Presents', 'The Maid the Greek Married', 'A Vow to Claim His Hidden Son'],
  },
  {
    name: 'Louise Jensen',
    bio: "Louise Jensen is a Sunday Times and international bestselling author of psychological thrillers set primarily in the UK. Her novels The Date, The Family, The Stolen Sisters, and The Missing are known for domestic suspense, complex family dynamics, and twisty plots that keep readers guessing until the final page. Her debut novel The Sister was a Kindle #1 bestseller.",
    genre: 'thriller',
    knownFor: ['The Date', 'The Family', 'The Sister'],
  },
  {
    name: 'Rona Halsall',
    bio: "Rona Halsall is a UK bestselling author of psychological thrillers known for dark domestic suspense and unreliable narrators. Her novels including Keep You Safe, Love You Gone, and Her Mother's Lies feature gripping plots built around family secrets, betrayal, and dangerous obsessions. She has sold over a million copies worldwide.",
    genre: 'thriller',
    knownFor: ['Keep You Safe', 'Love You Gone', "Her Mother's Lies"],
  },
  {
    name: 'Pepper Winters',
    bio: "Pepper Winters is a New York Times and USA Today bestselling author of dark romance, known for morally complex characters and emotionally intense storylines. Her Tears of Tess series launched her career, and she has since written dozens of novels across multiple series including Dollar, Indebted, and Monsters in the Dark, consistently appearing on bestseller lists.",
    genre: 'romance',
    knownFor: ['Tears of Tess', 'Dollar Series', 'Indebted Series'],
  },
  {
    name: 'Skye Warren',
    bio: "Skye Warren is a New York Times and USA Today bestselling author of dark and contemporary romance. Known for her psychological depth and exploration of taboo themes within romance, she has published over 50 novels including the Endgame trilogy, The Trust Fund Duet, and Survival of the Richest. Her books consistently land on major bestseller lists.",
    genre: 'romance',
    knownFor: ['Endgame Series', 'Survival of the Richest', 'The Trust Fund Duet'],
  },
  {
    name: 'Willow Winters',
    bio: "Willow Winters is a USA Today bestselling author of contemporary and dark romance with over 60 novels published. Known for standalone novels and connected series featuring emotionally complex romances, her prolific output and dedicated readership have made her a staple of the self-publishing romance market. Her Merciless World and This Love Hurts series are among her most popular.",
    genre: 'romance',
    knownFor: ['Merciless World', 'This Love Hurts', 'Bad Boys series'],
  },
  {
    name: 'Suzanne Enoch',
    bio: "Suzanne Enoch is a New York Times bestselling author of historical and contemporary romance with over 40 novels to her name. Best known for her Regency romance series including Scandalous Brides, Lessons in Love, and The Adventurers Club, she brings witty heroines and roguish heroes to the Georgian and Regency eras with warmth and humor.",
    genre: 'romance',
    knownFor: ['Scandalous Brides', 'The Adventurers Club', 'Samantha Jellicoe series'],
  },
  {
    name: 'Karen Hawkins',
    bio: "Karen Hawkins is a New York Times and USA Today bestselling author of historical and contemporary romance. She is best known for her MacLean Curse series and the Hurst Amulet series set in Regency England, as well as her charming contemporary romance series set in Dove Pond, South Carolina — small-town romance featuring sisterhood and Southern warmth.",
    genre: 'romance',
    knownFor: ['MacLean Curse', 'Dove Pond series', 'Hurst Amulet'],
  },
  {
    name: 'Charlie Jane Anders',
    bio: "Charlie Jane Anders is a Hugo, Nebula, and Locus Award-winning author of science fiction and fantasy. Her debut novel All the Birds in the Sky won the Nebula Award for Best Novel. She is also known for The City in the Middle of the Night and the Unstoppable series. Anders co-founded io9, the influential science fiction blog, and is a prominent voice in speculative fiction.",
    genre: 'sci-fi',
    knownFor: ['All the Birds in the Sky', 'The City in the Middle of the Night', 'Victories Greater Than Death'],
  },
  {
    name: 'Fran Wilde',
    bio: "Fran Wilde is a Hugo and Nebula Award-winning author of science fiction and fantasy. Her debut novel Updraft won the Andre Norton Nebula Award and is the first book in the Bone Universe series. She is known for intricate world-building that defies genre conventions, weaving together fantasy, science fiction, and social commentary. Her novella The Jewel and Her Lapidary is also a fan favorite.",
    genre: 'fantasy',
    knownFor: ['Updraft', 'Cloudbound', 'The Jewel and Her Lapidary'],
  },
  {
    name: 'Dani Collins',
    bio: "Dani Collins is a USA Today bestselling author of category romance, publishing almost exclusively with Harlequin Presents. A prolific Canadian author with over 70 novels, she is known for sweeping international settings, deeply emotional plots, and the glamorous tension that defines the Presents line. She writes alpha billionaires and independent heroines navigating love against all odds.",
    genre: 'romance',
    knownFor: ['Harlequin Presents', 'Their Reunion Vow', 'A Hidden Heir to Redeem Him'],
  },
  {
    name: 'James Dashner',
    bio: "James Dashner is the American author of the Maze Runner series, one of the defining YA dystopian trilogies of the 2010s. He began his writing career with the 13th Reality series before The Maze Runner (2009) launched him to international bestseller status. The series was adapted into a blockbuster film franchise beginning in 2014. Dashner is known for high-concept premises that drop readers into dangerous situations with few answers, forcing characters and readers alike to piece together the truth.",
    genre: 'fiction',
    knownFor: ['The Maze Runner', 'The Scorch Trials', 'The Death Cure', 'The 13th Reality'],
  },
  {
    name: 'Veronica Roth',
    bio: "Veronica Roth is the New York Times bestselling author of the Divergent trilogy, which she wrote while studying creative writing at Northwestern University. The trilogy — Divergent (2011), Insurgent (2012), and Allegiant (2013) — sold over 35 million copies worldwide and was adapted into a major film franchise starring Shailene Woodley. After Divergent, Roth moved into adult SFF with the Carve the Mark duology and the dark fantasy Chosen Ones.",
    genre: 'fiction',
    knownFor: ['Divergent', 'Insurgent', 'Allegiant', 'Chosen Ones'],
  },
  {
    name: 'Richelle Mead',
    bio: "Richelle Mead is a New York Times bestselling author known primarily for her Vampire Academy series and its Bloodlines spinoff. Born in Michigan, Mead combines paranormal romance with boarding school drama and supernatural hierarchy, creating one of the best-loved YA vampire series of the 2000s. Her adult urban fantasy series Succubus Blues and the Georgina Kincaid series established her adult readership. The Vampire Academy film adaptation premiered in 2014.",
    genre: 'romance',
    knownFor: ['Vampire Academy', 'Bloodlines', 'Succubus Blues', 'Georgina Kincaid series'],
  },
  {
    name: 'Christopher Paolini',
    bio: "Christopher Paolini is an American author who began writing Eragon at the age of fifteen, making him one of the youngest authors to achieve international bestseller status with a debut novel. The Inheritance Cycle — Eragon (2003), Eldest (2005), Brisingr (2008), and Inheritance (2011) — has sold over 35 million copies worldwide. Paolini returned to the world of Alagaësia with Murtagh (2023). He has also written To Be Taught, If Fortunate, a science fiction novella, and is working on a new sci-fi novel, The Fractal Shroud.",
    genre: 'fantasy',
    knownFor: ['Eragon', 'Eldest', 'Brisingr', 'Inheritance', 'Murtagh'],
  },
  {
    name: 'Marie Lu',
    bio: "Marie Lu is the New York Times bestselling author of the Legend trilogy, the Young Elites trilogy, and the Warcross duology. Born in China and raised in Texas, Lu worked as an art director in video games before her debut novel Legend (2011) launched her writing career. Known for propulsive dual-POV storytelling, morally complex heroes, and class-war themes, she has established herself as one of the defining YA authors of her generation. The Legend trilogy has sold millions of copies in over 30 languages.",
    genre: 'fiction',
    knownFor: ['Legend', 'The Young Elites', 'Warcross', 'Batman: Nightwalker'],
  },
  {
    name: 'Victoria Aveyard',
    bio: "Victoria Aveyard is the New York Times bestselling author of the Red Queen series, her debut YA fantasy novel that became a phenomenon when published in 2015. Aveyard grew up in East Longmeadow, Massachusetts and studied screenwriting at USC before writing Red Queen. The Red Queen series — spanning four novels and multiple novellas — has sold over 10 million copies worldwide. She has also written Realm Breaker, an epic fantasy series for adults.",
    genre: 'fiction',
    knownFor: ['Red Queen', 'Glass Sword', 'War Storm', 'Realm Breaker'],
  },
  {
    name: 'Frank Herbert',
    bio: "Frank Herbert (1920–1986) was an American science fiction author best known for Dune (1965), the bestselling science fiction novel of all time with over 20 million copies sold. A former journalist and ecological thinker, Herbert spent six years researching Oregon sand dunes before writing Dune, which transformed his observations on ecology, religion, and power into the planet Arrakis. He wrote five sequels before his death in 1986. Denis Villeneuve's film adaptations (2021, 2024) introduced Dune to a new generation.",
    genre: 'sci-fi',
    knownFor: ['Dune', 'Dune Messiah', 'Children of Dune', 'God Emperor of Dune'],
  },
  {
    name: 'Sabaa Tahir',
    bio: "Sabaa Tahir is a New York Times bestselling author and former night editor at the Washington Post. Born in London and raised in the Mojave Desert in California, she drew on ancient Rome, the Mughal Empire, and Afghan folklore to create the world of An Ember in the Ashes (2015). The Ember in the Ashes series spans four novels and has sold millions of copies worldwide, praised for its brutal world-building, dual-POV structure, and deeply human characters. Her standalone All My Rage won the Pulitzer Prize for Fiction in 2023.",
    genre: 'fantasy',
    knownFor: ['An Ember in the Ashes', 'A Torch Against the Night', 'All My Rage'],
  },
  {
    name: 'Kiera Cass',
    bio: "Kiera Cass is an American author best known for The Selection series, a YA dystopian romance set in a future America where 35 girls compete to marry the prince. The original trilogy (The Selection, The Elite, The One) plus two follow-up novels became international bestsellers, appealing to fans of both romance and competition-driven dystopia. Cass is known for her accessible, addictive writing style and her ability to blend fairy-tale glamour with the emotional intensity of a love triangle.",
    genre: 'romance',
    knownFor: ['The Selection', 'The Elite', 'The One', 'The Heir'],
  },
  {
    name: 'Neal Shusterman',
    bio: "Neal Shusterman is a National Book Award-winning American author known for dark, high-concept YA fiction that explores the moral implications of technology, society, and human nature. His breakout YA thriller Unwind introduced the concept of 'unwinding' — teenage dissassembly that is disturbingly logical in his dystopian America. The Arc of a Scythe trilogy (Scythe, Thunderhead, The Toll) imagines a world where death has been defeated and a society of arbiters decides who dies. Shusterman is one of the most philosophically ambitious YA authors working today.",
    genre: 'sci-fi',
    knownFor: ['Scythe', 'Unwind', 'Challenger Deep', 'Thunderhead'],
  },
  {
    name: 'Tomi Adeyemi',
    bio: "Tomi Adeyemi is a Nigerian-American author whose debut novel Children of Blood and Bone (2018) became a #1 New York Times bestseller and a cultural phenomenon. Inspired by West African mythology and fueled by the Black Lives Matter movement, Adeyemi built a magic system rooted in Yoruba religion and a world that reflects the experience of racial dispossession. Children of Blood and Bone won multiple awards and launched a bidding war for film rights before publication. The Legacy of Orïsha trilogy continues her Orïsha universe.",
    genre: 'fantasy',
    knownFor: ['Children of Blood and Bone', 'Children of Virtue and Vengeance', 'Legacy of Orïsha'],
  },
  {
    name: 'Ally Condie',
    bio: "Ally Condie is a New York Times bestselling American author known for the Matched trilogy, a YA dystopian romance in which the Society controls every aspect of citizens' lives — including who they marry. The Matched trilogy became an international bestseller in the early 2010s, with film rights acquired by Disney. Condie's writing is lyrical and quiet compared to other YA dystopia, more interested in the interior emotional life of her protagonist than in action set pieces. She has also written the Atlantia duology and several standalone novels.",
    genre: 'fiction',
    knownFor: ['Matched', 'Crossed', 'Reached', 'Atlantia'],
  },
  {
    name: 'J.K. Rowling',
    bio: "J.K. Rowling is the British author of the Harry Potter series, the best-selling book series in history with over 600 million copies sold worldwide. She wrote the first Harry Potter novel while a single mother living on welfare in Edinburgh, and went on to become one of the wealthiest people in the United Kingdom through the books, films, and global Harry Potter franchise. Beyond Harry Potter, she has written the Cormoran Strike crime novels under the pen name Robert Galbraith. The Wizarding World has expanded into Pottermore, theme parks, stage plays, and the Fantastic Beasts film series.",
    genre: 'fantasy',
    knownFor: ['Harry Potter series', 'Fantastic Beasts', 'The Cormoran Strike series (as Robert Galbraith)'],
  },
  {
    name: 'Stephenie Meyer',
    bio: "Stephenie Meyer is an American author best known for the Twilight saga, which she began after dreaming about a girl in a meadow with a vampire who loved her but wanted to drink her blood. The four-book series sold over 160 million copies worldwide and became a blockbuster film franchise starring Kristen Stewart and Robert Pattinson. Meyer also wrote The Host (2008), a science fiction novel adapted into a 2013 film. Midnight Sun (2020) retells the first Twilight novel from Edward's perspective and became an instant #1 bestseller despite the original series concluding over a decade earlier.",
    genre: 'romance',
    knownFor: ['Twilight', 'New Moon', 'Eclipse', 'Breaking Dawn', 'The Host', 'Midnight Sun'],
  },
  {
    name: 'Kendare Blake',
    bio: "Kendare Blake is an American author of young adult fantasy known for the Three Dark Crowns series, a dark four-book saga set on a fictional island where every generation three triplet queens must fight to the death for the throne. Blake also wrote the Anna Dressed in Blood duology, a YA supernatural thriller about a teenage ghost hunter, and the Goddess War trilogy. Her work is known for its dark tone, morally complex female characters, and subversion of fairy-tale tropes. Three Dark Crowns was a New York Times bestseller and established Blake as a major voice in dark YA fantasy.",
    genre: 'fantasy',
    knownFor: ['Three Dark Crowns', 'One Dark Throne', 'Two Dark Reigns', 'Five Dark Fates', 'Anna Dressed in Blood'],
  },
  {
    name: 'Lauren Oliver',
    bio: "Lauren Oliver is a New York Times bestselling American author known for the Delirium trilogy, a YA dystopian romance series set in a future America where love has been classified as a disease and cured at age eighteen. Beyond Delirium, she wrote the Before I Fall standalone (adapted into a 2017 film), the Panic novel (adapted into an Amazon series), and the Replica duology. Oliver's writing is distinguished by its lyrical, literary prose — more akin to literary fiction than genre YA — and her interest in the psychology of conformity and identity under pressure.",
    genre: 'fiction',
    knownFor: ['Delirium', 'Pandemonium', 'Requiem', 'Before I Fall', 'Panic'],
  },
  {
    name: 'Scott Lynch',
    bio: "Scott Lynch is an American fantasy author known for the Gentleman Bastard Sequence, an ongoing heist fantasy series featuring Locke Lamora, a master con artist operating in the city of Camorr — a fantasy analog to Renaissance Venice built atop the ruins of an alien civilization. The first novel, The Lies of Locke Lamora (2006), was nominated for the World Fantasy Award and became a cult classic for its intricate plotting, dark humor, and detailed secondary world. Lynch is known for long gaps between books; three of a planned seven volumes have been published over nearly two decades.",
    genre: 'fantasy',
    knownFor: ['The Lies of Locke Lamora', 'Red Seas Under Red Skies', 'The Republic of Thieves'],
  },
  {
    name: 'Erin Morgenstern',
    bio: "Erin Morgenstern is an American author and visual artist known for The Night Circus (2011), a standalone fantasy novel about a mysterious black-and-white circus and two magicians bound in an ancient competition inside it. The Night Circus spent seven weeks on the New York Times bestseller list and has been translated into over 30 languages. Her second novel, The Starless Sea (2019), is a completely separate standalone about a graduate student who falls into an underground world of stories. Morgenstern is also a visual artist who creates paintings, mixed-media collages, and novels formatted as illustrated books.",
    genre: 'fantasy',
    knownFor: ['The Night Circus', 'The Starless Sea'],
  },
  {
    name: 'Madeline Miller',
    bio: "Madeline Miller is an American author and classicist known for two lyrical literary fantasy novels retelling Greek mythology. The Song of Achilles (2012) tells the Trojan War through Patroclus's perspective and won the Orange Prize for Fiction. Circe (2018) retells the life of the witch from Greek mythology and won the Goodreads Choice Award for Fantasy. Both novels became New York Times bestsellers and are widely used in academic literature courses. Miller studied Classics at Brown University and taught Latin and Greek for fifteen years before her debut was published.",
    genre: 'fantasy',
    knownFor: ['The Song of Achilles', 'Circe'],
  },
  {
    name: 'Katherine Arden',
    bio: "Katherine Arden is an American author known for the Winternight Trilogy, a historical fantasy set in medieval Russia drawing on authentic Slavic mythology. The trilogy — The Bear and the Nightingale (2017), The Girl in the Tower (2017), and The Winter of the Witch (2019) — follows Vasilisa Petrovna, a girl who can see the old spirits that Russian Christianity is erasing. Arden studied Russian at Middlebury College, lived in Moscow and Paris, and drew on extensive research into Russian folklore for the series. She also wrote Small Spaces, a middle-grade horror series.",
    genre: 'fantasy',
    knownFor: ['The Bear and the Nightingale', 'The Girl in the Tower', 'The Winter of the Witch'],
  },
  {
    name: 'S.A. Chakraborty',
    bio: "S.A. Chakraborty is an American author known for the Daevabad Trilogy, an adult fantasy series drawing on Islamic mythology, Arabophone history, and South Asian folklore. The trilogy — The City of Brass (2017), The Kingdom of the Wicked (2019), and The Empire of Gold (2020) — follows a con artist in 18th-century Cairo who is pulled into the hidden city of Daevabad and the ancient conflict between djinn tribes. Chakraborty also wrote The Adventures of Amina al-Sirafi (2023), a separate series in the same world set in the 12th century.",
    genre: 'fantasy',
    knownFor: ['The City of Brass', 'The Kingdom of the Wicked', 'The Empire of Gold', 'The Adventures of Amina al-Sirafi'],
  },
  {
    name: 'Arkady Martine',
    bio: "Arkady Martine is an American author and Byzantine historian whose Teixcalaan series — A Memory Called Empire (2019) and A Desolation Called Peace (2021) — is notable for being the only duology in which both books won the Hugo Award for Best Novel. Martine draws on her expertise in Byzantine imperial history to create Teixcalaan, an interstellar empire whose court culture, linguistic politics, and relationship to its periphery reflect Byzantine precedent. She also co-founded a crisis mapping initiative (Nola Rising) after Hurricane Katrina and teaches digital humanities.",
    genre: 'sci-fi',
    knownFor: ['A Memory Called Empire', 'A Desolation Called Peace'],
  },
  {
    name: 'Sue Lynn Tan',
    bio: "Sue Lynn Tan is a Malaysian-British author known for the Celestial Kingdom duology — Daughter of the Moon Goddess (2022) and Heart of the Sun Warrior (2022) — which draws on Chinese mythology, particularly the legend of Chang'e (the moon goddess) and the archer Houyi. The duology became a USA Today and Publishers Weekly bestseller and was praised for its lyrical prose and its care for the source mythology. Tan was born in Malaysia, educated in France and England, and now lives in Hong Kong.",
    genre: 'fantasy',
    knownFor: ['Daughter of the Moon Goddess', 'Heart of the Sun Warrior'],
  },
  {
    name: 'Katherine Addison',
    bio: "Katherine Addison is the pen name of American author Sarah Monette, known for The Goblin Emperor (2014), a standalone fantasy novel that became one of the foundational texts of cozy fantasy. The Goblin Emperor was nominated for the Hugo, Nebula, Locus, and World Fantasy Awards. Addison also wrote The Witness for the Dead (2021) and The Grief of Stones (2022), companion novels set in the same world. Under her real name Sarah Monette, she also wrote the Doctrine of Labyrinths fantasy series and co-wrote the Kyle Murchison Booth supernatural novellas.",
    genre: 'fantasy',
    knownFor: ['The Goblin Emperor', 'The Witness for the Dead', 'The Grief of Stones'],
  },
  {
    name: 'Maggie Stiefvater',
    bio: "Maggie Stiefvater is an American author of young adult fantasy known for the Raven Cycle — four books (The Raven Boys, The Dream Thieves, Blue Lily Lily Blue, The Raven King) following a girl from a family of psychics and the prep school boys searching for a sleeping Welsh king in Virginia. She also wrote Shiver (2009), a YA werewolf romance trilogy, and The Scorpio Races (2011), a standalone about water horses on an Irish island. Her prose is distinguished by its atmospheric, funny, and emotionally precise voice.",
    genre: 'fantasy',
    knownFor: ['The Raven Boys', 'The Scorpio Races', 'Shiver', 'The Dream Thieves'],
  },
  {
    name: 'Samantha Shannon',
    bio: "Samantha Shannon is a British author known for The Bone Season series (a fantasy series set in a near-future London) and The Priory of the Orange Tree (2019), an 850-page standalone epic fantasy widely praised as a landmark of feminist epic fantasy. Shannon began The Bone Season at Oxford University; it was published when she was 21 and compared to J.K. Rowling and Suzanne Collins. The Priory of the Orange Tree became one of the highest-profile standalone fantasy epics of the 2010s. Its prequel, A Day of Fallen Night, was published in 2023.",
    genre: 'fantasy',
    knownFor: ['The Priory of the Orange Tree', 'A Day of Fallen Night', 'The Bone Season'],
  },
  {
    name: 'Travis Baldree',
    bio: "Travis Baldree is an American author and audiobook narrator known for Legends & Lattes (2022), a cozy fantasy novel about an orc barbarian who retires from adventuring and opens a coffee shop — widely credited as one of the books that defined the cozy fantasy genre. Baldree originally self-published Legends & Lattes before it was acquired by Tor and became a bestseller. He has narrated over 500 audiobooks, including many fantasy and sci-fi titles. His second novel, Bookshops & Bonedust (2023), is a prequel to Legends & Lattes.",
    genre: 'fantasy',
    knownFor: ['Legends & Lattes', 'Bookshops & Bonedust'],
  },
  {
    name: 'Lauren DeStefano',
    bio: "Lauren DeStefano is an American author of young adult dystopian fiction known for the Chemical Garden Trilogy — Wither (2011), Fever (2012), and Sever (2013) — set in a future where a genetic engineering catastrophe has shortened human lifespans to 25 (women) and 20 (men). The trilogy is notable for its attention to the female protagonist's interior experience and its critique of reproductive control. DeStefano also wrote the Perfect Ruin series.",
    genre: 'fiction',
    knownFor: ['Wither', 'Fever', 'Sever'],
  },
  {
    name: 'T. Kingfisher',
    bio: "T. Kingfisher is the pen name of American author Ursula Vernon, used for work aimed at adult or older YA readers. Under this name she has written A Wizard's Guide to Defensive Baking (2020), a middle-grade fantasy about a baker who can magic bread; What Moves the Dead (2022), a Lovecraftian horror novella retelling of The Fall of the House of Usher; and the Clocktaur War duology, the Paladin's Grace series, and other adult fantasy-horror. As Ursula Vernon she also writes the award-winning Hamster Princess and Dragonbreath children's book series.",
    genre: 'fantasy',
    knownFor: ['A Wizard\'s Guide to Defensive Baking', 'What Moves the Dead', 'Paladin\'s Grace'],
  },
  {
    name: 'Jennifer Saint',
    bio: "Jennifer Saint is a British author of feminist mythology retellings. Her debut novel Ariadne (2021) retells the myth of Theseus and the Minotaur through the eyes of the Cretan princess who gave Theseus the thread — and her sister Phaedra. Ariadne was an immediate bestseller and established Saint as a leading voice in the growing genre of literary mythology retellings. She has since published Elektra (2022), which centers on Clytemnestra, Cassandra, and Elektra during the Trojan War's aftermath, and Atalanta (2023), a retelling of the myth of the female hero who ran faster than any man. All three novels are completely standalone.",
    genre: 'fiction',
    knownFor: ['Ariadne', 'Elektra', 'Atalanta'],
  },
  {
    name: 'Neil Gaiman',
    bio: "Neil Gaiman is a British author of fantasy, horror, and science fiction for adults and children, widely regarded as one of the most influential fantasy writers of the past 40 years. His adult novels include American Gods (2001), Anansi Boys (2005), Neverwhere (1996), and Stardust (1999). With Terry Pratchett he co-wrote Good Omens (1990). His children's books include Coraline (2002), The Graveyard Book (2008, Newbery Medal), and The Ocean at the End of the Lane (2013). He also wrote the comic book series The Sandman (1989–1996), which defined the literary potential of the form. American Gods and Good Omens have both been adapted into successful television series.",
    genre: 'fantasy',
    knownFor: ['American Gods', 'Stardust', 'Good Omens', 'Coraline', 'The Sandman'],
  },
  {
    name: 'Becky Chambers',
    bio: "Becky Chambers is an American science fiction author best known for the Wayfarers series — A Long Way to a Small, Angry Planet (2014), A Closed and Common Orbit (2016), Record of a Spaceborn Few (2018), and The Galaxy, and the Ground Within (2021) — a cozy, ensemble space opera series about ordinary people living ordinary lives in a galaxy full of different species. She also writes the Monk and Robot series, which began with A Psalm for the Wild-Built (2021). Chambers is credited with establishing the genre of 'cozy sci-fi' or 'hopepunk' — science fiction interested in cooperation, found family, and the texture of daily life rather than conflict and survival. She has won multiple Hugo Awards.",
    genre: 'sci-fi',
    knownFor: ['A Long Way to a Small, Angry Planet', 'A Psalm for the Wild-Built', 'A Closed and Common Orbit'],
  },
  {
    name: 'Evan Winter',
    bio: "Evan Winter is a South African-Canadian author of epic fantasy. His debut novel The Rage of Dragons (2019) — originally self-published, then picked up by Orbit — drew on Xhosa culture and Zulu history for its world-building, making it one of the first major epic fantasy series rooted in African rather than European medieval culture. The novel and its sequel The Fires of Vengeance (2020) form The Burning duology, a complete story. The series is praised for its technical combat, relentless pace, and the specificity of its world-building. Winter has said the series was directly influenced by his experience of not seeing his own cultural background reflected in the fantasy genre.",
    genre: 'fantasy',
    knownFor: ['The Rage of Dragons', 'The Fires of Vengeance'],
  },
  {
    name: 'Philip Pullman',
    bio: "Philip Pullman is a British author best known for His Dark Materials, a three-book fantasy trilogy consisting of The Golden Compass (1995), The Subtle Knife (1997), and The Amber Spyglass (2000). The trilogy began as children's fantasy and deepened into one of the most philosophically ambitious and theologically controversial works of speculative fiction ever written, drawing on Milton's Paradise Lost and engaging directly with questions of religious authority, consciousness, and freedom. The Amber Spyglass won the Whitbread Book of the Year Award in 2001, the first children's book to do so. Pullman has since written The Book of Dust, a companion series set in the same world: La Belle Sauvage (2017) and The Secret Commonwealth (2019).",
    genre: 'fantasy',
    knownFor: ['The Golden Compass', 'His Dark Materials', 'The Book of Dust'],
  },
  {
    name: 'James S.A. Corey',
    bio: "James S.A. Corey is the pen name of co-authors Daniel Abraham and Ty Franck, who together wrote The Expanse, a nine-book science fiction series set in a colonized solar system. The series began with Leviathan Wakes (2011) and concluded with Leviathan Falls (2021). The Expanse is praised for its hard scientific accuracy, its politically realistic depiction of three distinct civilizations in conflict, and its ensemble cast. The television adaptation (Amazon Prime, 2015–2022) ran for six seasons and is widely considered one of the greatest science fiction adaptations ever made. Daniel Abraham also writes epic fantasy under his own name; Ty Franck was a personal assistant to George R.R. Martin.",
    genre: 'sci-fi',
    knownFor: ['Leviathan Wakes', 'The Expanse', 'Nemesis Games'],
  },
  {
    name: 'Tracy Deonn',
    bio: "Tracy Deonn is an American author of YA fantasy. Her debut novel Legendborn (2020) was an immediate bestseller, centering on a Black girl who discovers a secret Arthurian society at the University of North Carolina at Chapel Hill and finds that her own family history is entangled with the society's magical legacy. Legendborn was praised for its integration of Arthurian mythology with American racial history — particularly the history of the American South — and won numerous awards including the Coretta Scott King Author Honor. She is writing a sequel trilogy under the Legendborn Cycle series title; Bloodmarked (2022) is the second book.",
    genre: 'fantasy',
    knownFor: ['Legendborn', 'Bloodmarked'],
  },
  {
    name: 'Marie Rutkoski',
    bio: "Marie Rutkoski is an American author of YA fantasy best known for The Winner's Trilogy — The Winner's Curse (2014), The Winner's Crime (2015), and The Winner's Kiss (2016). The trilogy is set in a fantasy world where the Herrani people were enslaved by the Valorian empire, and follows Kestrel, a Valorian general's daughter, and Arin, a Herrani slave she buys at auction. The series is praised for its sophisticated portrayal of colonialism, its strategically intelligent female protagonist, and its slow-burn romance built on genuine political stakes rather than proximity. Rutkoski previously wrote the Kronos Chronicles middle-grade series.",
    genre: 'fantasy',
    knownFor: ["The Winner's Curse", "The Winner's Crime", "The Winner's Kiss"],
  },
  {
    name: 'Orson Scott Card',
    bio: "Orson Scott Card is an American author best known for Ender's Game (1985), a science fiction novel about a child genius trained at Battle School to command humanity's fleet against an alien species. The novel won both the Hugo and Nebula Awards for Best Novel — the only science fiction novel to have won both in the same year. Card continued the series with Speaker for the Dead (1986), which won both awards again, and later wrote Ender's Shadow (1999), a parallel novel that retells Ender's Game from Bean's perspective and launched a second series set in the same universe. He is also the author of the Alvin Maker fantasy series.",
    genre: 'sci-fi',
    knownFor: ["Ender's Game", "Speaker for the Dead", "Ender's Shadow"],
  },
  {
    name: 'Naomi Novik',
    bio: "Naomi Novik is an American author of fantasy best known for two series: the Temeraire alternate-history fantasy series (9 books, 2006–2016), set during the Napoleonic Wars in a world where dragons are used as air forces, and the Scholomance trilogy (A Deadly Education, The Last Graduate, The Golden Enclaves), a YA fantasy about a lethal magical school. She also wrote the standalone dark fairy tale Uprooted (2015), which won the Nebula Award for Best Novel. Novik was previously a video game programmer and co-founder of the Organization for Transformative Works, which created the Archive of Our Own (AO3) fan fiction archive.",
    genre: 'fantasy',
    knownFor: ['A Deadly Education', 'Uprooted', 'The Scholomance'],
  },
  {
    name: 'Dan Simmons',
    bio: "Dan Simmons is an American author of science fiction and horror best known for the Hyperion Cantos, a four-book science fiction series beginning with Hyperion (1989), which won the Hugo Award for Best Novel. Hyperion is structured in the mode of The Canterbury Tales, with seven pilgrims telling their stories on the way to a world where an entity of blades and cruelty has been killing people for centuries. The follow-up The Fall of Hyperion (1990) completes the story arc. Simmons has also written the horror novel The Terror (2007), about the Franklin Expedition, and other genre fiction.",
    genre: 'sci-fi',
    knownFor: ['Hyperion', 'The Fall of Hyperion', 'The Terror'],
  },
  {
    name: 'Isaac Asimov',
    bio: "Isaac Asimov (1920–1992) was an American biochemist and prolific science fiction author who wrote or edited more than 500 books. He is best known for the Foundation series — a sweeping science fiction epic about the fall of the Galactic Empire and the mathematician Hari Seldon's plan to reduce the resulting dark age using psychohistory — and for the Robot series, which introduced the Three Laws of Robotics. The original Foundation trilogy (Foundation, Foundation and Empire, Second Foundation) won a one-time Hugo Award as the Best All-Time Series in 1966. Asimov is credited, along with Arthur C. Clarke and Robert A. Heinlein, with establishing the modern form of the science fiction novel.",
    genre: 'sci-fi',
    knownFor: ['Foundation', 'Foundation and Empire', 'I, Robot'],
  },
];

function normalize(s: string) {
  return s.toLowerCase().replace(/\.\s+/g, '.').replace(/\s+/g, ' ').trim();
}

export function getAuthorBio(name: string): AuthorBio | undefined {
  const n = normalize(name);
  return AUTHOR_BIOS.find((a) => normalize(a.name) === n);
}
