export interface AuthorBio {
  name: string;
  bio: string;
  genre: string;
  knownFor: string[];
}

const AUTHOR_BIOS: AuthorBio[] = [
  {
    name: 'Sarah J. Maas',
    bio: 'Sarah J. Maas is a #1 New York Times and internationally bestselling author of romantasy and epic fantasy. Her series include A Court of Thorns and Roses (ACOTAR), Throne of Glass (ToG), and Crescent City. Known for complex heroines, intricate world-building, and slow-burn romance, she has sold over 12 million books worldwide.',
    genre: 'fantasy',
    knownFor: ['ACOTAR', 'Throne of Glass', 'Crescent City'],
  },
  {
    name: 'Rebecca Yarros',
    bio: 'Rebecca Yarros is a #1 New York Times bestselling author and decorated US Air Force veteran spouse whose Empyrean series — beginning with Fourth Wing — became a global publishing phenomenon. Her romantasy novels are known for their dragon-riding world-building, enemies-to-lovers dynamics, and emotional depth.',
    genre: 'fantasy',
    knownFor: ['Fourth Wing', 'Iron Flame', 'Onyx Storm'],
  },
  {
    name: 'Brandon Sanderson',
    bio: 'Brandon Sanderson is a #1 New York Times and internationally bestselling fantasy author renowned for his intricate magic systems and the Cosmere — a shared universe spanning multiple series. His works include The Stormlight Archive, Mistborn, Elantris, Warbreaker, and The Way of Kings. He also completed Robert Jordan\'s Wheel of Time series.',
    genre: 'fantasy',
    knownFor: ['Stormlight Archive', 'Mistborn', 'Cosmere'],
  },
  {
    name: 'Colleen Hoover',
    bio: 'Colleen Hoover (CoHo) is a #1 New York Times bestselling author of contemporary romance and new adult fiction. A former social worker, she self-published her debut Slammed in 2012 and became one of the most popular romance authors in the world, powered significantly by BookTok. Her books include It Ends with Us, Ugly Love, Verity, and Reminders of Him.',
    genre: 'romance',
    knownFor: ['It Ends with Us', 'Ugly Love', 'Verity'],
  },
  {
    name: 'George R.R. Martin',
    bio: "George R.R. Martin is a New York Times bestselling author and the creator of A Song of Ice and Fire, the epic fantasy series that inspired HBO's Game of Thrones. Known for his morally complex characters, political intrigue, and subverted fantasy tropes, Martin is one of the most influential fantasy authors of the 21st century. Fans await The Winds of Winter, Book 6.",
    genre: 'fantasy',
    knownFor: ['A Song of Ice and Fire', 'Game of Thrones', 'Winds of Winter'],
  },
  {
    name: 'Gillian Flynn',
    bio: 'Gillian Flynn is a New York Times bestselling author of psychological thrillers known for their dark, razor-sharp prose and unreliable narrators. Her novels include Gone Girl, Dark Places, and Sharp Objects — all of which have been adapted for film and television. Flynn is also a screenwriter and television producer.',
    genre: 'thriller',
    knownFor: ['Gone Girl', 'Sharp Objects', 'Dark Places'],
  },
  {
    name: 'James Patterson',
    bio: "James Patterson is the world's bestselling fiction author and a #1 New York Times bestseller. Known for his fast-paced thrillers and prolific output — often co-authored — his series include Alex Cross, Michael Bennett, Women's Murder Club, and NYPD Red. He is also a major advocate for children's literacy.",
    genre: 'thriller',
    knownFor: ['Alex Cross', "Women's Murder Club", 'Michael Bennett'],
  },
  {
    name: 'Nora Roberts',
    bio: 'Nora Roberts is a #1 New York Times bestselling author of over 200 romance novels as well as futuristic suspense as J.D. Robb. One of the most prolific and successful romance authors in history, her In Death series (as J.D. Robb) has over 50 installments. She is a member of the Romance Writers of America Hall of Fame.',
    genre: 'romance',
    knownFor: ['In Death series', 'Chesapeake Bay', 'Irish trilogy'],
  },
  {
    name: 'Andy Weir',
    bio: 'Andy Weir is a New York Times bestselling science fiction author known for scientifically rigorous, fast-paced stories. His debut The Martian — self-published in 2011 before becoming a major motion picture — launched his career. He followed it with Artemis and Project Hail Mary.',
    genre: 'sci-fi',
    knownFor: ['The Martian', 'Project Hail Mary', 'Artemis'],
  },
  {
    name: 'Taylor Jenkins Reid',
    bio: 'Taylor Jenkins Reid is a New York Times bestselling author of contemporary fiction known for character-driven stories with Hollywood settings and historical depth. Her books include The Seven Husbands of Evelyn Hugo, Daisy Jones & The Six, Malibu Rising, and Carrie Soto Is Back.',
    genre: 'fiction',
    knownFor: ['The Seven Husbands of Evelyn Hugo', 'Daisy Jones & The Six', 'Malibu Rising'],
  },
  {
    name: 'Emily Henry',
    bio: 'Emily Henry is a #1 New York Times bestselling author of contemporary romance known for her witty banter, emotional depth, and slow-burn love stories. Her books include Beach Read, People We Meet on Vacation, Book Lovers, Happy Place, and Funny Story.',
    genre: 'romance',
    knownFor: ['Beach Read', 'People We Meet on Vacation', 'Book Lovers'],
  },
  {
    name: 'Ali Hazelwood',
    bio: 'Ali Hazelwood is a New York Times bestselling author of STEM romance — nerdy, witty love stories featuring scientists and academics. Her debut The Love Hypothesis launched a wave of academic romance. She also writes the Loathe to Love You and Bride series.',
    genre: 'romance',
    knownFor: ['The Love Hypothesis', 'Love on the Brain', 'Bride'],
  },
  {
    name: 'Leigh Bardugo',
    bio: 'Leigh Bardugo is a #1 New York Times bestselling author and creator of the Grishaverse — one of the most beloved fantasy universes in modern fiction. Her Six of Crows duology is widely regarded as among the best heist fantasy ever written, and the Shadow and Bone trilogy inspired a Netflix series. She is also the author of Wonder Woman: Warbringer.',
    genre: 'fantasy',
    knownFor: ['Six of Crows', 'Shadow and Bone', 'King of Scars'],
  },
  {
    name: 'Cassandra Clare',
    bio: 'Cassandra Clare is a #1 New York Times and #1 internationally bestselling author of the Shadowhunter Chronicles — one of the best-selling YA fantasy series of all time. Her interconnected series include The Mortal Instruments, The Infernal Devices, The Dark Artifices, and The Last Hours. She has sold over 50 million books worldwide.',
    genre: 'fantasy',
    knownFor: ['City of Bones', 'Clockwork Angel', 'Lady Midnight'],
  },
  {
    name: 'Rick Riordan',
    bio: "Rick Riordan is the #1 New York Times bestselling author of the Percy Jackson & The Olympians series and its many sequels and companions. A former middle school English and social studies teacher, Riordan created Percy Jackson to help his son with dyslexia. His Riordan-verse spans Greek, Roman, Egyptian, Norse, and various cultural mythologies. A Disney+ adaptation of Percy Jackson debuted in 2023.",
    genre: 'fantasy',
    knownFor: ['Percy Jackson & The Olympians', 'The Heroes of Olympus', 'The Kane Chronicles'],
  },
  {
    name: 'Diana Gabaldon',
    bio: 'Diana Gabaldon is the New York Times bestselling author of the Outlander series — a sweeping saga that blends historical fiction, time travel, romance, and adventure across 18th-century Scotland. With nine novels and multiple novellas, Outlander has sold over 50 million copies worldwide and inspired a long-running Starz television series.',
    genre: 'fiction',
    knownFor: ['Outlander', 'Dragonfly in Amber', 'The Fiery Cross'],
  },
  {
    name: 'Holly Black',
    bio: "Holly Black is a #1 New York Times bestselling author of dark and vivid fantasy novels for teens and adults. Her Folk of the Air trilogy — The Cruel Prince, The Wicked King, and The Queen of Nothing — brought her to mainstream prominence and became a defining series of modern YA fantasy. She is also the co-creator of The Spiderwick Chronicles with Tony DiTerlizzi.",
    genre: 'fantasy',
    knownFor: ['The Cruel Prince', 'The Wicked King', 'The Stolen Heir'],
  },
  {
    name: 'V.E. Schwab',
    bio: "V.E. Schwab (also known as Victoria Schwab) is a #1 New York Times bestselling author known for lush, character-driven speculative fiction. Her Shades of Magic trilogy follows a rare magician who travels between parallel Londons, while The Invisible Life of Addie LaRue became a literary phenomenon. She is also the author of the Villains duology (Vicious, Vengeful).",
    genre: 'fantasy',
    knownFor: ['A Darker Shade of Magic', 'The Invisible Life of Addie LaRue', 'Vicious'],
  },
  {
    name: 'Pierce Brown',
    bio: 'Pierce Brown is a #1 New York Times bestselling author and creator of the Red Rising Saga — a brutal, brilliantly plotted science fiction epic set in a future where humanity colonizes the solar system under a rigid color-coded caste system. Compared to Game of Thrones for its political complexity and willingness to upend expectations, the series has sold millions of copies worldwide.',
    genre: 'sci-fi',
    knownFor: ['Red Rising', 'Golden Son', 'Morning Star'],
  },
  {
    name: 'Jennifer L. Armentrout',
    bio: "Jennifer L. Armentrout is a #1 New York Times and internationally bestselling author of romantic fantasy, paranormal romance, and new adult fiction. She is best known for her Blood and Ash series, which begins with From Blood and Ash and has become one of the most beloved romantasy series of the decade. Armentrout is an extraordinarily prolific author with over 50 published books across multiple pen names and genres.",
    genre: 'fantasy',
    knownFor: ['From Blood and Ash', 'A Kingdom of Flesh and Fire', 'The War of Two Queens'],
  },
  {
    name: 'Jennifer Lynn Barnes',
    bio: "Jennifer Lynn Barnes is a New York Times bestselling author of YA mystery and thriller novels, as well as a professor of psychology. Her breakout series The Inheritance Games — following Avery Grambs, who unexpectedly inherits a billionaire's fortune — became a massive BookTok phenomenon and one of the best-selling YA series in recent years. Barnes brings her psychology expertise to crafting deeply engaging mysteries.",
    genre: 'thriller',
    knownFor: ['The Inheritance Games', 'The Hawthorne Legacy', 'The Final Gambit'],
  },
  {
    name: 'Julia Quinn',
    bio: "Julia Quinn is a New York Times bestselling author and one of the most beloved names in Regency romance. Her Bridgerton series — eight novels following the eight Bridgerton siblings — gained a massive new audience when Shonda Rhimes adapted it for Netflix, making Quinn a household name. Known for her wit, humor, and swoon-worthy heroes, Quinn holds a degree from Yale and attended Harvard Medical School before pursuing writing full time.",
    genre: 'romance',
    knownFor: ['The Duke and I', 'The Viscount Who Loved Me', 'Romancing Mr. Bridgerton'],
  },
  {
    name: 'Patrick Rothfuss',
    bio: "Patrick Rothfuss is an American fantasy author whose Kingkiller Chronicle — beginning with The Name of the Wind — is widely considered one of the finest fantasy series ever written. His prose is celebrated for its literary beauty and the depth of its world-building, particularly the musical and mythological systems of the world of Temerant. Fans have eagerly awaited The Doors of Stone, the concluding volume, for over a decade.",
    genre: 'fantasy',
    knownFor: ['The Name of the Wind', "The Wise Man's Fear", 'Doors of Stone'],
  },
  {
    name: 'Andrzej Sapkowski',
    bio: "Andrzej Sapkowski is a Polish fantasy author and creator of The Witcher saga, one of the most beloved and commercially successful fantasy franchises in the world. His morally complex Witcher stories — collected in The Last Wish and Sword of Destiny before expanding into the five-novel saga — inspired the award-winning CD Projekt Red video games and a Netflix series. Sapkowski is one of Europe's best-selling fantasy authors.",
    genre: 'fantasy',
    knownFor: ['The Last Wish', 'Blood of Elves', 'Lady of the Lake'],
  },
  {
    name: 'Ana Huang',
    bio: "Ana Huang is a New York Times bestselling author of contemporary romance whose Twisted Series became a global BookTok sensation. Beginning with Twisted Love, the series features wealthy, morally grey alpha heroes and the bold women who match them — a combination that resonated with millions of readers worldwide. Huang is one of the defining voices of the modern BookTok romance era.",
    genre: 'romance',
    knownFor: ['Twisted Love', 'Twisted Games', 'Twisted Hate'],
  },
  {
    name: 'Tahereh Mafi',
    bio: "Tahereh Mafi is a New York Times bestselling author best known for the Shatter Me series, a YA dystopian fantasy celebrated for its intensely lyrical, stream-of-consciousness prose style and its emotionally complex love triangle. Born in Iran and raised in Connecticut, Mafi has become one of the most distinctive stylistic voices in young adult fiction. The Shatter Me series has sold over 4 million copies worldwide.",
    genre: 'fantasy',
    knownFor: ['Shatter Me', 'Unravel Me', 'Ignite Me'],
  },
  {
    name: 'Olivie Blake',
    bio: "Olivie Blake is the pen name of Alexene Farol Follmuth, a New York Times bestselling author of dark fantasy and romantasy. Her novel The Atlas Six — originally self-published before being acquired by Tor — became a viral sensation for its morally complex ensemble cast, dense philosophical themes, and dark academia aesthetic. Blake is also the author of Masters of Death and One for My Enemy.",
    genre: 'fantasy',
    knownFor: ['The Atlas Six', 'The Atlas Paradox', 'The Atlas Complex'],
  },
  {
    name: 'Suzanne Collins',
    bio: "Suzanne Collins is the New York Times bestselling author of The Hunger Games trilogy, which has sold over 100 million copies worldwide and spawned a blockbuster film franchise. Before the Hunger Games, she wrote the Underland Chronicles (beginning with Gregor the Overlander). Her prequel The Ballad of Songbirds and Snakes (2020) and the forthcoming Sunrise on the Reaping (March 2026) continue the Panem universe. Collins was a television writer before turning to novels.",
    genre: 'sci-fi',
    knownFor: ['The Hunger Games', 'Catching Fire', 'Mockingjay'],
  },
  {
    name: 'Robert Jordan',
    bio: "Robert Jordan (pen name of James Oliver Rigney Jr.) was an American fantasy author best known for The Wheel of Time, a 14-novel epic that reshaped the genre and sold over 90 million copies worldwide. Jordan wrote prolifically — as many as 14 hours a day — and was working on the final three books when he died of cardiac amyloidosis in 2007. Brandon Sanderson completed the series from Jordan's extensive notes. The Wheel of Time premiered as an Amazon Prime Video series in 2021.",
    genre: 'fantasy',
    knownFor: ['The Eye of the World', 'The Shadow Rising', 'A Memory of Light'],
  },
  {
    name: 'R. F. Kuang',
    bio: "R.F. Kuang (Rebecca F. Kuang) is an American fantasy and literary fiction author whose work spans brutal military fantasy (The Poppy War trilogy), Oxford historical fantasy (Babel, 2022), and literary satire (Yellowface, 2023). A Marshall Scholar and Oxford graduate, Kuang brings deep historical and literary knowledge to genre fiction and is widely credited with opening doors for Asian voices in Anglo-American fantasy. She is one of the most acclaimed young authors working in any genre.",
    genre: 'fantasy',
    knownFor: ['The Poppy War', 'Babel', 'Yellowface'],
  },
  {
    name: 'Stephen King',
    bio: "Stephen King is one of the best-selling authors of all time, with over 350 million copies of his books sold worldwide. Known as the 'King of Horror,' his work spans horror, thriller, science fiction, and fantasy. The Dark Tower series — his magnum opus — weaves together the mythology of dozens of his other novels into a single connected universe. Major works include It, The Shining, The Stand, Carrie, Misery, and Pet Sematary. King continues publishing multiple books per year into his 70s.",
    genre: 'horror',
    knownFor: ['The Dark Tower', 'The Stand', 'It'],
  },
  {
    name: 'Lynda La Plante',
    bio: 'Lynda La Plante is a British crime writer and screenwriter whose Prime Suspect — starring Helen Mirren — became one of the most critically acclaimed crime dramas in television history. Her Jane Tennison and Anna Travis detective series are bestsellers in the UK and internationally. La Plante began as an actress before turning to writing, and has won numerous BAFTA and Edgar Awards. Her books are known for their gritty procedural realism and complex female leads.',
    genre: 'thriller',
    knownFor: ['Prime Suspect', 'Anna Travis series', 'Tennison'],
  },
  {
    name: 'Tia Williams',
    bio: "Tia Williams is a New York Times bestselling author of contemporary romance and women's fiction. Her novel Seven Days in June became a BookTok sensation for its searing depiction of a chronic pain survivor and a reunion romance between two Black writers. A former beauty editor, Williams is known for her lush prose and emotionally resonant characters. Her books include It Goes Like This and The Perfect Find.",
    genre: 'romance',
    knownFor: ['Seven Days in June', 'It Goes Like This', 'The Perfect Find'],
  },
  {
    name: 'Kelly Yang',
    bio: "Kelly Yang is a New York Times bestselling author of young adult and middle grade fiction. Her debut Front Desk (2018) — inspired by her own childhood as a Chinese immigrant growing up in motels — won the Asian/Pacific American Award for Literature and launched a beloved series. She is a founder of The Kelly Yang Project, which teaches essay writing and critical thinking to children worldwide. Her books champion immigrant stories and social justice themes.",
    genre: 'fiction',
    knownFor: ['Front Desk', 'Parachutes', 'New From Here'],
  },
  {
    name: 'Ia Genberg',
    bio: "Ia Genberg is a Swedish novelist whose debut The Details (original title: Detaljerna) won the Nordic Council's Literature Prize and the International Booker Prize in 2024. Written in precise, crystalline prose, The Details explores female friendship and memory through intimate portraits. Genberg is considered one of Sweden's most distinctive literary voices.",
    genre: 'fiction',
    knownFor: ['The Details'],
  },
  {
    name: 'Alka Joshi',
    bio: "Alka Joshi is a New York Times and USA Today bestselling author of literary fiction. Her debut The Henna Artist (2021) — set in 1950s Rajasthan — became a Reese's Book Club pick and launched the Jaipur Trilogy. Joshi draws on her Indian heritage to explore women's autonomy, art, and ambition in post-independence India. She worked as an advertising executive for over two decades before publishing her first novel at age 62.",
    genre: 'fiction',
    knownFor: ['The Henna Artist', 'The Secret Keeper of Jaipur', 'The Perfumist of Paris'],
  },
  {
    name: 'Saladin Ahmed',
    bio: "Saladin Ahmed is a Hugo Award-nominated fantasy author and comic book writer known for Throne of the Crescent Moon, a Nebula Award finalist set in a Middle Eastern-inspired fantasy world. As a comic writer, he has worked on Marvel's Black Bolt, Ms. Marvel, and Abbott for BOOM! Studios. Ahmed's work centers diverse, non-Eurocentric perspectives in genre fiction and has been translated into a dozen languages.",
    genre: 'fantasy',
    knownFor: ['Throne of the Crescent Moon', 'Black Bolt', 'Abbott'],
  },
  {
    name: 'Donna Andrews',
    bio: "Donna Andrews is an Agatha and Anthony Award-winning mystery author best known for the Meg Langslow series, featuring a blacksmith and amateur sleuth whose cases often involve birds (she raises ostriches). The series spans over 30 books and is beloved for its cozy small-town Virginia setting and humorous tone. Andrews also writes the Turing Hopper series featuring an artificial intelligence detective.",
    genre: 'mystery',
    knownFor: ['Meg Langslow series', 'Murder with Peacocks', 'Owl Be Home for Christmas'],
  },
  {
    name: 'Carolyn Haines',
    bio: "Carolyn Haines is a USA Today bestselling author of the Sarah Booth Delaney Mississippi Delta mystery series, featuring a Southern belle who teams up with the ghost of a flapper-era maid to solve crimes. A former journalist, Haines has written over 50 books across mystery, romance, and mainstream fiction. She also rescues animals and operates the Good Fortune Farm Refuge in Alabama.",
    genre: 'mystery',
    knownFor: ['Sarah Booth Delaney series', 'Bone to Pick', 'Charmed Bones'],
  },
  {
    name: 'Peter Straub',
    bio: "Peter Straub was a two-time Bram Stoker Award winner and World Fantasy Award winner widely considered one of the most literary voices in horror fiction. Ghost Story (1979) is regarded as a masterpiece of the genre, and he collaborated with Stephen King on The Talisman and Black House. Straub's work blended literary sophistication with supernatural horror, and he mentored generations of genre writers before his death in 2022.",
    genre: 'thriller',
    knownFor: ['Ghost Story', 'The Talisman', 'Koko'],
  },
  {
    name: 'Maurice Sendak',
    bio: "Maurice Sendak was one of the most celebrated and influential illustrators and authors in children's literature history. Where the Wild Things Are (1963) won the Caldecott Medal and is one of the best-selling picture books of all time, appearing in virtually every list of greatest children's books. Sendak worked with a distinctive emotional intensity that many considered radical for children's books. His other major works include In the Night Kitchen and Outside Over There.",
    genre: 'fiction',
    knownFor: ['Where the Wild Things Are', 'In the Night Kitchen', 'Higglety Pigglety Pop!'],
  },
  {
    name: 'Caitlin Crews',
    bio: "Caitlin Crews is a USA Today and New York Times bestselling author of over 100 contemporary and category romance novels, primarily for Harlequin Presents. Known for glamorous settings, brooding heroes, and emotionally charged plots, she writes billionaire romance, royal romance, and enemies-to-lovers stories beloved by romance readers worldwide.",
    genre: 'romance',
    knownFor: ['Harlequin Presents', 'The Playboy of Argentina', 'A Baby to Bind His Bride'],
  },
  {
    name: 'Millie Adams',
    bio: "Millie Adams is a pen name for a New York Times and USA Today bestselling romance author known for emotionally intense Harlequin Presents novels. Writing under the Adams name, she delivers passionate category romance featuring powerful heroes, strong heroines, and the kind of sweeping drama that defines the Presents line.",
    genre: 'romance',
    knownFor: ['Harlequin Presents', 'His Secretly Pregnant Cinderella'],
  },
  {
    name: 'Jackie Ashenden',
    bio: "Jackie Ashenden is a New Zealand-based New York Times and USA Today bestselling romance author with over 80 novels to her name, writing primarily for Harlequin Presents and Harlequin Dare. She's known for deeply emotional heroes, intense chemistry, and a penchant for brooding billionaires and alpha males who meet their match.",
    genre: 'romance',
    knownFor: ['Harlequin Presents', 'The Maid the Greek Married', 'A Vow to Claim His Hidden Son'],
  },
  {
    name: 'Louise Jensen',
    bio: "Louise Jensen is a Sunday Times and international bestselling author of psychological thrillers set primarily in the UK. Her novels The Date, The Family, The Stolen Sisters, and The Missing are known for domestic suspense, complex family dynamics, and twisty plots that keep readers guessing until the final page. Her debut novel The Sister was a Kindle #1 bestseller.",
    genre: 'thriller',
    knownFor: ['The Date', 'The Family', 'The Sister'],
  },
  {
    name: 'Rona Halsall',
    bio: "Rona Halsall is a UK bestselling author of psychological thrillers known for dark domestic suspense and unreliable narrators. Her novels including Keep You Safe, Love You Gone, and Her Mother's Lies feature gripping plots built around family secrets, betrayal, and dangerous obsessions. She has sold over a million copies worldwide.",
    genre: 'thriller',
    knownFor: ['Keep You Safe', 'Love You Gone', "Her Mother's Lies"],
  },
  {
    name: 'Pepper Winters',
    bio: "Pepper Winters is a New York Times and USA Today bestselling author of dark romance, known for morally complex characters and emotionally intense storylines. Her Tears of Tess series launched her career, and she has since written dozens of novels across multiple series including Dollar, Indebted, and Monsters in the Dark, consistently appearing on bestseller lists.",
    genre: 'romance',
    knownFor: ['Tears of Tess', 'Dollar Series', 'Indebted Series'],
  },
  {
    name: 'Skye Warren',
    bio: "Skye Warren is a New York Times and USA Today bestselling author of dark and contemporary romance. Known for her psychological depth and exploration of taboo themes within romance, she has published over 50 novels including the Endgame trilogy, The Trust Fund Duet, and Survival of the Richest. Her books consistently land on major bestseller lists.",
    genre: 'romance',
    knownFor: ['Endgame Series', 'Survival of the Richest', 'The Trust Fund Duet'],
  },
  {
    name: 'Willow Winters',
    bio: "Willow Winters is a USA Today bestselling author of contemporary and dark romance with over 60 novels published. Known for standalone novels and connected series featuring emotionally complex romances, her prolific output and dedicated readership have made her a staple of the self-publishing romance market. Her Merciless World and This Love Hurts series are among her most popular.",
    genre: 'romance',
    knownFor: ['Merciless World', 'This Love Hurts', 'Bad Boys series'],
  },
  {
    name: 'Suzanne Enoch',
    bio: "Suzanne Enoch is a New York Times bestselling author of historical and contemporary romance with over 40 novels to her name. Best known for her Regency romance series including Scandalous Brides, Lessons in Love, and The Adventurers Club, she brings witty heroines and roguish heroes to the Georgian and Regency eras with warmth and humor.",
    genre: 'romance',
    knownFor: ['Scandalous Brides', 'The Adventurers Club', 'Samantha Jellicoe series'],
  },
  {
    name: 'Karen Hawkins',
    bio: "Karen Hawkins is a New York Times and USA Today bestselling author of historical and contemporary romance. She is best known for her MacLean Curse series and the Hurst Amulet series set in Regency England, as well as her charming contemporary romance series set in Dove Pond, South Carolina — small-town romance featuring sisterhood and Southern warmth.",
    genre: 'romance',
    knownFor: ['MacLean Curse', 'Dove Pond series', 'Hurst Amulet'],
  },
  {
    name: 'Charlie Jane Anders',
    bio: "Charlie Jane Anders is a Hugo, Nebula, and Locus Award-winning author of science fiction and fantasy. Her debut novel All the Birds in the Sky won the Nebula Award for Best Novel. She is also known for The City in the Middle of the Night and the Unstoppable series. Anders co-founded io9, the influential science fiction blog, and is a prominent voice in speculative fiction.",
    genre: 'sci-fi',
    knownFor: ['All the Birds in the Sky', 'The City in the Middle of the Night', 'Victories Greater Than Death'],
  },
  {
    name: 'Fran Wilde',
    bio: "Fran Wilde is a Hugo and Nebula Award-winning author of science fiction and fantasy. Her debut novel Updraft won the Andre Norton Nebula Award and is the first book in the Bone Universe series. She is known for intricate world-building that defies genre conventions, weaving together fantasy, science fiction, and social commentary. Her novella The Jewel and Her Lapidary is also a fan favorite.",
    genre: 'fantasy',
    knownFor: ['Updraft', 'Cloudbound', 'The Jewel and Her Lapidary'],
  },
  {
    name: 'Dani Collins',
    bio: "Dani Collins is a USA Today bestselling author of category romance, publishing almost exclusively with Harlequin Presents. A prolific Canadian author with over 70 novels, she is known for sweeping international settings, deeply emotional plots, and the glamorous tension that defines the Presents line. She writes alpha billionaires and independent heroines navigating love against all odds.",
    genre: 'romance',
    knownFor: ['Harlequin Presents', 'Their Reunion Vow', 'A Hidden Heir to Redeem Him'],
  },
  {
    name: 'James Dashner',
    bio: "James Dashner is the American author of the Maze Runner series, one of the defining YA dystopian trilogies of the 2010s. He began his writing career with the 13th Reality series before The Maze Runner (2009) launched him to international bestseller status. The series was adapted into a blockbuster film franchise beginning in 2014. Dashner is known for high-concept premises that drop readers into dangerous situations with few answers, forcing characters and readers alike to piece together the truth.",
    genre: 'fiction',
    knownFor: ['The Maze Runner', 'The Scorch Trials', 'The Death Cure', 'The 13th Reality'],
  },
  {
    name: 'Veronica Roth',
    bio: "Veronica Roth is the New York Times bestselling author of the Divergent trilogy, which she wrote while studying creative writing at Northwestern University. The trilogy — Divergent (2011), Insurgent (2012), and Allegiant (2013) — sold over 35 million copies worldwide and was adapted into a major film franchise starring Shailene Woodley. After Divergent, Roth moved into adult SFF with the Carve the Mark duology and the dark fantasy Chosen Ones.",
    genre: 'fiction',
    knownFor: ['Divergent', 'Insurgent', 'Allegiant', 'Chosen Ones'],
  },
  {
    name: 'Richelle Mead',
    bio: "Richelle Mead is a New York Times bestselling author known primarily for her Vampire Academy series and its Bloodlines spinoff. Born in Michigan, Mead combines paranormal romance with boarding school drama and supernatural hierarchy, creating one of the best-loved YA vampire series of the 2000s. Her adult urban fantasy series Succubus Blues and the Georgina Kincaid series established her adult readership. The Vampire Academy film adaptation premiered in 2014.",
    genre: 'romance',
    knownFor: ['Vampire Academy', 'Bloodlines', 'Succubus Blues', 'Georgina Kincaid series'],
  },
  {
    name: 'Christopher Paolini',
    bio: "Christopher Paolini is an American author who began writing Eragon at the age of fifteen, making him one of the youngest authors to achieve international bestseller status with a debut novel. The Inheritance Cycle — Eragon (2003), Eldest (2005), Brisingr (2008), and Inheritance (2011) — has sold over 35 million copies worldwide. Paolini returned to the world of Alagaësia with Murtagh (2023). He has also written To Be Taught, If Fortunate, a science fiction novella, and is working on a new sci-fi novel, The Fractal Shroud.",
    genre: 'fantasy',
    knownFor: ['Eragon', 'Eldest', 'Brisingr', 'Inheritance', 'Murtagh'],
  },
  {
    name: 'Marie Lu',
    bio: "Marie Lu is the New York Times bestselling author of the Legend trilogy, the Young Elites trilogy, and the Warcross duology. Born in China and raised in Texas, Lu worked as an art director in video games before her debut novel Legend (2011) launched her writing career. Known for propulsive dual-POV storytelling, morally complex heroes, and class-war themes, she has established herself as one of the defining YA authors of her generation. The Legend trilogy has sold millions of copies in over 30 languages.",
    genre: 'fiction',
    knownFor: ['Legend', 'The Young Elites', 'Warcross', 'Batman: Nightwalker'],
  },
  {
    name: 'Victoria Aveyard',
    bio: "Victoria Aveyard is the New York Times bestselling author of the Red Queen series, her debut YA fantasy novel that became a phenomenon when published in 2015. Aveyard grew up in East Longmeadow, Massachusetts and studied screenwriting at USC before writing Red Queen. The Red Queen series — spanning four novels and multiple novellas — has sold over 10 million copies worldwide. She has also written Realm Breaker, an epic fantasy series for adults.",
    genre: 'fiction',
    knownFor: ['Red Queen', 'Glass Sword', 'War Storm', 'Realm Breaker'],
  },
  {
    name: 'Frank Herbert',
    bio: "Frank Herbert (1920–1986) was an American science fiction author best known for Dune (1965), the bestselling science fiction novel of all time with over 20 million copies sold. A former journalist and ecological thinker, Herbert spent six years researching Oregon sand dunes before writing Dune, which transformed his observations on ecology, religion, and power into the planet Arrakis. He wrote five sequels before his death in 1986. Denis Villeneuve's film adaptations (2021, 2024) introduced Dune to a new generation.",
    genre: 'sci-fi',
    knownFor: ['Dune', 'Dune Messiah', 'Children of Dune', 'God Emperor of Dune'],
  },
  {
    name: 'Sabaa Tahir',
    bio: "Sabaa Tahir is a New York Times bestselling author and former night editor at the Washington Post. Born in London and raised in the Mojave Desert in California, she drew on ancient Rome, the Mughal Empire, and Afghan folklore to create the world of An Ember in the Ashes (2015). The Ember in the Ashes series spans four novels and has sold millions of copies worldwide, praised for its brutal world-building, dual-POV structure, and deeply human characters. Her standalone All My Rage won the Pulitzer Prize for Fiction in 2023.",
    genre: 'fantasy',
    knownFor: ['An Ember in the Ashes', 'A Torch Against the Night', 'All My Rage'],
  },
  {
    name: 'Kiera Cass',
    bio: "Kiera Cass is an American author best known for The Selection series, a YA dystopian romance set in a future America where 35 girls compete to marry the prince. The original trilogy (The Selection, The Elite, The One) plus two follow-up novels became international bestsellers, appealing to fans of both romance and competition-driven dystopia. Cass is known for her accessible, addictive writing style and her ability to blend fairy-tale glamour with the emotional intensity of a love triangle.",
    genre: 'romance',
    knownFor: ['The Selection', 'The Elite', 'The One', 'The Heir'],
  },
  {
    name: 'Neal Shusterman',
    bio: "Neal Shusterman is a National Book Award-winning American author known for dark, high-concept YA fiction that explores the moral implications of technology, society, and human nature. His breakout YA thriller Unwind introduced the concept of 'unwinding' — teenage dissassembly that is disturbingly logical in his dystopian America. The Arc of a Scythe trilogy (Scythe, Thunderhead, The Toll) imagines a world where death has been defeated and a society of arbiters decides who dies. Shusterman is one of the most philosophically ambitious YA authors working today.",
    genre: 'sci-fi',
    knownFor: ['Scythe', 'Unwind', 'Challenger Deep', 'Thunderhead'],
  },
  {
    name: 'Tomi Adeyemi',
    bio: "Tomi Adeyemi is a Nigerian-American author whose debut novel Children of Blood and Bone (2018) became a #1 New York Times bestseller and a cultural phenomenon. Inspired by West African mythology and fueled by the Black Lives Matter movement, Adeyemi built a magic system rooted in Yoruba religion and a world that reflects the experience of racial dispossession. Children of Blood and Bone won multiple awards and launched a bidding war for film rights before publication. The Legacy of Orïsha trilogy continues her Orïsha universe.",
    genre: 'fantasy',
    knownFor: ['Children of Blood and Bone', 'Children of Virtue and Vengeance', 'Legacy of Orïsha'],
  },
  {
    name: 'Ally Condie',
    bio: "Ally Condie is a New York Times bestselling American author known for the Matched trilogy, a YA dystopian romance in which the Society controls every aspect of citizens' lives — including who they marry. The Matched trilogy became an international bestseller in the early 2010s, with film rights acquired by Disney. Condie's writing is lyrical and quiet compared to other YA dystopia, more interested in the interior emotional life of her protagonist than in action set pieces. She has also written the Atlantia duology and several standalone novels.",
    genre: 'fiction',
    knownFor: ['Matched', 'Crossed', 'Reached', 'Atlantia'],
  },
  {
    name: 'J.K. Rowling',
    bio: "J.K. Rowling is the British author of the Harry Potter series, the best-selling book series in history with over 600 million copies sold worldwide. She wrote the first Harry Potter novel while a single mother living on welfare in Edinburgh, and went on to become one of the wealthiest people in the United Kingdom through the books, films, and global Harry Potter franchise. Beyond Harry Potter, she has written the Cormoran Strike crime novels under the pen name Robert Galbraith. The Wizarding World has expanded into Pottermore, theme parks, stage plays, and the Fantastic Beasts film series.",
    genre: 'fantasy',
    knownFor: ['Harry Potter series', 'Fantastic Beasts', 'The Cormoran Strike series (as Robert Galbraith)'],
  },
  {
    name: 'Stephenie Meyer',
    bio: "Stephenie Meyer is an American author best known for the Twilight saga, which she began after dreaming about a girl in a meadow with a vampire who loved her but wanted to drink her blood. The four-book series sold over 160 million copies worldwide and became a blockbuster film franchise starring Kristen Stewart and Robert Pattinson. Meyer also wrote The Host (2008), a science fiction novel adapted into a 2013 film. Midnight Sun (2020) retells the first Twilight novel from Edward's perspective and became an instant #1 bestseller despite the original series concluding over a decade earlier.",
    genre: 'romance',
    knownFor: ['Twilight', 'New Moon', 'Eclipse', 'Breaking Dawn', 'The Host', 'Midnight Sun'],
  },
  {
    name: 'Kendare Blake',
    bio: "Kendare Blake is an American author of young adult fantasy known for the Three Dark Crowns series, a dark four-book saga set on a fictional island where every generation three triplet queens must fight to the death for the throne. Blake also wrote the Anna Dressed in Blood duology, a YA supernatural thriller about a teenage ghost hunter, and the Goddess War trilogy. Her work is known for its dark tone, morally complex female characters, and subversion of fairy-tale tropes. Three Dark Crowns was a New York Times bestseller and established Blake as a major voice in dark YA fantasy.",
    genre: 'fantasy',
    knownFor: ['Three Dark Crowns', 'One Dark Throne', 'Two Dark Reigns', 'Five Dark Fates', 'Anna Dressed in Blood'],
  },
  {
    name: 'Lauren Oliver',
    bio: "Lauren Oliver is a New York Times bestselling American author known for the Delirium trilogy, a YA dystopian romance series set in a future America where love has been classified as a disease and cured at age eighteen. Beyond Delirium, she wrote the Before I Fall standalone (adapted into a 2017 film), the Panic novel (adapted into an Amazon series), and the Replica duology. Oliver's writing is distinguished by its lyrical, literary prose — more akin to literary fiction than genre YA — and her interest in the psychology of conformity and identity under pressure.",
    genre: 'fiction',
    knownFor: ['Delirium', 'Pandemonium', 'Requiem', 'Before I Fall', 'Panic'],
  },
  {
    name: 'Scott Lynch',
    bio: "Scott Lynch is an American fantasy author known for the Gentleman Bastard Sequence, an ongoing heist fantasy series featuring Locke Lamora, a master con artist operating in the city of Camorr — a fantasy analog to Renaissance Venice built atop the ruins of an alien civilization. The first novel, The Lies of Locke Lamora (2006), was nominated for the World Fantasy Award and became a cult classic for its intricate plotting, dark humor, and detailed secondary world. Lynch is known for long gaps between books; three of a planned seven volumes have been published over nearly two decades.",
    genre: 'fantasy',
    knownFor: ['The Lies of Locke Lamora', 'Red Seas Under Red Skies', 'The Republic of Thieves'],
  },
  {
    name: 'Erin Morgenstern',
    bio: "Erin Morgenstern is an American author and visual artist known for The Night Circus (2011), a standalone fantasy novel about a mysterious black-and-white circus and two magicians bound in an ancient competition inside it. The Night Circus spent seven weeks on the New York Times bestseller list and has been translated into over 30 languages. Her second novel, The Starless Sea (2019), is a completely separate standalone about a graduate student who falls into an underground world of stories. Morgenstern is also a visual artist who creates paintings, mixed-media collages, and novels formatted as illustrated books.",
    genre: 'fantasy',
    knownFor: ['The Night Circus', 'The Starless Sea'],
  },
  {
    name: 'Madeline Miller',
    bio: "Madeline Miller is an American author and classicist known for two lyrical literary fantasy novels retelling Greek mythology. The Song of Achilles (2012) tells the Trojan War through Patroclus's perspective and won the Orange Prize for Fiction. Circe (2018) retells the life of the witch from Greek mythology and won the Goodreads Choice Award for Fantasy. Both novels became New York Times bestsellers and are widely used in academic literature courses. Miller studied Classics at Brown University and taught Latin and Greek for fifteen years before her debut was published.",
    genre: 'fantasy',
    knownFor: ['The Song of Achilles', 'Circe'],
  },
  {
    name: 'Katherine Arden',
    bio: "Katherine Arden is an American author known for the Winternight Trilogy, a historical fantasy set in medieval Russia drawing on authentic Slavic mythology. The trilogy — The Bear and the Nightingale (2017), The Girl in the Tower (2017), and The Winter of the Witch (2019) — follows Vasilisa Petrovna, a girl who can see the old spirits that Russian Christianity is erasing. Arden studied Russian at Middlebury College, lived in Moscow and Paris, and drew on extensive research into Russian folklore for the series. She also wrote Small Spaces, a middle-grade horror series.",
    genre: 'fantasy',
    knownFor: ['The Bear and the Nightingale', 'The Girl in the Tower', 'The Winter of the Witch'],
  },
  {
    name: 'S.A. Chakraborty',
    bio: "S.A. Chakraborty is an American author known for the Daevabad Trilogy, an adult fantasy series drawing on Islamic mythology, Arabophone history, and South Asian folklore. The trilogy — The City of Brass (2017), The Kingdom of the Wicked (2019), and The Empire of Gold (2020) — follows a con artist in 18th-century Cairo who is pulled into the hidden city of Daevabad and the ancient conflict between djinn tribes. Chakraborty also wrote The Adventures of Amina al-Sirafi (2023), a separate series in the same world set in the 12th century.",
    genre: 'fantasy',
    knownFor: ['The City of Brass', 'The Kingdom of the Wicked', 'The Empire of Gold', 'The Adventures of Amina al-Sirafi'],
  },
  {
    name: 'Arkady Martine',
    bio: "Arkady Martine is an American author and Byzantine historian whose Teixcalaan series — A Memory Called Empire (2019) and A Desolation Called Peace (2021) — is notable for being the only duology in which both books won the Hugo Award for Best Novel. Martine draws on her expertise in Byzantine imperial history to create Teixcalaan, an interstellar empire whose court culture, linguistic politics, and relationship to its periphery reflect Byzantine precedent. She also co-founded a crisis mapping initiative (Nola Rising) after Hurricane Katrina and teaches digital humanities.",
    genre: 'sci-fi',
    knownFor: ['A Memory Called Empire', 'A Desolation Called Peace'],
  },
  {
    name: 'Sue Lynn Tan',
    bio: "Sue Lynn Tan is a Malaysian-British author known for the Celestial Kingdom duology — Daughter of the Moon Goddess (2022) and Heart of the Sun Warrior (2022) — which draws on Chinese mythology, particularly the legend of Chang'e (the moon goddess) and the archer Houyi. The duology became a USA Today and Publishers Weekly bestseller and was praised for its lyrical prose and its care for the source mythology. Tan was born in Malaysia, educated in France and England, and now lives in Hong Kong.",
    genre: 'fantasy',
    knownFor: ['Daughter of the Moon Goddess', 'Heart of the Sun Warrior'],
  },
  {
    name: 'Katherine Addison',
    bio: "Katherine Addison is the pen name of American author Sarah Monette, known for The Goblin Emperor (2014), a standalone fantasy novel that became one of the foundational texts of cozy fantasy. The Goblin Emperor was nominated for the Hugo, Nebula, Locus, and World Fantasy Awards. Addison also wrote The Witness for the Dead (2021) and The Grief of Stones (2022), companion novels set in the same world. Under her real name Sarah Monette, she also wrote the Doctrine of Labyrinths fantasy series and co-wrote the Kyle Murchison Booth supernatural novellas.",
    genre: 'fantasy',
    knownFor: ['The Goblin Emperor', 'The Witness for the Dead', 'The Grief of Stones'],
  },
  {
    name: 'Maggie Stiefvater',
    bio: "Maggie Stiefvater is an American author of young adult fantasy known for the Raven Cycle — four books (The Raven Boys, The Dream Thieves, Blue Lily Lily Blue, The Raven King) following a girl from a family of psychics and the prep school boys searching for a sleeping Welsh king in Virginia. She also wrote Shiver (2009), a YA werewolf romance trilogy, and The Scorpio Races (2011), a standalone about water horses on an Irish island. Her prose is distinguished by its atmospheric, funny, and emotionally precise voice.",
    genre: 'fantasy',
    knownFor: ['The Raven Boys', 'The Scorpio Races', 'Shiver', 'The Dream Thieves'],
  },
  {
    name: 'Samantha Shannon',
    bio: "Samantha Shannon is a British author known for The Bone Season series (a fantasy series set in a near-future London) and The Priory of the Orange Tree (2019), an 850-page standalone epic fantasy widely praised as a landmark of feminist epic fantasy. Shannon began The Bone Season at Oxford University; it was published when she was 21 and compared to J.K. Rowling and Suzanne Collins. The Priory of the Orange Tree became one of the highest-profile standalone fantasy epics of the 2010s. Its prequel, A Day of Fallen Night, was published in 2023.",
    genre: 'fantasy',
    knownFor: ['The Priory of the Orange Tree', 'A Day of Fallen Night', 'The Bone Season'],
  },
  {
    name: 'Travis Baldree',
    bio: "Travis Baldree is an American author and audiobook narrator known for Legends & Lattes (2022), a cozy fantasy novel about an orc barbarian who retires from adventuring and opens a coffee shop — widely credited as one of the books that defined the cozy fantasy genre. Baldree originally self-published Legends & Lattes before it was acquired by Tor and became a bestseller. He has narrated over 500 audiobooks, including many fantasy and sci-fi titles. His second novel, Bookshops & Bonedust (2023), is a prequel to Legends & Lattes.",
    genre: 'fantasy',
    knownFor: ['Legends & Lattes', 'Bookshops & Bonedust'],
  },
  {
    name: 'Lauren DeStefano',
    bio: "Lauren DeStefano is an American author of young adult dystopian fiction known for the Chemical Garden Trilogy — Wither (2011), Fever (2012), and Sever (2013) — set in a future where a genetic engineering catastrophe has shortened human lifespans to 25 (women) and 20 (men). The trilogy is notable for its attention to the female protagonist's interior experience and its critique of reproductive control. DeStefano also wrote the Perfect Ruin series.",
    genre: 'fiction',
    knownFor: ['Wither', 'Fever', 'Sever'],
  },
  {
    name: 'T. Kingfisher',
    bio: "T. Kingfisher is the pen name of American author Ursula Vernon, used for work aimed at adult or older YA readers. Under this name she has written A Wizard's Guide to Defensive Baking (2020), a middle-grade fantasy about a baker who can magic bread; What Moves the Dead (2022), a Lovecraftian horror novella retelling of The Fall of the House of Usher; and the Clocktaur War duology, the Paladin's Grace series, and other adult fantasy-horror. As Ursula Vernon she also writes the award-winning Hamster Princess and Dragonbreath children's book series.",
    genre: 'fantasy',
    knownFor: ['A Wizard\'s Guide to Defensive Baking', 'What Moves the Dead', 'Paladin\'s Grace'],
  },
  {
    name: 'Jennifer Saint',
    bio: "Jennifer Saint is a British author of feminist mythology retellings. Her debut novel Ariadne (2021) retells the myth of Theseus and the Minotaur through the eyes of the Cretan princess who gave Theseus the thread — and her sister Phaedra. Ariadne was an immediate bestseller and established Saint as a leading voice in the growing genre of literary mythology retellings. She has since published Elektra (2022), which centers on Clytemnestra, Cassandra, and Elektra during the Trojan War's aftermath, and Atalanta (2023), a retelling of the myth of the female hero who ran faster than any man. All three novels are completely standalone.",
    genre: 'fiction',
    knownFor: ['Ariadne', 'Elektra', 'Atalanta'],
  },
  {
    name: 'Neil Gaiman',
    bio: "Neil Gaiman is a British author of fantasy, horror, and science fiction for adults and children, widely regarded as one of the most influential fantasy writers of the past 40 years. His adult novels include American Gods (2001), Anansi Boys (2005), Neverwhere (1996), and Stardust (1999). With Terry Pratchett he co-wrote Good Omens (1990). His children's books include Coraline (2002), The Graveyard Book (2008, Newbery Medal), and The Ocean at the End of the Lane (2013). He also wrote the comic book series The Sandman (1989–1996), which defined the literary potential of the form. American Gods and Good Omens have both been adapted into successful television series.",
    genre: 'fantasy',
    knownFor: ['American Gods', 'Stardust', 'Good Omens', 'Coraline', 'The Sandman'],
  },
  {
    name: 'Becky Chambers',
    bio: "Becky Chambers is an American science fiction author best known for the Wayfarers series — A Long Way to a Small, Angry Planet (2014), A Closed and Common Orbit (2016), Record of a Spaceborn Few (2018), and The Galaxy, and the Ground Within (2021) — a cozy, ensemble space opera series about ordinary people living ordinary lives in a galaxy full of different species. She also writes the Monk and Robot series, which began with A Psalm for the Wild-Built (2021). Chambers is credited with establishing the genre of 'cozy sci-fi' or 'hopepunk' — science fiction interested in cooperation, found family, and the texture of daily life rather than conflict and survival. She has won multiple Hugo Awards.",
    genre: 'sci-fi',
    knownFor: ['A Long Way to a Small, Angry Planet', 'A Psalm for the Wild-Built', 'A Closed and Common Orbit'],
  },
  {
    name: 'Evan Winter',
    bio: "Evan Winter is a South African-Canadian author of epic fantasy. His debut novel The Rage of Dragons (2019) — originally self-published, then picked up by Orbit — drew on Xhosa culture and Zulu history for its world-building, making it one of the first major epic fantasy series rooted in African rather than European medieval culture. The novel and its sequel The Fires of Vengeance (2020) form The Burning duology, a complete story. The series is praised for its technical combat, relentless pace, and the specificity of its world-building. Winter has said the series was directly influenced by his experience of not seeing his own cultural background reflected in the fantasy genre.",
    genre: 'fantasy',
    knownFor: ['The Rage of Dragons', 'The Fires of Vengeance'],
  },
  {
    name: 'Philip Pullman',
    bio: "Philip Pullman is a British author best known for His Dark Materials, a three-book fantasy trilogy consisting of The Golden Compass (1995), The Subtle Knife (1997), and The Amber Spyglass (2000). The trilogy began as children's fantasy and deepened into one of the most philosophically ambitious and theologically controversial works of speculative fiction ever written, drawing on Milton's Paradise Lost and engaging directly with questions of religious authority, consciousness, and freedom. The Amber Spyglass won the Whitbread Book of the Year Award in 2001, the first children's book to do so. Pullman has since written The Book of Dust, a companion series set in the same world: La Belle Sauvage (2017) and The Secret Commonwealth (2019).",
    genre: 'fantasy',
    knownFor: ['The Golden Compass', 'His Dark Materials', 'The Book of Dust'],
  },
  {
    name: 'James S.A. Corey',
    bio: "James S.A. Corey is the pen name of co-authors Daniel Abraham and Ty Franck, who together wrote The Expanse, a nine-book science fiction series set in a colonized solar system. The series began with Leviathan Wakes (2011) and concluded with Leviathan Falls (2021). The Expanse is praised for its hard scientific accuracy, its politically realistic depiction of three distinct civilizations in conflict, and its ensemble cast. The television adaptation (Amazon Prime, 2015–2022) ran for six seasons and is widely considered one of the greatest science fiction adaptations ever made. Daniel Abraham also writes epic fantasy under his own name; Ty Franck was a personal assistant to George R.R. Martin.",
    genre: 'sci-fi',
    knownFor: ['Leviathan Wakes', 'The Expanse', 'Nemesis Games'],
  },
  {
    name: 'Tracy Deonn',
    bio: "Tracy Deonn is an American author of YA fantasy. Her debut novel Legendborn (2020) was an immediate bestseller, centering on a Black girl who discovers a secret Arthurian society at the University of North Carolina at Chapel Hill and finds that her own family history is entangled with the society's magical legacy. Legendborn was praised for its integration of Arthurian mythology with American racial history — particularly the history of the American South — and won numerous awards including the Coretta Scott King Author Honor. She is writing a sequel trilogy under the Legendborn Cycle series title; Bloodmarked (2022) is the second book.",
    genre: 'fantasy',
    knownFor: ['Legendborn', 'Bloodmarked'],
  },
  {
    name: 'Marie Rutkoski',
    bio: "Marie Rutkoski is an American author of YA fantasy best known for The Winner's Trilogy — The Winner's Curse (2014), The Winner's Crime (2015), and The Winner's Kiss (2016). The trilogy is set in a fantasy world where the Herrani people were enslaved by the Valorian empire, and follows Kestrel, a Valorian general's daughter, and Arin, a Herrani slave she buys at auction. The series is praised for its sophisticated portrayal of colonialism, its strategically intelligent female protagonist, and its slow-burn romance built on genuine political stakes rather than proximity. Rutkoski previously wrote the Kronos Chronicles middle-grade series.",
    genre: 'fantasy',
    knownFor: ["The Winner's Curse", "The Winner's Crime", "The Winner's Kiss"],
  },
  {
    name: 'Orson Scott Card',
    bio: "Orson Scott Card is an American author best known for Ender's Game (1985), a science fiction novel about a child genius trained at Battle School to command humanity's fleet against an alien species. The novel won both the Hugo and Nebula Awards for Best Novel — the only science fiction novel to have won both in the same year. Card continued the series with Speaker for the Dead (1986), which won both awards again, and later wrote Ender's Shadow (1999), a parallel novel that retells Ender's Game from Bean's perspective and launched a second series set in the same universe. He is also the author of the Alvin Maker fantasy series.",
    genre: 'sci-fi',
    knownFor: ["Ender's Game", "Speaker for the Dead", "Ender's Shadow"],
  },
  {
    name: 'Naomi Novik',
    bio: "Naomi Novik is an American author of fantasy best known for two series: the Temeraire alternate-history fantasy series (9 books, 2006–2016), set during the Napoleonic Wars in a world where dragons are used as air forces, and the Scholomance trilogy (A Deadly Education, The Last Graduate, The Golden Enclaves), a YA fantasy about a lethal magical school. She also wrote the standalone dark fairy tale Uprooted (2015), which won the Nebula Award for Best Novel. Novik was previously a video game programmer and co-founder of the Organization for Transformative Works, which created the Archive of Our Own (AO3) fan fiction archive.",
    genre: 'fantasy',
    knownFor: ['A Deadly Education', 'Uprooted', 'The Scholomance'],
  },
  {
    name: 'Dan Simmons',
    bio: "Dan Simmons is an American author of science fiction and horror best known for the Hyperion Cantos, a four-book science fiction series beginning with Hyperion (1989), which won the Hugo Award for Best Novel. Hyperion is structured in the mode of The Canterbury Tales, with seven pilgrims telling their stories on the way to a world where an entity of blades and cruelty has been killing people for centuries. The follow-up The Fall of Hyperion (1990) completes the story arc. Simmons has also written the horror novel The Terror (2007), about the Franklin Expedition, and other genre fiction.",
    genre: 'sci-fi',
    knownFor: ['Hyperion', 'The Fall of Hyperion', 'The Terror'],
  },
  {
    name: 'Isaac Asimov',
    bio: "Isaac Asimov (1920–1992) was an American biochemist and prolific science fiction author who wrote or edited more than 500 books. He is best known for the Foundation series — a sweeping science fiction epic about the fall of the Galactic Empire and the mathematician Hari Seldon's plan to reduce the resulting dark age using psychohistory — and for the Robot series, which introduced the Three Laws of Robotics. The original Foundation trilogy (Foundation, Foundation and Empire, Second Foundation) won a one-time Hugo Award as the Best All-Time Series in 1966. Asimov is credited, along with Arthur C. Clarke and Robert A. Heinlein, with establishing the modern form of the science fiction novel.",
    genre: 'sci-fi',
    knownFor: ['Foundation', 'Foundation and Empire', 'I, Robot'],
  },
  {
    name: 'Ursula K. Le Guin',
    bio: "Ursula K. Le Guin (1929–2018) was an American author widely considered one of the greatest science fiction and fantasy writers ever to work in the genre. Her major works include The Left Hand of Darkness (1969, Hugo and Nebula), The Dispossessed (1974, Hugo and Nebula), The Word for World is Forest (1972), and the Earthsea fantasy series. Le Guin was the first woman to win a Hugo for Best Novel (for The Left Hand of Darkness) and was later given the SFWA Grand Master Award. She is known for using speculative fiction to examine real social structures — gender, anarchism, colonialism, ecology — in ways that have influenced virtually every major SF author of the last 50 years.",
    genre: 'sci-fi',
    knownFor: ['The Left Hand of Darkness', 'The Dispossessed', 'A Wizard of Earthsea'],
  },
  {
    name: 'John Scalzi',
    bio: "John Scalzi is an American author of science fiction and former president of the Science Fiction and Fantasy Writers Association (SFWA). He is best known for the Old Man's War military SF series (2005–2015), which began with Old Man's War and ran for six novels. He also wrote the Hugo Award-winning Redshirts (2012), a satirical meta-novel about secondary characters in science fiction. Scalzi is known for his accessible prose style, dark humor, and the speed of his output — he is one of the most prolific major SF authors of his generation. His blog Whatever was one of the most widely read author blogs in the early internet era.",
    genre: 'sci-fi',
    knownFor: ["Old Man's War", 'Redshirts', 'The Kaiju Preservation Society'],
  },
  {
    name: 'Blake Crouch',
    bio: "Blake Crouch is an American author of science fiction thrillers, best known for a series of standalone novels that use a speculative scientific concept as the engine of a thriller plot: Dark Matter (2016, parallel universes), Recursion (2019, memory and time), and Upgrade (2022, genetic intelligence enhancement). Crouch previously wrote the Wayward Pines thriller trilogy, which was adapted into a Fox television series. His standalone novels are known for their accessibility — they are frequently recommended to readers who don't normally read science fiction — and for their high momentum pacing and emotional cores.",
    genre: 'sci-fi',
    knownFor: ['Dark Matter', 'Recursion', 'Upgrade'],
  },
  {
    name: 'Kerri Maniscalco',
    bio: "Kerri Maniscalco is an American author of YA historical fantasy and dark fantasy. She is best known for two series: the Stalking Jack the Ripper historical mystery series (4 books, 2016–2019), set in 1888 Victorian London and featuring a young female forensic detective, and the Kingdom of the Wicked dark fantasy trilogy (2020–2022), set in 1888 Sicily and featuring a young woman who summons a demon to investigate her twin sister's murder. Both series draw on the atmosphere and historical detail of the late Victorian period and feature slow-burn romances with morally complicated love interests. The Stalking Jack the Ripper series has sold millions of copies worldwide.",
    genre: 'fantasy',
    knownFor: ['Kingdom of the Wicked', 'Stalking Jack the Ripper'],
  },
  {
    name: 'Octavia Butler',
    bio: "Octavia Butler (1947–2006) was an American science fiction author widely regarded as one of the greatest SF writers of the 20th century and the first major African American woman in the genre. Her major works include Kindred (1979), the Parable series (Parable of the Sower, 1993; Parable of the Talents, 1998), the Patternist series, and the Bloodchild short fiction collection. She won multiple Hugo and Nebula Awards, a PEN Lifetime Achievement Award, and a MacArthur Fellowship. Butler wrote science fiction as a tool for examining real social structures — race, gender, power, biology — from angles that prose realism could not access. She died in 2006 at age 58, leaving the Parable series incomplete.",
    genre: 'sci-fi',
    knownFor: ['Kindred', 'Parable of the Sower', 'Parable of the Talents'],
  },
  {
    name: 'Emily St. John Mandel',
    bio: "Emily St. John Mandel is a Canadian-American author best known for Station Eleven (2014), a literary novel set before and after a flu pandemic kills most of the world's population. Station Eleven was a finalist for the National Book Award and the PEN/Faulkner Award, adapted into an HBO Max miniseries in 2021, and became one of the defining pandemic novels in American literature. She has since written The Glass Hotel (2020), a companion novel sharing some characters with Station Eleven, and Sea of Tranquility (2022), which connects all three novels through a time-travel mystery. Her earlier novels (Last Night in Montreal, The Singer's Gun, The Lola Quartet) are literary thrillers.",
    genre: 'fiction',
    knownFor: ['Station Eleven', 'Sea of Tranquility', 'The Glass Hotel'],
  },
  {
    name: 'Matt Haig',
    bio: "Matt Haig is a British author best known for The Midnight Library (2020), a literary novel about a woman who discovers a library between life and death where every book is a life she didn't live. The Midnight Library became one of the best-selling novels of the 2020s, selling millions of copies worldwide and being translated into over 40 languages. Haig is also the author of the memoir Reasons to Stay Alive (2015), about his experience with depression and anxiety, and several other novels including The Humans (2013) and How to Stop Time (2017). He is known for literary fiction that engages directly with mental health, often in accessible and emotionally warm registers.",
    genre: 'fiction',
    knownFor: ['The Midnight Library', 'Reasons to Stay Alive', 'The Humans'],
  },
  {
    name: 'Cormac McCarthy',
    bio: "Cormac McCarthy (1933–2023) was an American novelist widely considered one of the most significant literary voices of the 20th and 21st centuries. He is best known for The Road (2006), which won the Pulitzer Prize for Fiction in 2007, and No Country for Old Men (2005), which was adapted into the Academy Award–winning film by the Coen Brothers. His other major works include Blood Meridian (1985), often cited as one of the greatest American novels, the Border Trilogy (All the Pretty Horses, The Crossing, Cities of the Plain), and his final two novels, The Passenger and Stella Maris (both 2022). McCarthy's prose is distinguished by its spare punctuation, biblical cadences, and an unflinching engagement with violence, death, and the moral landscape of the American West and South.",
    genre: 'fiction',
    knownFor: ['The Road', 'No Country for Old Men', 'Blood Meridian'],
  },
  {
    name: 'Toni Morrison',
    bio: "Toni Morrison (1931–2019) was an American novelist and Nobel Prize laureate widely regarded as one of the greatest writers in American literary history. Her novel Beloved (1987) won the Pulitzer Prize for Fiction in 1988 and is consistently ranked among the greatest American novels. In 1993, Morrison became the first African-American woman to be awarded the Nobel Prize in Literature. Her other major works include Song of Solomon (1977, National Book Award), Sula (1973), The Bluest Eye (1970), Jazz (1992), Paradise (1997), and A Mercy (2008). Morrison taught at Princeton University for many years. Her fiction is distinguished by its lyrical prose, deep engagement with the experience of Black Americans, and its structural innovation — Morrison repeatedly invented new forms for the material her novels required.",
    genre: 'fiction',
    knownFor: ['Beloved', 'Song of Solomon', 'The Bluest Eye'],
  },
  {
    name: 'Colson Whitehead',
    bio: "Colson Whitehead is an American novelist who has won the Pulitzer Prize for Fiction twice — for The Underground Railroad (2016) and The Nickel Boys (2019) — making him only the fourth author in history to win the prize twice. The Underground Railroad, which imagines a literal subterranean railroad helping enslaved people escape the antebellum South, also won the National Book Award and was adapted into a miniseries by Barry Jenkins. Whitehead is also the author of Zone One (2011), a literary zombie novel, The Intuitionist (1999), Harlem Shuffle (2021), and Crook Manifesto (2023). He is a staff writer at The New Yorker and has been described as one of the defining American novelists of his generation.",
    genre: 'fiction',
    knownFor: ['The Underground Railroad', 'The Nickel Boys', 'Harlem Shuffle'],
  },
  {
    name: 'Fredrik Backman',
    bio: "Fredrik Backman is a Swedish author and blogger whose debut novel A Man Called Ove (2012) became an international bestseller, selling millions of copies in more than 40 countries and being adapted into both a Swedish Oscar-nominated film (2015) and an American film starring Tom Hanks (A Man Called Otto, 2022). Backman worked as a freelance journalist and blogger before turning to fiction. His subsequent novels include My Grandmother Asked Me to Tell You She's Sorry (2013), Britt-Marie Was Here (2014), Beartown (2016, his most critically serious work), Anxious People (2019), and The Winners (2022). Backman writes character-driven literary fiction about ordinary Scandinavian communities navigating grief, community, and the question of what people owe each other.",
    genre: 'fiction',
    knownFor: ['A Man Called Ove', 'Anxious People', 'Beartown'],
  },
  {
    name: 'Gail Honeyman',
    bio: "Gail Honeyman is a Scottish author whose debut novel Eleanor Oliphant Is Completely Fine (2017) was an international phenomenon, selling over 4 million copies worldwide, spending over 50 weeks on the New York Times bestseller list, and winning the British Book Award for Debut Novel of the Year. The novel follows Eleanor Oliphant, a woman with an extremely regimented life and near-total social isolation, and was widely praised for its distinctive first-person voice and its careful handling of trauma and mental health. Reese Witherspoon selected it for her book club, which significantly accelerated its reach. A film adaptation has been in development for several years. As of 2024, Honeyman has not published a second novel.",
    genre: 'fiction',
    knownFor: ['Eleanor Oliphant Is Completely Fine'],
  },
  {
    name: 'Claire North',
    bio: "Claire North is a pen name for Catherine Webb, a British author who also writes as Kate Griffin. Her debut under the Claire North name, The First Fifteen Lives of Harry August (2014), became an international bestseller and is widely considered one of the finest time-loop novels in literary science fiction. Her subsequent novels include Touch (2015), The Sudden Appearance of Hope (2016, World Fantasy Award winner), 84K (2018), The Gameshouse (2015), The Pursuit of William Abbey (2019), and Notes from the Burning Age (2021). North is known for using speculative premises as vehicles for character studies about identity, memory, and what makes a person who they are. As Kate Griffin she writes urban fantasy set in London.",
    genre: 'sci-fi',
    knownFor: ['The First Fifteen Lives of Harry August', 'Touch', 'The Sudden Appearance of Hope'],
  },
  {
    name: 'Delia Owens',
    bio: "Delia Owens is an American wildlife scientist and author whose debut novel, Where the Crawdads Sing (2018), became one of the best-selling novels of the 2010s and 2020s, selling over 15 million copies worldwide, spending years on the New York Times bestseller list, and being selected for Reese Witherspoon's book club. Before writing fiction, Owens spent decades as a wildlife researcher in Africa and co-wrote three nonfiction books about her work with her husband, Mark Owens: Cry of the Kalahari (1984), The Eye of the Elephant (1992), and Secrets of the Savanna (2006). Where the Crawdads Sing draws on her extensive experience in remote natural environments, particularly coastal marshes. It was adapted into a film in 2022 with Daisy Edgar-Jones. As of 2024 she has not published a second novel.",
    genre: 'fiction',
    knownFor: ['Where the Crawdads Sing'],
  },
  {
    name: 'Hanya Yanagihara',
    bio: "Hanya Yanagihara is an American novelist and the editor in chief of T: The New York Times Style Magazine. Her second novel, A Little Life (2015), was a finalist for the Man Booker Prize, a finalist for the National Book Award, and one of the most discussed literary novels of the 2010s. It is known for its extreme emotional intensity and graphic depictions of childhood sexual abuse and self-harm. Her first novel, The People in the Trees (2013), was a quieter critical success; her third, To Paradise (2022), spans three centuries and three versions of America. Yanagihara's fiction is distinguished by its commitment to portraying suffering without redemptive framing — she has said she believes fiction is obligated to show what certain kinds of damage actually look like.",
    genre: 'fiction',
    knownFor: ['A Little Life', 'The People in the Trees', 'To Paradise'],
  },
  {
    name: 'Donna Tartt',
    bio: "Donna Tartt is an American novelist who has published three novels over three decades, each of which has been a major literary event: The Secret History (1992), The Little Friend (2002), and The Goldfinch (2013), which won the Pulitzer Prize for Fiction. The Secret History, her debut, defined the dark academia aesthetic and the reverse-mystery structure in literary fiction, and remains one of the most-sold literary debut novels in American publishing history. Tartt is known for her long production schedule — roughly a decade between each novel — and her exacting attention to prose. The Goldfinch was adapted into a film in 2019.",
    genre: 'fiction',
    knownFor: ['The Secret History', 'The Goldfinch', 'The Little Friend'],
  },
  {
    name: 'Celeste Ng',
    bio: "Celeste Ng is a Chinese-American novelist born in Pittsburgh and raised in Shaker Heights, Ohio — the community that provides the setting for her second novel, Little Fires Everywhere. Her debut novel, Everything I Never Told You (2014), won the Amazon Book of the Year Award and the Alex Award. Little Fires Everywhere (2017) was an instant New York Times bestseller, was selected for Reese Witherspoon's book club, and was adapted into a Hulu miniseries (2020) starring Witherspoon and Kerry Washington. Her third novel, Our Missing Hearts (2022), is a speculative fiction novel about a near-future America where a law banning cultural influence has separated families. Ng is a frequent speaker and essayist on race, identity, and American literature.",
    genre: 'fiction',
    knownFor: ['Little Fires Everywhere', 'Everything I Never Told You', 'Our Missing Hearts'],
  },
  {
    name: 'Liane Moriarty',
    bio: "Liane Moriarty is an Australian novelist who became an international phenomenon with Big Little Lies (2014), which sold millions of copies worldwide and was adapted into an Emmy-winning HBO miniseries (2017) starring Reese Witherspoon and Nicole Kidman. Her subsequent novel, Nine Perfect Strangers (2018), was also adapted into a Hulu miniseries (2021) with Nicole Kidman. Moriarty is known for her dark domestic comedies — literary thrillers that use sharp ensemble characterization and a multi-perspective structure to examine the secrets that upscale communities keep. Her other novels include The Husband's Secret (2013), What Alice Forgot (2009), Truly Madly Guilty (2016), and Apples Never Fall (2021).",
    genre: 'fiction',
    knownFor: ['Big Little Lies', 'Nine Perfect Strangers', 'The Husband\'s Secret'],
  },
  {
    name: 'Joe Haldeman',
    bio: "Joe Haldeman is an American science fiction author and Vietnam War veteran best known for The Forever War (1974), a Hugo and Nebula Award–winning novel about soldiers fighting an interstellar war while relativistic travel ages Earth decades between each deployment. Haldeman has explicitly described The Forever War as his response to his experience in Vietnam and to Robert Heinlein's Starship Troopers. He has taught creative writing at MIT for many years. His other major works include Forever Peace (1997, Hugo Award), Camouflage (2004, Nebula Award), and Old Twentieth (2005). He is generally considered one of the defining voices of the 'war is alienating' tradition in military science fiction.",
    genre: 'sci-fi',
    knownFor: ['The Forever War', 'Forever Peace', 'Camouflage'],
  },
  {
    name: 'Sally Rooney',
    bio: "Sally Rooney is an Irish novelist born in County Mayo in 1991 who became one of the defining literary voices of her generation with her debut novel Conversations with Friends (2017) and her second novel Normal People (2018), which won the Costa Novel Award and was adapted into a widely acclaimed BBC Three/Hulu series (2020) starring Daisy Edgar-Jones and Paul Mescal. Her third novel, Beautiful World, Where Are You (2021), debuted at number one in multiple countries. Rooney is known for her distinctive style — no quotation marks for dialogue, rigorous interiority, and an unwavering focus on power dynamics, class, and the specific difficulty of intimacy in contemporary life. She studied English literature at Trinity College Dublin, where Normal People and Conversations with Friends are partly set.",
    genre: 'romance',
    knownFor: ['Normal People', 'Conversations with Friends', 'Beautiful World Where Are You'],
  },
  {
    name: 'Brit Bennett',
    bio: "Brit Bennett is an American novelist whose debut novel The Mothers (2016) was a New York Times bestseller and a finalist for several literary awards. Her second novel, The Vanishing Half (2020), was a New York Times number one bestseller, remained on the bestseller list for over a year, and was named the Best Book of 2020 by numerous outlets including Time magazine. Bennett studied English at Stanford University and earned her MFA from the University of Michigan. Her fiction focuses on African-American communities and the ways race, identity, and family legacy shape individual lives across generations. She has written essays for The New Yorker, The New York Times, and other publications.",
    genre: 'fiction',
    knownFor: ['The Vanishing Half', 'The Mothers'],
  },
  {
    name: 'M.L. Rio',
    bio: "M.L. Rio is the pen name of an American author who published her debut novel If We Were Villains in 2017. The novel, about seven Shakespeare students at a performing arts conservatory, became a cult classic of the dark academia genre and a perennial bestseller. Rio studied English at William & Mary and earned her PhD in Shakespeare from King's College London. If We Were Villains was originally published by Flatiron Books and remained in print through consistent reader recommendations and TikTok (BookTok) promotion years after publication. As of 2024 she has not published a second novel. She has cited Donna Tartt's The Secret History and Shakespeare himself as her primary influences.",
    genre: 'fiction',
    knownFor: ['If We Were Villains'],
  },
  {
    name: 'Yaa Gyasi',
    bio: "Yaa Gyasi is a Ghanaian-American novelist born in Mampong, Ghana in 1989 and raised in Huntsville, Alabama. Her debut novel Homegoing (2016), written while she was at the Iowa Writers' Workshop, won the National Book Critics Circle's John Leonard Award for best debut, the PEN/Hemingway Award, the Vilcek Prize for Creative Promise in Literature, and several other honors; it was also a finalist for the National Book Award and the PEN/Faulkner Award. Her second novel, Transcendent Kingdom (2020), was a finalist for the Booker Prize and has been translated into over 30 languages. Gyasi is known for her structural ambition — Homegoing spans 300 years and 14 chapters — and her interest in what history does to individual lives across generations.",
    genre: 'fiction',
    knownFor: ['Homegoing', 'Transcendent Kingdom'],
  },
  {
    name: 'Min Jin Lee',
    bio: "Min Jin Lee is a Korean-American novelist born in Seoul, South Korea in 1968 and raised in New York City. She studied history at Yale and law at Georgetown before turning to fiction. Her debut novel, Free Food for Millionaires (2007), was a New York Times Notable Book. Her second novel, Pachinko (2017), spent years in research and drafting, was a finalist for the National Book Award, and was selected as one of the best novels of 2017 by more than 100 publications. Pachinko was adapted into an Apple TV+ series premiering in 2022. Lee is known for her detailed research into the lives of communities she portrays — particularly the Zainichi Korean community in Japan — and for her belief that fiction can illuminate what history alone cannot show.",
    genre: 'fiction',
    knownFor: ['Pachinko', 'Free Food for Millionaires'],
  },
  {
    name: 'Anthony Doerr',
    bio: "Anthony Doerr is an American novelist and short story writer from Cleveland, Ohio who won the Pulitzer Prize for Fiction in 2015 for All the Light We Cannot See (2014), which had taken him ten years to write. The novel also won the Carnegie Medal for Excellence in Fiction. His earlier work includes the short story collections The Shell Collector (2002) and Memory Wall (2010), both of which won multiple awards, and a novel, About Grace (2004). His third novel, Cloud Cuckoo Land (2021), weaves together stories across multiple centuries and won the Carnegie Medal. Doerr is known for his lyrical prose, his meticulous research, and his interest in science, light, and the physical world as subjects for literary fiction.",
    genre: 'fiction',
    knownFor: ['All the Light We Cannot See', 'Cloud Cuckoo Land', 'The Shell Collector'],
  },
  {
    name: 'Amor Towles',
    bio: "Amor Towles is an American novelist who spent many years as an investment professional before publishing his debut novel, Rules of Civility (2011). His second novel, A Gentleman in Moscow (2016), became one of the best-selling literary novels of the decade, spending years on bestseller lists around the world and selling over 3 million copies in the US alone. It was adapted into a Paramount+ / Sky Atlantic miniseries in 2024, starring Ewan McGregor. His third novel, The Lincoln Highway (2021), debuted at number one on the New York Times bestseller list. Towles is known for his elegant prose, his wit, his period detail, and his warmly humanist philosophy — a rare literary novelist whose work is simultaneously critically respected and enormously popular.",
    genre: 'fiction',
    knownFor: ['A Gentleman in Moscow', 'Rules of Civility', 'The Lincoln Highway'],
  },
  {
    name: 'Emma Donoghue',
    bio: "Emma Donoghue is an Irish-Canadian novelist, playwright, and literary historian born in Dublin in 1969. She is best known for Room (2010), which was shortlisted for the Man Booker Prize and the Orange Prize and was adapted into an Academy Award–winning film (2015) with Brie Larson and Jacob Tremblay. Room's premise — narrated entirely by a five-year-old who has spent his whole life in a single room — was inspired by the Josef Fritzl case and other captivity cases. Donoghue has also written historical fiction (Slammerkin, The Wonder, Akin, Haven), a study of lesbian novels (Passions Between Women), and several plays. She holds a PhD in English from Cambridge and has written extensively on Jane Austen.",
    genre: 'fiction',
    knownFor: ['Room', 'The Wonder', 'Akin'],
  },
  {
    name: 'Kristin Hannah',
    bio: "Kristin Hannah is an American novelist who has published more than 25 novels since 1991 and became one of the most commercially successful literary fiction authors in the world with The Nightingale (2015), which sold over 15 million copies worldwide. Originally a lawyer, she turned to writing full-time in the 1990s. Her other best-known novels include Firefly Lane (2008), The Great Alone (2018), and The Women (2024). Hannah is known for her emotionally intense, research-intensive novels that center women's experiences across historical and contemporary settings. The Nightingale is often cited as the novel that established her internationally; it has been one of the most consistently recommended novels on BookTok and in book clubs for a decade.",
    genre: 'fiction',
    knownFor: ['The Nightingale', 'The Great Alone', 'Firefly Lane'],
  },
  {
    name: 'Gillian Flynn',
    bio: "Gillian Flynn is an American novelist and screenwriter who spent many years as a TV critic for Entertainment Weekly before publishing her debut novel Sharp Objects (2006). Her third novel, Gone Girl (2012), became a global publishing phenomenon, selling over 20 million copies, spending years on bestseller lists, and being adapted into a David Fincher film (2014) with a screenplay Flynn wrote herself. She is known for creating female characters who are genuinely villainous, morally complicated, and psychologically extreme in ways that challenge genre conventions. Her work is credited with establishing the 'domestic thriller' and 'unreliable female narrator' as dominant forces in contemporary popular fiction. She has also written for television, including the miniseries Utopia (2020).",
    genre: 'fiction',
    knownFor: ['Gone Girl', 'Sharp Objects', 'Dark Places'],
  },
  {
    name: 'Paula Hawkins',
    bio: "Paula Hawkins is a British novelist and former financial journalist who became one of the best-selling thriller authors in the world with The Girl on the Train (2015), which sold over 23 million copies worldwide, spent 20 weeks at number one in the United States, and was adapted into a film (2016) starring Emily Blunt. Hawkins is known for her multiple unreliable female narrator structure and her interest in the domestic spaces where women's lives are defined and controlled. Her subsequent novels, Into the Water (2017) and A Slow Fire Burning (2021), both debuted at number one in the UK and the US. She is frequently credited, alongside Gillian Flynn, with establishing the domestic psychological thriller as one of the defining popular genres of the 2010s.",
    genre: 'fiction',
    knownFor: ['The Girl on the Train', 'Into the Water', 'A Slow Fire Burning'],
  },
  {
    name: 'Douglas Stuart',
    bio: "Douglas Stuart is a Scottish-American novelist and fashion designer born in Glasgow in 1976. He was raised in working-class Glasgow by his mother, who died of alcoholism when he was 16 — the experience that forms the basis of his debut novel, Shuggie Bain (2020). Shuggie Bain was rejected by more than 30 publishers before being accepted; it won the Man Booker Prize in 2020 and the National Book Critics Circle's John Leonard Award. Stuart worked for many years as a designer for Calvin Klein and Ralph Lauren before writing fiction. His second novel, Young Mungo (2022), was also a bestseller and dealt with his experience of being gay in working-class Glasgow. He has been compared to James Baldwin and Roddy Doyle for his ability to render working-class life with literary precision.",
    genre: 'fiction',
    knownFor: ['Shuggie Bain', 'Young Mungo'],
  },
  {
    name: 'Alex Michaelides',
    bio: "Alex Michaelides is a British-Cypriot author and screenwriter born in Cyprus. He studied English literature at Cambridge and earned a master's degree in screenwriting from the American Film Institute in Los Angeles. After years of working in film and television, he wrote The Silent Patient (2019) — a psychological thriller that debuted at number one on the New York Times bestseller list and remained on it for over a year. The Silent Patient became an international bestseller, was translated into more than 50 languages, and turned Michaelides into one of the most successful debut thriller writers of the decade. It was followed by The Maidens (2021) and The Life We Left Behind (2024). Michaelides's work draws on Greek tragedy, mythology, and classical literature as structural frameworks for psychological suspense.",
    genre: 'fiction',
    knownFor: ['The Silent Patient', 'The Maidens', 'The Life We Left Behind'],
  },
  {
    name: "Maggie O'Farrell",
    bio: "Maggie O'Farrell is a British-Irish novelist born in Northern Ireland in 1972. She grew up in Wales and Scotland after a childhood illness left her temporarily paralyzed; she has written about surviving multiple near-death experiences in her memoir I Am, I Am, I Am (2017). O'Farrell is the author of nine novels, including After You'd Gone (2000), The Hand That First Held Mine (Baileys Women's Prize for Fiction winner, 2010), Instructions for a Heatwave (2013), and Hamnet (2020), which won the Women's Prize for Fiction and was one of the most celebrated literary novels of its decade. Hamnet imagines the life of Agnes, wife of the man who would become William Shakespeare, and the death of their son from plague in 1596. Her 2022 novel The Marriage Portrait returned to historical fiction, following Lucrezia de' Medici in Renaissance Florence. O'Farrell's fiction is characterized by lyrical prose, psychological depth, and an interest in women who have been made invisible by the famous men around them.",
    genre: 'fiction',
    knownFor: ['Hamnet', 'I Am, I Am, I Am', 'The Hand That First Held Mine', 'The Marriage Portrait'],
  },
  {
    name: 'Ottessa Moshfegh',
    bio: "Ottessa Moshfegh is an American novelist and short story writer born in Boston in 1981 to Croatian and Iranian parents. She studied at Barnard College and received her MFA from Brown University. Her debut novel Eileen (2015) was shortlisted for the Man Booker Prize and won the PEN/Hemingway Award; it established her reputation for writing with unflinching, darkly comic interiority from the perspective of deeply alienated, self-destructive women. Her short story collection Homesick for Another World (2017) confirmed her as one of the most formally inventive short fiction writers of her generation. My Year of Rest and Relaxation (2018) became her most widely read novel — a nihilistic, deadpan portrait of a beautiful, privileged young woman who attempts to sleep through a year of her life on an escalating regimen of psychiatric drugs. Moshfegh has also written Death in Her Hands (2020) and Lapvona (2022), a medieval fable that represents her most extreme formal departure. She is known for combining literary ambition with an interest in grotesque bodies, moral vacancy, and the gap between how lives look from outside and how they feel from inside.",
    genre: 'fiction',
    knownFor: ['My Year of Rest and Relaxation', 'Eileen', 'Homesick for Another World', 'Lapvona'],
  },
  {
    name: 'Markus Zusak',
    bio: "Markus Zusak is an Australian novelist born in Sydney in 1975 to German and Austrian parents who immigrated to Australia. He published four young adult novels before The Book Thief (2005) — The Underdog (1999), Fighting Ruben Wolfe (2000), When Dogs Cry (2001), and The Messenger (2002, called I Am the Messenger in the United States). The Book Thief was rejected by multiple publishers before being published; it was narrated by Death and told the story of a German girl during World War II. The novel became an international phenomenon — selling over 16 million copies, appearing on the New York Times bestseller list for more than ten years, and being adapted into a film in 2013. Zusak waited thirteen years to publish his follow-up, Bridge of Clay (2018), a family saga set in contemporary Australia. His work is characterized by unusual narrators, experimental structure, and a willingness to announce tragedy before it occurs as a way of shifting the reader's attention from what happens to how it happens.",
    genre: 'fiction',
    knownFor: ['The Book Thief', 'Bridge of Clay', 'The Messenger'],
  },
  {
    name: 'B.A. Paris',
    bio: "B.A. Paris is the pen name of Barbara Marrow, a British-French author who spent much of her adult life in France before returning to the UK. She worked in finance and later as a teacher before turning to writing thrillers. Her debut novel Behind Closed Doors (2016) was self-published before being picked up by St. Martin's Press; it became an international bestseller and established her as a leading figure in the domestic psychological thriller genre that emerged in the wake of Gone Girl. Paris has since published The Breakdown (2017), Bring Me Back (2018), The Dilemma (2019), The Therapist (2021), The Prisoner (2023), and The Skylight (2024). Her novels typically feature coercive control, manipulative marriages, and the gap between how lives look to outsiders and what they conceal within.",
    genre: 'fiction',
    knownFor: ['Behind Closed Doors', 'The Breakdown', 'Bring Me Back', 'The Therapist'],
  },
  {
    name: 'A.J. Finn',
    bio: "A.J. Finn is the pen name of Dan Mallory, an American author and former book editor. Mallory worked as an executive editor at William Morrow, an imprint of HarperCollins, before publishing The Woman in the Window (2018) under the name A.J. Finn. The novel was a deliberate homage to Alfred Hitchcock's Rear Window and sold millions of copies, debuting at number one on the New York Times bestseller list. In 2019, a New Yorker profile by Ian Parker revealed that Mallory had fabricated significant details of his personal history — including claims about his mother's cancer death and his own brain tumor — to people in his professional and personal life. The revelations generated significant public discussion about the novel and its author. The Woman in the Window was adapted into a Netflix film in 2021 starring Amy Adams. As of 2025, Mallory has not published a second novel.",
    genre: 'fiction',
    knownFor: ['The Woman in the Window'],
  },
  {
    name: 'Tayari Jones',
    bio: "Tayari Jones is an American novelist born in Atlanta, Georgia in 1970. She is the author of five novels: Leaving Atlanta (2002), The Untelling (2005), Silver Sparrow (2011), An American Marriage (2018), and Ghost (2024). Leaving Atlanta was a semi-autobiographical novel about the Atlanta child murders of 1979–1981, which happened during Jones's childhood. An American Marriage, her fourth novel, won the Women's Prize for Fiction in 2019 and was an Oprah's Book Club selection; it follows a young professional Black couple in Atlanta after the husband is wrongfully convicted of rape. Jones has said she was moved to write the novel by a conversation with a man who had been wrongfully imprisoned, and the way both he and his wife had valid but irreconcilable perspectives on what the imprisonment had meant for their relationship. An American Marriage established Jones as one of the most important voices in contemporary American literary fiction. She is a professor at Emory University.",
    genre: 'fiction',
    knownFor: ['An American Marriage', 'Silver Sparrow', 'Leaving Atlanta'],
  },
  {
    name: 'Jesmyn Ward',
    bio: "Jesmyn Ward is an American novelist born in DeLisle, Mississippi in 1977. She is the only woman and the first Black writer to have won the National Book Award for Fiction twice — for Salvage the Bones (2011) and Sing, Unburied, Sing (2017). Ward grew up in poverty in rural Mississippi and lost five young Black men in her community to drugs, accidents, and poverty in four years — an experience she documented in her memoir Men We Reaped (2013). Her fiction is set in and around DeLisle (fictionalized as Bois Sauvage) and is consistently interested in what poverty, racism, and the American criminal justice system do to Black families in the rural South. Her novels include Where the Line Bleeds (2008), Salvage the Bones, Sing, Unburied, Sing, and Let Us Descend (2023). Ward has been compared to Toni Morrison for her use of lyrical prose and supernatural elements to carry the weight of historical trauma. She is a professor at Tulane University.",
    genre: 'fiction',
    knownFor: ['Sing, Unburied, Sing', 'Salvage the Bones', 'Men We Reaped', 'Let Us Descend'],
  },
  {
    name: 'Amy Tan',
    bio: "Amy Tan is an American novelist born in Oakland, California in 1952, to Chinese immigrant parents from Shanghai. She graduated from San Jose State University and worked as a language development specialist and then a freelance business writer before turning to fiction. Her debut novel The Joy Luck Club (1989) — structured as sixteen interlinked stories told by four Chinese immigrant mothers and their American-born daughters — was an immediate bestseller and was a finalist for the National Book Award and the National Book Critics Circle Award. The Joy Luck Club was adapted into a widely seen film in 1993 directed by Wayne Wang. Tan followed it with The Kitchen God's Wife (1991), The Hundred Secret Senses (1995), The Bonesetter's Daughter (2001), Saving Fish from Drowning (2005), and The Valley of Amazement (2013). She has also written a memoir, The Opposite of Fate (2003). Tan is celebrated for her exploration of the gap between Chinese immigrant mothers and their American-born daughters — the different languages, memories, and understandings of what family and sacrifice mean across generations.",
    genre: 'fiction',
    knownFor: ['The Joy Luck Club', 'The Kitchen God\'s Wife', 'The Bonesetter\'s Daughter'],
  },
  {
    name: 'Isabel Allende',
    bio: "Isabel Allende is a Chilean-American novelist born in Lima, Peru in 1942, the daughter of a Chilean diplomat and cousin to Salvador Allende, the Chilean president who was overthrown and killed in the 1973 coup. Allende worked as a journalist in Chile before the coup forced her into exile; she moved to Venezuela and later to the United States, where she has lived since the 1980s. She wrote The House of the Spirits (1982) as a letter to her dying grandfather — a novel about three generations of the Trueba family in an unnamed South American country through a military coup that closely mirrors Chile's. The House of the Spirits became an international bestseller and a foundational text of Latin American magical realism. Allende has since published over 25 books, including Of Love and Shadows (1984), Eva Luna (1987), The Infinite Plan (1991), Paula (1994, a memoir about her daughter's death), Portrait in Sepia (2000), Maya's Notebook (2011), In the Midst of Winter (2017), and A Long Petal of the Sea (2019). She is one of the most widely read Spanish-language authors in the world and has sold over 77 million books.",
    genre: 'fiction',
    knownFor: ['The House of the Spirits', 'A Long Petal of the Sea', 'Eva Luna', 'Paula'],
  },
  {
    name: 'Tommy Orange',
    bio: "Tommy Orange is a Native American novelist of Cheyenne and Arapaho descent, born and raised in Oakland, California. He attended the Institute of American Indian Arts in Santa Fe and received his MFA from there. His debut novel There There (2018) — about twelve Native American characters converging on an Oakland powwow — was a Pulitzer Prize finalist, won the PEN/Hemingway Award, the Center for Fiction First Novel Prize, and the American Book Award, and was widely described as the most important debut novel about Native American experience in decades. Orange has said he wanted to write a novel about urban Native American experience — the majority of Native Americans live in cities, not on reservations — to counter the cultural assumption that Native American life means reservation life. His second novel, Wandering Stars (2024), continues the story of There There's survivors. Orange teaches at the Institute of American Indian Arts.",
    genre: 'fiction',
    knownFor: ['There There', 'Wandering Stars'],
  },
];

function normalize(s: string) {
  return s.toLowerCase().replace(/\.\s+/g, '.').replace(/\s+/g, ' ').trim();
}

export function getAuthorBio(name: string): AuthorBio | undefined {
  const n = normalize(name);
  return AUTHOR_BIOS.find((a) => normalize(a.name) === n);
}
