export interface RecommendedBook {
  title: string;
  author: string;
  why: string;
  genre: string;
}

export interface BooksLikeEntry {
  slug: string;
  sourceTitle: string;
  sourceShortName?: string;
  tagline: string;
  description: string;
  recommendations: RecommendedBook[];
  keywords: string[];
}

function amazonUrl(title: string, author: string): string {
  const tag = 'bookreleaseradar-20';
  const q = encodeURIComponent(`${title} ${author}`);
  return `https://www.amazon.com/s?k=${q}&i=stripbooks&tag=${tag}`;
}

export function getRecommendationAmazonUrl(book: RecommendedBook): string {
  return amazonUrl(book.title, book.author);
}

export const RECOMMENDATIONS: BooksLikeEntry[] = [
  {
    slug: 'acotar',
    sourceTitle: 'A Court of Thorns and Roses',
    sourceShortName: 'ACOTAR',
    tagline: 'Fae courts, forbidden love, and high-stakes magic',
    description:
      "If you loved ACOTAR's blend of fae mythology, enemies-to-lovers romance, and immersive world-building, these books deliver the same addictive mix of magic, tension, and swoon-worthy romance.",
    keywords: [
      'books like ACOTAR',
      'books similar to A Court of Thorns and Roses',
      'if you liked ACOTAR',
      'romantasy books like ACOTAR',
      'fae romance books',
      'books like Sarah J Maas',
    ],
    recommendations: [
      { title: 'Fourth Wing', author: 'Rebecca Yarros', why: 'Dragon riders, enemies-to-lovers romance, and the same intense fandom. The most direct heir to ACOTAR\'s romantasy throne.', genre: 'fantasy' },
      { title: 'From Blood and Ash', author: 'Jennifer L. Armentrout', why: 'Forbidden love, secret identities, and a hidden magical world. Fans of ACOTAR consistently rate this as their top recommendation.', genre: 'fantasy' },
      { title: 'The Cruel Prince', author: 'Holly Black', why: 'Mortal girl in a ruthless fae court — the original inspiration often cited alongside ACOTAR. Sharp prose, complex power dynamics.', genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: 'Roman Empire–inspired world, forbidden love across class lines, and the kind of slow burn that readers can\'t put down.', genre: 'fantasy' },
      { title: 'Caraval', author: 'Stephanie Garber', why: 'Atmospheric, lush, and mysterious — a magical competition with romance and twists. Perfect for readers who love ACOTAR\'s sense of wonder.', genre: 'fantasy' },
      { title: 'Kingdom of the Wicked', author: 'Kerri Maniscalco', why: 'Historical Sicily meets demonic mythology and slow-burn romance. Dark, atmospheric, and addictive — a natural next read after ACOTAR.', genre: 'fantasy' },
      { title: 'The Bridge Kingdom', author: 'Danielle L. Jensen', why: 'Political intrigue, enemies who become lovers, and a morally gray love interest. Fans of Rhysand will love this.', genre: 'fantasy' },
      { title: 'A Touch of Darkness', author: 'Scarlett St. Clair', why: 'Hades and Persephone mythology retelling with dark romance and forbidden attraction — very similar energy to ACOTAR\'s Feyre and Tamlin arc.', genre: 'fantasy' },
    ],
  },
  {
    slug: 'fourth-wing',
    sourceTitle: 'Fourth Wing',
    sourceShortName: 'Empyrean',
    tagline: 'Dragon riders, enemies-to-lovers, and high-stakes war',
    description:
      "Fourth Wing captured the world with its dragon-riding academy, brooding love interest, and intense enemies-to-lovers arc. Here are the best books to read when you've finished the Empyrean series.",
    keywords: [
      'books like Fourth Wing',
      'books similar to Fourth Wing',
      'if you liked Fourth Wing',
      'romantasy books like Fourth Wing',
      'dragon books like Fourth Wing',
      'books like Rebecca Yarros',
    ],
    recommendations: [
      { title: 'A Court of Thorns and Roses', author: 'Sarah J. Maas', why: 'The reigning queen of romantasy. ACOTAR shares Fourth Wing\'s enemies-to-lovers intensity, morally gray love interest, and addictive pacing.', genre: 'fantasy' },
      { title: 'From Blood and Ash', author: 'Jennifer L. Armentrout', why: 'The most popular recommendation for Fourth Wing fans — forbidden love, hidden worlds, and that same "I couldn\'t put it down" energy.', genre: 'fantasy' },
      { title: 'The Cruel Prince', author: 'Holly Black', why: 'A mortal girl navigating a dangerous world of powerful, ruthless men. The dynamic between Jude and Cardan mirrors Violet and Xaden perfectly.', genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: 'Military academy setting, oppressive power structures, and a slow-burn romance across class divides. Tonally closest to Fourth Wing\'s academy arc.', genre: 'fantasy' },
      { title: 'Lightlark', author: 'Alex Aster', why: 'An island where six rulers compete, secrets, and forbidden attractions. Great for readers who loved Fourth Wing\'s layered mystery.', genre: 'fantasy' },
      { title: 'The Bridge Kingdom', author: 'Danielle L. Jensen', why: 'Enemies-to-lovers with spectacular world-building and a brooding love interest who rivals Xaden for intensity.', genre: 'fantasy' },
      { title: 'Serpent & Dove', author: 'Shelby Mahurin', why: 'Witch and witch hunter forced together, forbidden attraction, and sharp banter. An extremely popular pick for Fourth Wing fans.', genre: 'fantasy' },
      { title: 'The Poppy War', author: 'R.F. Kuang', why: 'Military academy, gifted protagonist finding hidden power, and brutal war. Darker than Fourth Wing but equally gripping for fans of the academy setting.', genre: 'fantasy' },
    ],
  },
  {
    slug: 'colleen-hoover',
    sourceTitle: 'Colleen Hoover',
    sourceShortName: 'CoHo',
    tagline: 'Emotional romance that hits different',
    description:
      "Colleen Hoover built her following on emotionally raw, character-driven romance with unexpected twists. These authors deliver the same gut-punch emotional depth and compelling love stories that CoHo fans crave.",
    keywords: [
      'books like Colleen Hoover',
      'authors like Colleen Hoover',
      'if you liked Colleen Hoover',
      'romance books like CoHo',
      'new adult romance like Colleen Hoover',
      'emotional romance books',
    ],
    recommendations: [
      { title: 'Beach Read', author: 'Emily Henry', why: "Emily Henry is the most recommended CoHo alternative — smart, emotionally resonant romance with genuinely funny banter. Beach Read is the perfect entry point.", genre: 'romance' },
      { title: 'People We Meet on Vacation', author: 'Emily Henry', why: "Friends-to-lovers across years of missed chances. If you loved the longing in It Ends with Us, this will wreck you in the best way.", genre: 'romance' },
      { title: 'The Love Hypothesis', author: 'Ali Hazelwood', why: "Fake dating in academia with a nerdy heroine and a grumpy love interest. Lighter than CoHo but with the same addictive \"one more chapter\" pull.", genre: 'romance' },
      { title: 'The Spanish Love Deception', author: 'Elena Armas', why: "Enemies-to-lovers, fake dating, and will-they-won't-they tension done brilliantly. A massive BookTok hit for CoHo fans.", genre: 'romance' },
      { title: 'Reminders of Him', author: 'Colleen Hoover', why: "Already a CoHo reader? Reminders of Him is the most emotionally complex of her recent books — grieving mother, impossible love story, devastating and beautiful.", genre: 'romance' },
      { title: 'Twisted Love', author: 'Ana Huang', why: "Overprotective, brooding love interest with a dark past — the grumpy-sunshine dynamic CoHo fans adore, turned up to eleven.", genre: 'romance' },
      { title: 'The Simple Wild', author: 'K.A. Tucker', why: "Alaska setting, emotionally unavailable hero, and a heroine learning what really matters. Perfect for fans of CoHo\'s sweeping emotional arcs.", genre: 'romance' },
      { title: 'It Starts with Us', author: 'Colleen Hoover', why: "The long-awaited sequel to It Ends with Us — essential reading for any CoHo fan who needs to see Lily\'s story continue.", genre: 'romance' },
    ],
  },
  {
    slug: 'a-song-of-ice-and-fire',
    sourceTitle: 'A Song of Ice and Fire',
    sourceShortName: 'GoT',
    tagline: 'Dark politics, moral ambiguity, and epic world-building',
    description:
      "A Song of Ice and Fire redefined epic fantasy with its morally gray characters, political intrigue, and refusal to play by genre rules. These books deliver the same complexity while you wait for The Winds of Winter.",
    keywords: [
      'books like Game of Thrones',
      'books like A Song of Ice and Fire',
      'books like GoT',
      'epic fantasy like George R.R. Martin',
      'dark fantasy political intrigue',
      'books to read while waiting for Winds of Winter',
    ],
    recommendations: [
      { title: 'The Blade Itself', author: 'Joe Abercrombie', why: "The closest thing to GRRM in the genre — brutal, funny, and morally complex. Abercrombie's First Law trilogy subverts fantasy tropes as ruthlessly as Martin does.", genre: 'fantasy' },
      { title: 'Prince of Thorns', author: 'Mark Lawrence', why: "Grimdark fantasy with a young anti-hero, political maneuvering, and a post-apocalyptic medieval world. Dark, brilliant, and relentless.", genre: 'fantasy' },
      { title: 'The Way of Kings', author: 'Brandon Sanderson', why: "Epic in scope with equally intricate world-building. Less grimdark but similarly massive in scale — perfect for ASOIAF fans who want the size without the despair.", genre: 'fantasy' },
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "Beautifully written, complex protagonist, and a richly detailed world. Fans of Martin\'s prose style often cite Rothfuss as the closest literary equivalent.", genre: 'fantasy' },
      { title: 'The Lions of Al-Rassan', author: 'Guy Gavriel Kay', why: "Historical fantasy with political intrigue, cultural conflict, and bittersweet romance. Kay is GRRM\'s most cited literary influence.", genre: 'fantasy' },
      { title: 'The Lies of Locke Lamora', author: 'Scott Lynch', why: "Heist fantasy with a sprawling criminal underworld, complex con artists, and the kind of witty, violent plotting that GRRM fans love.", genre: 'fantasy' },
      { title: 'Blood Song', author: 'Anthony Ryan', why: "Military fantasy with a complex protagonist, a fascinating order system, and secrets that unravel over time. Huge ASOIAF crossover fandom.", genre: 'fantasy' },
      { title: 'Fire & Blood', author: 'George R.R. Martin', why: "While you wait for Winds of Winter — dive into the Targaryen history that inspired House of the Dragon. Same universe, equally rich.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'stormlight-archive',
    sourceTitle: 'The Stormlight Archive',
    tagline: 'Epic world-building, magic systems, and sweeping scope',
    description:
      "The Stormlight Archive sets the bar for modern epic fantasy with its depth, complexity, and emotional impact. These books match that ambition — massive worlds, intricate magic, and character arcs that span thousands of pages.",
    keywords: [
      'books like Stormlight Archive',
      'books like Brandon Sanderson',
      'epic fantasy like Stormlight',
      'books like Way of Kings',
      'books for Stormlight Archive fans',
    ],
    recommendations: [
      { title: 'Mistborn: The Final Empire', author: 'Brandon Sanderson', why: "The obvious starting point — Sanderson's other beloved Cosmere series shares the same meticulous magic systems and emotional payoffs.", genre: 'fantasy' },
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "Arguably the only other modern fantasy with comparable prose quality and world-building ambition. Essential reading for Stormlight fans.", genre: 'fantasy' },
      { title: 'The Priory of the Orange Tree', author: 'Samantha Shannon', why: "One-volume epic with dragon riders, complex female protagonists, and three distinct continents of world-building. Beloved by Sanderson fans.", genre: 'fantasy' },
      { title: 'The Eye of the World', author: 'Robert Jordan', why: "Brandon Sanderson completed the Wheel of Time — the series that most influenced him. If you love Stormlight, start here.", genre: 'fantasy' },
      { title: 'A Game of Thrones', author: 'George R.R. Martin', why: "Different tone (darker, more political) but equally epic in scope. The only series that competes with Stormlight for pure scale.", genre: 'fantasy' },
      { title: 'The Blade Itself', author: 'Joe Abercrombie', why: "Masterful character work and subverted genre expectations. Stormlight fans who want something shorter and grimmer love Abercrombie.", genre: 'fantasy' },
      { title: 'The Black Prism', author: 'Brent Weeks', why: "The Lightbringer series features a magic system as inventive as Allomancy — color-based magic with political intrigue and complex morality.", genre: 'fantasy' },
      { title: 'The Poppy War', author: 'R.F. Kuang', why: "Grimdark, brilliant, and devastating — Chinese history-inspired fantasy with the same willingness to put characters through hell that Sanderson embraces.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'mistborn',
    sourceTitle: 'Mistborn',
    sourceShortName: 'Mistborn',
    tagline: 'Heist fantasy, hard magic, and underdog heroes',
    description:
      "Mistborn hooked readers with its revolutionary hard magic system, a band of scrappy thieves taking on an immortal tyrant, and emotional sucker punches. These books share the same addictive blend of clever systems and beloved characters.",
    keywords: [
      'books like Mistborn',
      'books similar to Mistborn',
      'if you liked Mistborn',
      'epic fantasy like Mistborn',
      'hard magic system fantasy',
      'books like Brandon Sanderson Mistborn',
    ],
    recommendations: [
      { title: 'The Way of Kings', author: 'Brandon Sanderson', why: "Sanderson's magnum opus — a grander, more emotional scale with Cosmere connections to Mistborn. If you loved the magic system, Stormlight Archive takes it further.", genre: 'fantasy' },
      { title: 'The Final Empire (Mistborn #1)', author: 'Brandon Sanderson', why: "Already a fan? The second Mistborn era (Wax & Wayne) is a great steampunk continuation with the same magic in a new setting.", genre: 'fantasy' },
      { title: 'The Lies of Locke Lamora', author: 'Scott Lynch', why: "The heist fantasy par excellence — a crew of con artists in a renaissance city that feels as lived-in as Luthadel. Razor-sharp dialogue and devastating twists.", genre: 'fantasy' },
      { title: 'The Blade Itself', author: 'Joe Abercrombie', why: "Morally complex characters and a fantasy world that subverts every trope. If you loved Kelsier's cynicism, Abercrombie's cast will feel like family.", genre: 'fantasy' },
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "A different kind of hard magic system — sympathy — with a brilliant underdog protagonist. Rothfuss and Sanderson are the twin pillars of modern epic fantasy.", genre: 'fantasy' },
      { title: 'The Black Prism', author: 'Brent Weeks', why: "Lightbringer's color-based magic system rivals Allomancy for inventiveness. Political intrigue, a large cast, and a satisfying multi-book payoff.", genre: 'fantasy' },
      { title: 'Six of Crows', author: 'Leigh Bardugo', why: "Heist crew, impossible mission, morally gray characters with rich backstories. The Grisha world's equivalent of Mistborn's first arc.", genre: 'fantasy' },
      { title: 'The Goblin Emperor', author: 'Katherine Addison', why: "An unlikely protagonist thrust into power, navigating politics with kindness. A gentler counterpoint to Vin's story — still deeply rewarding.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'wheel-of-time',
    sourceTitle: 'The Wheel of Time',
    sourceShortName: 'WoT',
    tagline: 'Epic scope, deep lore, and an unforgettable world',
    description:
      "The Wheel of Time is one of fantasy's grandest achievements — 14 books, 4 million words, and a world with more depth than most. These books are the best companions and successors for readers who can't get enough.",
    keywords: [
      'books like Wheel of Time',
      'books like WoT',
      'epic fantasy like Wheel of Time',
      'books like Robert Jordan',
      'books similar to Wheel of Time',
      'what to read after Wheel of Time',
    ],
    recommendations: [
      { title: 'The Way of Kings', author: 'Brandon Sanderson', why: "Sanderson completed WoT — and Stormlight Archive is his own take on the epic-scale world-building Jordan pioneered. The most natural next series for WoT fans.", genre: 'fantasy' },
      { title: 'The Eye of the World', author: 'Robert Jordan', why: "Still in WoT? Book 1 is often the best re-read start. If you've finished: the New Spring prequel reveals Moiraine's backstory in full.", genre: 'fantasy' },
      { title: 'A Game of Thrones', author: 'George R.R. Martin', why: "Started the same year as WoT (1996) and shares the same epic ambition with a darker, more political edge. The two series defined a generation of fantasy.", genre: 'fantasy' },
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "Like WoT, it features a brilliant protagonist whose legend is larger than the man, told against a richly detailed world. Beautiful prose that Jordan fans love.", genre: 'fantasy' },
      { title: 'The Malazan Book of the Fallen', author: 'Steven Erikson', why: "If WoT isn't big enough — Malazan is even more complex, with a 10-book series and thousands of years of history. Demanding but rewarding.", genre: 'fantasy' },
      { title: 'The Sword of Kaigen', author: 'M.L. Wang', why: "A standalone epic with the emotional depth and magic of WoT compressed into a single devastating volume. Perfect palate cleanser.", genre: 'fantasy' },
      { title: 'The Stormlight Archive', author: 'Brandon Sanderson', why: "The series Sanderson built after proving himself on WoT — more emotionally intense, more intricate magic, and equally massive in scope.", genre: 'fantasy' },
      { title: 'Tigana', author: 'Guy Gavriel Kay', why: "Single-volume epic fantasy with WoT-level emotional impact. Kay understands the same tropes Jordan used and makes them sing.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'hunger-games',
    sourceTitle: 'The Hunger Games',
    sourceShortName: 'THG',
    tagline: 'Dystopian survival, revolution, and a heroine who fights back',
    description:
      "The Hunger Games defined a generation of YA dystopian fiction with its visceral survival stakes, political allegory, and a heroine who didn't have all the answers. These books match that energy and then some.",
    keywords: [
      'books like Hunger Games',
      'books similar to Hunger Games',
      'if you liked Hunger Games',
      'YA dystopian books like Hunger Games',
      'books like Suzanne Collins',
      'what to read after Hunger Games',
    ],
    recommendations: [
      { title: 'Divergent', author: 'Veronica Roth', why: "The most direct YA heir — faction-based dystopia, a female protagonist, and a love triangle. Shares Hunger Games' pacing and YA energy.", genre: 'fiction' },
      { title: 'The Maze Runner', author: 'James Dashner', why: "Teens in a deadly arena with no memory and no rules. Identical survival-thriller pacing — if you loved the Games, the Maze delivers.", genre: 'fiction' },
      { title: 'Red Queen', author: 'Victoria Aveyard', why: "Class war, unexpected powers, and a protagonist navigating political manipulation. The Hunger Games' political chess moves with a fantasy overlay.", genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "A brutal military empire, gladiatorial trials, and two protagonists who pay for every victory. The most mature and literary of the Hunger Games comparisons.", genre: 'fantasy' },
      { title: 'The Ballad of Songbirds and Snakes', author: 'Suzanne Collins', why: "The official Hunger Games prequel — Snow's origin story. Darker and more morally complex than the original trilogy.", genre: 'fiction' },
      { title: 'Legend', author: 'Marie Lu', why: "Two teenagers on opposite sides of a dystopian war discover the truth about their government. The Hunger Games' dual-perspective structure done brilliantly.", genre: 'fiction' },
      { title: 'The Giver', author: 'Lois Lowry', why: "The original YA dystopia — shorter, quieter, and more devastating than Hunger Games. Essential if you haven't read it.", genre: 'fiction' },
      { title: '1984', author: 'George Orwell', why: "The political allegory behind Hunger Games runs straight back to Orwell. If the Capitol's propaganda resonated with you, 1984 is the adult version.", genre: 'fiction' },
    ],
  },
  {
    slug: 'six-of-crows',
    sourceTitle: 'Six of Crows',
    sourceShortName: 'Grishaverse',
    tagline: 'Heist crews, morally gray antiheroes, and impossible odds',
    description:
      "Six of Crows perfected the heist fantasy formula — a broken crew of misfits, a job that should be impossible, and characters whose backstories punch you in the gut. These books deliver the same alchemy of camaraderie, clever plotting, and moral complexity.",
    keywords: [
      'books like Six of Crows',
      'books similar to Six of Crows',
      'if you liked Six of Crows',
      'heist fantasy books',
      'books like Leigh Bardugo',
      'Grishaverse similar books',
    ],
    recommendations: [
      { title: 'Mistborn: The Final Empire', author: 'Brandon Sanderson', why: "A crew of thieves and misfits taking on an immortal tyrant. Mistborn is the spiritual ancestor of Six of Crows' heist fantasy — the same underdog energy and beloved ensemble cast.", genre: 'fantasy' },
      { title: 'The Lies of Locke Lamora', author: 'Scott Lynch', why: "The benchmark for heist fantasy. Con artists in a Venetian-inspired city with razor-sharp dialogue, devastating twists, and a male duo dynamic that rivals Kaz and Inej.", genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "Dual POVs, forbidden love, brutal stakes, and a world where survival costs everything. Sabaa Tahir captures the same moral grayness as Bardugo.", genre: 'fantasy' },
      { title: 'The Gilded Wolves', author: 'Roshani Chokshi', why: "A diverse crew solves puzzles in 1889 Paris for a dangerous heist. The most direct Six of Crows successor — even sharing the ensemble structure.", genre: 'fantasy' },
      { title: 'Shadow and Bone', author: 'Leigh Bardugo', why: "Already a Six of Crows fan? The original Grisha trilogy gives Kaz's world more context and introduces the Darkling — one of fantasy's great villains.", genre: 'fantasy' },
      { title: 'Caraval', author: 'Stephanie Garber', why: "A mysterious game, layered deception, and the feeling that nothing is as it seems. Shares Six of Crows' atmosphere of danger and wonder.", genre: 'fantasy' },
      { title: 'The Night Circus', author: 'Erin Morgenstern', why: "Lush, atmospheric, and built around a competition with hidden rules. Readers who loved the magical tension of Grisha world often cite this as their next read.", genre: 'fantasy' },
      { title: 'Throne of Glass', author: 'Sarah J. Maas', why: "A morally complex female protagonist fighting for her freedom in a world of power and magic. Fans of Inej and Nina often love Celaena Sardothien.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'shadowhunters',
    sourceTitle: 'The Shadowhunter Chronicles',
    sourceShortName: 'Shadowhunters',
    tagline: 'Hidden worlds, forbidden love, and demon hunters',
    description:
      "The Shadowhunter Chronicles built one of YA fantasy's most elaborate universes — Nephilim, warlocks, vampires, and a mythology that expands with every series. These books deliver the same sense of a hidden world under the surface of ours, with romance and danger at every turn.",
    keywords: [
      'books like Shadowhunters',
      'books similar to Mortal Instruments',
      'if you liked Cassandra Clare',
      'urban fantasy like Shadowhunters',
      'books like City of Bones',
      'YA fantasy like Mortal Instruments',
    ],
    recommendations: [
      { title: 'Percy Jackson and the Olympians', author: 'Rick Riordan', why: "Modern mythology hidden in plain sight, a young protagonist discovering a hidden world, and found family. The most natural companion to the Shadowhunter Chronicles.", genre: 'fantasy' },
      { title: 'Beautiful Creatures', author: 'Kami Garcia & Margaret Stohl', why: "Southern Gothic meets supernatural romance. An ordinary boy discovers the girl he loves is part of a hidden magical world — structurally mirroring City of Bones.", genre: 'fantasy' },
      { title: 'Hush, Hush', author: 'Becca Fitzpatrick', why: "A human girl drawn into a world of fallen angels with a dangerous, compelling love interest. Shares Shadowhunters' forbidden romance energy.", genre: 'fantasy' },
      { title: 'The Mortal Instruments (City of Bones)', author: 'Cassandra Clare', why: "Already a fan of the later series? Go back to where it started — City of Bones remains one of the most gripping urban fantasy openers in YA.", genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "Forbidden love, hidden power, and a brutal world that tests its characters mercilessly. Older Shadowhunters readers consistently love this as a step up.", genre: 'fantasy' },
      { title: 'Daughter of Smoke and Bone', author: 'Laini Taylor', why: "A girl who doesn't know her true origins discovers a war between angels and demons. Lyrical prose and a haunting forbidden love — perfect for Clare fans.", genre: 'fantasy' },
      { title: 'The Cruel Prince', author: 'Holly Black', why: "Mortal girl, hidden magical world, and a ruthless antagonist who becomes a love interest. Holly Black and Cassandra Clare have long been the twin pillars of dark YA fantasy.", genre: 'fantasy' },
      { title: 'Vampire Academy', author: 'Richelle Mead', why: "A supernatural school, secret society politics, and a fierce female protagonist with a forbidden attraction. One of the most beloved Shadowhunters crossover fandoms.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'percy-jackson',
    sourceTitle: 'Percy Jackson & The Olympians',
    sourceShortName: 'Percy Jackson',
    tagline: 'Greek mythology, modern adventures, and found family',
    description:
      "Percy Jackson introduced a generation to mythology with humor, heart, and the most lovable dyslexic demigod in fiction. These books capture the same sense of adventure, ancient powers in a modern world, and friendships that feel like home.",
    keywords: [
      'books like Percy Jackson',
      'books similar to Percy Jackson',
      'if you liked Percy Jackson',
      'mythology books like Percy Jackson',
      'books like Rick Riordan',
      'what to read after Percy Jackson',
    ],
    recommendations: [
      { title: 'The Lightning Thief', author: 'Rick Riordan', why: "If you loved the Heroes of Olympus or Trials of Apollo — return to where it started. Book 1 is as fresh as ever, and it's the best entry to the Riordan-verse.", genre: 'fantasy' },
      { title: 'The Kane Chronicles: The Red Pyramid', author: 'Rick Riordan', why: "Egyptian mythology in the same world as Percy Jackson. Different gods, same wit. A great next step once you've finished the main series.", genre: 'fantasy' },
      { title: 'Magnus Chase and the Gods of Asgard', author: 'Rick Riordan', why: "Norse mythology, a homeless teen discovering his divine heritage, and the same ensemble humor. Magnus Chase is Riordan at his sharpest.", genre: 'fantasy' },
      { title: 'The Alchemyst', author: 'Michael Scott', why: "Nicholas Flamel is real, the Philosopher's Stone is real, and mythological figures from every culture are waging a war in San Francisco. A must-read for Percy Jackson fans.", genre: 'fantasy' },
      { title: 'Aru Shah and the End of Time', author: 'Roshani Chokshi', why: "Rick Riordan Presents — Indian mythology done with the same humor and heart as PJO. Aru Shah is one of the best protagonists in the mythological adventure genre.", genre: 'fantasy' },
      { title: 'Harry Potter and the Sorcerer\'s Stone', author: 'J.K. Rowling', why: "A child discovering they're part of a hidden magical world, a trio of best friends, and an ancient evil. The closest structural sibling to Percy Jackson.", genre: 'fantasy' },
      { title: 'The Septimus Heap series', author: 'Angie Sage', why: "A seventh son with magical gifts, a richly built world, and the same middle-grade adventure pacing. A beloved next-read for Percy Jackson fans.", genre: 'fantasy' },
      { title: 'A Wizard of Earthsea', author: 'Ursula K. Le Guin', why: "The original coming-of-age fantasy — a young boy with power he doesn't yet understand, a mentor, and a world of islands and magic. Required reading after Percy Jackson.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'outlander',
    sourceTitle: 'Outlander',
    tagline: 'Time travel, sweeping romance, and historical depth',
    description:
      "Outlander is a singular achievement — combining time travel, Scottish history, epic romance, and adventure in a way no other series quite matches. These books capture different facets of what makes Outlander irresistible.",
    keywords: [
      'books like Outlander',
      'books similar to Outlander',
      'if you liked Outlander',
      'time travel romance books',
      'historical romance like Outlander',
      'books like Diana Gabaldon',
    ],
    recommendations: [
      { title: 'The Bronze Horseman', author: 'Paullina Simons', why: "WWII Leningrad, a sweeping love story, and the same epic scale as Outlander. Devastating, beautiful, and addictive — the most frequently cited Outlander companion.", genre: 'fiction' },
      { title: 'All the Light We Cannot See', author: 'Anthony Doerr', why: "Dual perspectives across wartime Europe, historical depth, and the kind of emotional weight Outlander delivers over thousands of pages — compressed into one novel.", genre: 'fiction' },
      { title: 'A Discovery of Witches', author: 'Deborah Harkness', why: "A witch discovers an enchanted manuscript and a vampire she's not supposed to love. Time travel, forbidden romance, and rich historical texture — perfect for Outlander fans.", genre: 'fantasy' },
      { title: 'The Pillars of the Earth', author: 'Ken Follett', why: "Medieval cathedral-building epic with political intrigue, romance, and the same immersive historical world-building Gabaldon delivers. Equally long and equally gripping.", genre: 'fiction' },
      { title: 'The Time Traveler\'s Wife', author: 'Audrey Niffenegger', why: "Love that transcends time, bittersweet longing, and a relationship built across impossible circumstances. The emotional core of Outlander in a modern setting.", genre: 'fiction' },
      { title: 'Outlander: Cross Stitch', author: 'Diana Gabaldon', why: "The UK first edition title of Outlander itself — and a reminder that re-reading the series is always rewarding. Start from Book 1 for new details you missed.", genre: 'fiction' },
      { title: 'The Seven Husbands of Evelyn Hugo', author: 'Taylor Jenkins Reid', why: "A sweeping story of love, ambition, and sacrifice across decades. Shares Outlander's scope and its understanding of what people give up for the loves of their lives.", genre: 'fiction' },
      { title: 'Roots', author: 'Alex Haley', why: "Multi-generational epic spanning centuries and continents. For Outlander fans who love the historical sweep and the sense that history lives in people across time.", genre: 'fiction' },
    ],
  },
  {
    slug: 'folk-of-the-air',
    sourceTitle: 'The Folk of the Air',
    sourceShortName: 'Folk of the Air',
    tagline: 'Dark fae courts, ruthless politics, and enemies who become everything',
    description:
      "The Folk of the Air took fae fantasy to a darker, more morally complex place — Jude's survival in a court that despises her, and her power dynamic with Cardan, became one of fantasy's most beloved and discussed relationships. These books match that intensity.",
    keywords: [
      'books like The Cruel Prince',
      'books like Folk of the Air',
      'books similar to Holly Black',
      'fae fantasy books',
      'enemies to lovers fantasy',
      'books like Jude and Cardan',
    ],
    recommendations: [
      { title: 'A Court of Thorns and Roses', author: 'Sarah J. Maas', why: "The other half of the fae fantasy renaissance — ACOTAR and The Cruel Prince are the two books fans recommend to each other first. Equally dark, equally romantic.", genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "A mortal in a world that doesn't value her life, navigating power and love in equal measure. The same survival tension and complex romance as Jude's arc.", genre: 'fantasy' },
      { title: 'The Winner\'s Curse', author: 'Marie Rutkoski', why: "A general's daughter and her slave — power imbalance, forbidden love, and political maneuvering in an empire. Structurally closest to Jude and Cardan's dynamic.", genre: 'fantasy' },
      { title: 'Caraval', author: 'Stephanie Garber', why: "Atmospheric, layered, and full of deception. The sense of never knowing who to trust mirrors Folk of the Air's court politics perfectly.", genre: 'fantasy' },
      { title: 'From Blood and Ash', author: 'Jennifer L. Armentrout', why: "The most popular recommendation in the enemies-to-lovers romantasy space alongside CoHo and ACOTAR. Intense, twisty, and deeply romantic.", genre: 'fantasy' },
      { title: 'A Curse So Dark and Lonely', author: 'Brigid Kemmerer', why: "A Beauty and the Beast retelling with a morally complex prince and a modern heroine. The same power dynamic energy as Folk of the Air with a fairy tale structure.", genre: 'fantasy' },
      { title: 'Tithe', author: 'Holly Black', why: "Holly Black's earlier fae novel — her original vision of a mortal girl in the dangerous Faerie. Essential reading if you loved her writing in The Cruel Prince.", genre: 'fantasy' },
      { title: 'Kingdom of the Wicked', author: 'Kerri Maniscalco', why: "Enemies-to-lovers with a Sicilian setting, demonic intrigue, and a heroine who refuses to be a victim. One of the top Folk of the Air crossover reads.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'shades-of-magic',
    sourceTitle: 'Shades of Magic',
    sourceShortName: 'Shades of Magic',
    tagline: 'Parallel worlds, rare magic, and unforgettable characters',
    description:
      "Shades of Magic built one of fantasy's most beloved universes by asking: what if there were four parallel Londons, and only one person could travel between them? These books share the same sense of wonder, vivid world-building, and characters you'd follow anywhere.",
    keywords: [
      'books like Shades of Magic',
      'books similar to V.E. Schwab',
      'if you liked A Darker Shade of Magic',
      'portal fantasy books',
      'books like Victoria Schwab',
      'parallel worlds fantasy books',
    ],
    recommendations: [
      { title: 'The Invisible Life of Addie LaRue', author: 'V.E. Schwab', why: "V.E. Schwab's most acclaimed standalone — a woman who made a deal to live forever but be forgotten by everyone she meets. Literary, heartbreaking, and brilliant.", genre: 'fantasy' },
      { title: 'Vicious', author: 'V.E. Schwab', why: "College rivals become superhuman enemies. Schwab at her most propulsive — two anti-heroes in a revenge story that never lets up. Essential for Shades fans who want more.", genre: 'fantasy' },
      { title: 'The Night Circus', author: 'Erin Morgenstern', why: "A magical competition between two young magicians in an impossibly beautiful circus. Shares Shades of Magic's lush atmosphere and the sense that magic is alive in the world.", genre: 'fantasy' },
      { title: 'Six of Crows', author: 'Leigh Bardugo', why: "Found family, complex magic, and a richly built world where every character has layers. Fans of Kell and Lila consistently love Kaz Brekker's crew.", genre: 'fantasy' },
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "A rare magician narrating his own legend, with prose that makes every page feel lived-in. Rothfuss and Schwab are two of fantasy's finest stylists.", genre: 'fantasy' },
      { title: 'A Memory Called Empire', author: 'Arkady Martine', why: "A diplomat with a predecessor's memories navigating an alien empire. Literary SF with the same layered identity themes and prose quality as Schwab.", genre: 'sci-fi' },
      { title: 'The Last Magician', author: 'Lisa Maxwell', why: "Time-traveling thieves in 1920s New York, a magical underworld, and a heist that spans centuries. Shares Shades of Magic's setting of historical London and portal magic.", genre: 'fantasy' },
      { title: 'Daughter of Smoke and Bone', author: 'Laini Taylor', why: "A girl who moves between worlds carrying teeth for a wish-granting demon. The most lyrical and lush recommendation for Schwab fans — equally beautiful prose.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'red-rising',
    sourceTitle: 'Red Rising',
    sourceShortName: 'Red Rising',
    tagline: 'Ruthless sci-fi with the scope of Game of Thrones',
    description:
      "Red Rising is one of the most visceral, brilliantly plotted sci-fi series ever written — part Hunger Games, part Game of Thrones, all its own. These books match that ambition: sprawling casts, brutal stakes, and plots that keep you guessing until the final page.",
    keywords: [
      'books like Red Rising',
      'books similar to Red Rising',
      'if you liked Red Rising',
      'sci-fi like Red Rising',
      'books like Pierce Brown',
      'what to read after Red Rising',
    ],
    recommendations: [
      { title: 'The Hunger Games', author: 'Suzanne Collins', why: "The acknowledged parent of Red Rising — Darrow's name even echoes Katniss. Same survival competition premise, same political revolution arc, but Red Rising takes it much darker.", genre: 'fiction' },
      { title: 'The Way of Kings', author: 'Brandon Sanderson', why: "Epic scope, massive cast, and a protagonist rising from nothing to reshape a world. The fantasy equivalent of Red Rising's ambition and emotional payoffs.", genre: 'fantasy' },
      { title: 'A Game of Thrones', author: 'George R.R. Martin', why: "Red Rising is explicitly compared to GoT for its willingness to kill major characters and its political complexity. The inevitable companion for any Red Rising fan.", genre: 'fantasy' },
      { title: 'Ender\'s Game', author: 'Orson Scott Card', why: "A brilliant child trained in brutal military games who discovers the stakes are not what he thought. A clear forerunner to Red Rising's Institute arc.", genre: 'sci-fi' },
      { title: 'Old Man\'s War', author: 'John Scalzi', why: "Military sci-fi with the same scale as Red Rising's later solar system conflicts — pacey, smart, and gripping. Perfect for Red Rising fans ready for adult military SF.", genre: 'sci-fi' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "Military trials, an empire built on oppression, and two protagonists paying a price for every moral choice they make. The fantasy sibling to Red Rising.", genre: 'fantasy' },
      { title: 'The Stars Are Legion', author: 'Kameron Hurley', why: "Brutal politics on living worldships, betrayal on every page, and a female protagonist who refuses to stay down. A sci-fi companion that matches Red Rising's grimdark energy.", genre: 'sci-fi' },
      { title: 'Iron Gold', author: 'Pierce Brown', why: "Already finished the original trilogy? Iron Gold (Book 4) expands the POVs and scale dramatically. Many fans call it the best entry point for the second arc.", genre: 'sci-fi' },
    ],
  },
  {
    slug: 'emily-henry',
    sourceTitle: 'Emily Henry',
    tagline: 'Smart, funny romance with real emotional depth',
    description:
      "Emily Henry writes romance novels for readers who want wit alongside their feelings — heroines with jobs and ambitions, love interests who are actually interesting, and emotional payoffs that earn every moment. These books deliver the same intelligent warmth.",
    keywords: [
      'books like Emily Henry',
      'authors like Emily Henry',
      'if you liked Beach Read',
      'witty romance books',
      'books like Book Lovers',
      'smart contemporary romance',
    ],
    recommendations: [
      { title: 'It Ends with Us', author: 'Colleen Hoover', why: "The most cited Emily Henry crossover — gut-punch emotional romance with complex real-world themes. CoHo and Emily Henry are the twin pillars of modern BookTok romance.", genre: 'romance' },
      { title: 'The Hating Game', author: 'Sally Thorne', why: "Office enemies-to-lovers with sharp banter and electric tension. The closest match to Emily Henry's wit and pacing — equally hard to put down.", genre: 'romance' },
      { title: 'One Day in December', author: 'Josie Silver', why: "A woman who sees the man she's meant to be with through a bus window — and then he's her best friend's new boyfriend. The longing Henry fans crave, stretched into a full novel.", genre: 'romance' },
      { title: 'The Spanish Love Deception', author: 'Elena Armas', why: "Fake dating, workplace rivals, and the kind of banter that makes you laugh on public transport. Elena Armas is consistently the most recommended Emily Henry alternative.", genre: 'romance' },
      { title: 'In a Holidaze', author: 'Christina Lauren', why: "Groundhog Day romance in a holiday setting — light, clever, and warm in exactly the way Emily Henry's books are warm.", genre: 'romance' },
      { title: 'The Kiss Quotient', author: 'Helen Hoang', why: "An autistic economist hires an escort to help her with relationships. Unexpected, genuine, and emotionally resonant — for Henry fans who want something a bit different.", genre: 'romance' },
      { title: 'Eligible', author: 'Curtis Sittenfeld', why: "A modern Pride and Prejudice retelling — witty, literary, and full of the kind of sharp observation Emily Henry brings to every book.", genre: 'romance' },
      { title: 'Happy Place', author: 'Emily Henry', why: "Already a Beach Read fan? Happy Place is Henry's most emotionally layered novel — two exes faking their relationship at their friends' cottage. Her best book.", genre: 'romance' },
    ],
  },
  {
    slug: 'taylor-jenkins-reid',
    sourceTitle: 'Taylor Jenkins Reid',
    sourceShortName: 'TJR',
    tagline: 'Glamour, sacrifice, and love across the decades',
    description:
      "Taylor Jenkins Reid writes sweeping stories about ambitious people — the prices they pay, the loves they lose, and the legends they become. These books share her sense of scale, her fascination with fame and desire, and her ability to make you feel like you lived through something.",
    keywords: [
      'books like Taylor Jenkins Reid',
      'authors like Taylor Jenkins Reid',
      'if you liked Evelyn Hugo',
      'books like Daisy Jones',
      'celebrity fiction books',
      'books similar to Taylor Jenkins Reid',
    ],
    recommendations: [
      { title: 'The Seven Husbands of Evelyn Hugo', author: 'Taylor Jenkins Reid', why: "Still the crown jewel — if you've read it, read it again. If you haven't, start here. Everything else on this list is for after.", genre: 'fiction' },
      { title: 'Beautiful Boy', author: 'David Sheff', why: "A memoir about a father and a son — real, devastating, and as immersive as any TJR novel. For Reid fans who want emotional depth with a true story behind it.", genre: 'fiction' },
      { title: 'Rock Paper Scissors', author: 'Alice Feeney', why: "A couple at a crossroads — what they reveal to each other, what they've hidden, and what comes next. Shares TJR's ability to structure a relationship as a slow reveal.", genre: 'fiction' },
      { title: 'People We Meet on Vacation', author: 'Emily Henry', why: "Friends-to-lovers with the same dual-timeline structure TJR uses in Evelyn Hugo. If you love TJR's narrative architecture, Henry's use of it is equally satisfying.", genre: 'romance' },
      { title: 'Daisy Jones & The Six', author: 'Taylor Jenkins Reid', why: "Already a TJR fan? Daisy Jones is her most stylistically inventive novel — told as a rockumentary transcript. Essential reading for anyone who loved Evelyn Hugo.", genre: 'fiction' },
      { title: 'Pachinko', author: 'Min Jin Lee', why: "A multi-generational saga spanning a century of Korean and Japanese history. Epic scope, sacrificed dreams, and characters whose choices ripple through generations — TJR's literary peer.", genre: 'fiction' },
      { title: 'The Great Alone', author: 'Kristin Hannah', why: "Alaska wilderness, a family in crisis, and love under impossible pressure. Kristin Hannah is the most recommended TJR companion — same emotional devastation, different settings.", genre: 'fiction' },
      { title: 'Malibu Rising', author: 'Taylor Jenkins Reid', why: "Four famous siblings, one wild night, and the summer that changes everything. TJR uses a 24-hour structure to unravel decades of family history — brilliantly constructed.", genre: 'fiction' },
    ],
  },
  {
    slug: 'throne-of-glass',
    sourceTitle: 'Throne of Glass',
    sourceShortName: 'ToG',
    tagline: 'Assassin queens, dark magic, and epic high fantasy',
    description:
      "Throne of Glass follows Celaena Sardothien, one of fantasy's most iconic heroines — an assassin navigating political intrigue, ancient magic, and impossible choices. These books share ToG's blend of fierce female protagonists, sprawling world-building, and high-stakes adventure.",
    keywords: [
      'books like Throne of Glass',
      'books similar to Throne of Glass',
      'if you liked Throne of Glass',
      'books like Sarah J Maas Throne of Glass',
      'high fantasy books like ToG',
      'epic fantasy with strong female lead',
    ],
    recommendations: [
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "Roman-inspired empire, a fierce slave-girl navigating a brutal military world, and a slow-burn romance. Celaena fans consistently name Laia of Serra as her spiritual sister.", genre: 'fantasy' },
      { title: 'Red Queen', author: 'Victoria Aveyard', why: "A girl with hidden powers in a world that would destroy her if they knew. Sharp political twists, a strong heroine, and the same addictive pacing as ToG.", genre: 'fantasy' },
      { title: 'The Cruel Prince', author: 'Holly Black', why: "Mortal girl fighting for power in a court that underestimates her — the same energy as Celaena's arc in the glass castle. Jude is every bit the match for Celaena's fire.", genre: 'fantasy' },
      { title: 'A Court of Thorns and Roses', author: 'Sarah J. Maas', why: "The author's other masterwork — same sweeping world-building, fierce heroine, and enemies-to-lovers romance. If you loved ToG, ACOTAR is the essential next read.", genre: 'fantasy' },
      { title: 'Shadow and Bone', author: 'Leigh Bardugo', why: "Russian folklore-inspired world, a girl who discovers world-changing power, and a court full of dangerous allies. The Grisha trilogy shares ToG's scale and ambition.", genre: 'fantasy' },
      { title: 'The Poppy War', author: 'R.F. Kuang', why: "A girl from the slums rises through a military academy to discover devastating power rooted in shamanic traditions. Dark, epic, and unflinching — for ToG readers ready for something harder.", genre: 'fantasy' },
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "Epic scope, a legendary protagonist narrating their own myth, and prose that elevates the genre. Kvothe shares Celaena's talent, pride, and complicated relationship with power.", genre: 'fantasy' },
      { title: 'Nevernight', author: 'Jay Kristoff', why: "A girl trained by assassins in a school built on secrets and death — unmistakably ToG-adjacent. Darkly funny, morally complex, and addictive.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'crescent-city',
    sourceTitle: 'Crescent City',
    sourceShortName: 'CC',
    tagline: 'Urban fantasy, supernatural noir, and cosmic stakes',
    description:
      "Crescent City brings Sarah J. Maas's world-building into a neon-lit, urban fantasy setting packed with Fae, angels, demons, and half-bloods navigating a city that runs on power and secrets. These books share its blend of urban fantasy atmosphere, found family, and universe-shattering romance.",
    keywords: [
      'books like Crescent City',
      'books similar to House of Earth and Blood',
      'books like Sarah J Maas Crescent City',
      'urban fantasy books like Crescent City',
      'books like House of Sky and Breath',
    ],
    recommendations: [
      { title: 'City of Bones', author: 'Cassandra Clare', why: "Shadow hunters, demons, and a girl who discovers she's part of a hidden supernatural world in New York City. The original blueprint for Crescent City's urban fantasy DNA.", genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "A world where the powerful grind down the powerless, and a heroine who refuses to break. The same brutal stakes and found-family emotional core that define Crescent City.", genre: 'fantasy' },
      { title: 'From Blood and Ash', author: 'Jennifer L. Armentrout', why: "Forbidden love, hidden supernatural heritage, and the kind of slow burn that makes you reread chapters. Bryce and Hunt fans will find their fix here.", genre: 'fantasy' },
      { title: 'A Discovery of Witches', author: 'Deborah Harkness', why: "Supernatural beings navigating human and magical politics, a romance that spans centuries, and rich world-lore. More literary in pace but equally immersive.", genre: 'fantasy' },
      { title: 'The House in the Cerulean Sea', author: 'TJ Klune', why: "Cozy, warm, and full of heart — a magical bureaucracy protecting mythical creatures. A tonal counterpoint to Crescent City's intensity, beloved by the same readers.", genre: 'fantasy' },
      { title: 'Dark Fever', author: 'Karen Marie Moning', why: "Dublin gone supernatural-dark, a heroine pulled into fae world politics, and a morally ambiguous male lead. The Fever series is the adult urban fantasy that prefigured Crescent City.", genre: 'fantasy' },
      { title: 'Daughter of the Moon Goddess', author: 'Sue Lynn Tan', why: "Chinese mythology, a heroine on a celestial quest, and lyrical prose layered over high stakes. Fans of Crescent City's mythological richness will love this.", genre: 'fantasy' },
      { title: 'Ninth House', author: 'Leigh Bardugo', why: "Yale's secret societies are actually fronts for magic use — dark, literary, and gripping. Bardugo's adult debut shares Crescent City's ambition to expand a beloved author's world.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'blood-and-ash',
    sourceTitle: 'From Blood and Ash',
    sourceShortName: 'Blood & Ash',
    tagline: 'Forbidden romance, hidden truths, and epic romantic fantasy',
    description:
      "From Blood and Ash follows Poppy, a Maiden sheltered from the world, who finds herself drawn to Hawke — a guard who is far more than he appears. These books share its blend of passionate slow-burn romance, lush world-building, and shocking plot reveals.",
    keywords: [
      'books like From Blood and Ash',
      'books similar to Blood and Ash',
      'if you liked Jennifer Armentrout',
      'romantic fantasy books like Blood and Ash',
      'books like FBAA',
      'from blood and ash reading recommendations',
    ],
    recommendations: [
      { title: 'A Court of Thorns and Roses', author: 'Sarah J. Maas', why: "Forbidden love between a mortal girl and a dangerous fae, an enemy who becomes everything — the golden standard of romantic fantasy that Blood and Ash fans universally love.", genre: 'fantasy' },
      { title: 'Fourth Wing', author: 'Rebecca Yarros', why: "A brutal academy, enemies-to-lovers tension that crackles off the page, and a romance built on secrets and danger. The momentum and passion are identical to the Blood and Ash experience.", genre: 'fantasy' },
      { title: 'The Cruel Prince', author: 'Holly Black', why: "A mortal girl fighting for power among fae who underestimate her, falling for the cruelest prince of all. The forbidden romance and power dynamics map exactly onto Poppy and Hawke.", genre: 'fantasy' },
      { title: 'Crescent City', author: 'Sarah J. Maas', why: "Urban fantasy with the same slow burn, complex mythology, and devastating reveals. Bryce and Hunt's dynamic mirrors what makes Poppy and Hawke unforgettable.", genre: 'fantasy' },
      { title: 'Kingdom of the Wicked', author: 'Kerri Maniscalco', why: "Sicily meets demonic mystery in a world dripping with atmosphere. A headstrong heroine, a dangerously compelling devil, and a romance that builds through danger.", genre: 'fantasy' },
      { title: 'The Bridge Kingdom', author: 'Danielle L. Jensen', why: "Two enemies forced into proximity by political arrangement, discovering the line between duty and desire. Bridge Kingdom fans cite the same electric tension as From Blood and Ash.", genre: 'romance' },
      { title: 'A Soul of Ash and Blood', author: 'Jennifer L. Armentrout', why: "If you loved From Blood and Ash, continue in-series — Book 5 is narrated entirely from Hawke's perspective, giving new depth to everything you already loved.", genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "Two worlds collide, forbidden attraction ignites, and the stakes are life and death. The same urgent pacing and impossibly high emotional stakes as Blood and Ash.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'inheritance-games',
    sourceTitle: 'The Inheritance Games',
    sourceShortName: 'Inheritance Games',
    tagline: 'Billion-dollar secrets, irresistible puzzles, and four Hawthorne brothers',
    description:
      "The Inheritance Games follows Avery Grambs, who inherits a mysterious billionaire's fortune and must unravel his secrets — while navigating his four genius grandchildren. These books share its addictive mix of high-stakes mystery, tantalizing romance, and you-can't-put-it-down pacing.",
    keywords: [
      'books like The Inheritance Games',
      'books similar to Inheritance Games',
      'books like Jennifer Lynn Barnes',
      'YA mystery books like Inheritance Games',
      'books like Hawthorne brothers',
      'puzzle mystery books like Inheritance Games',
    ],
    recommendations: [
      { title: 'The Final Gambit', author: 'Jennifer Lynn Barnes', why: "The conclusion of the original trilogy — if you loved Books 1 and 2, this is the essential next read. Avery's story reaches its most dangerous and romantic chapter yet.", genre: 'thriller' },
      { title: 'The Lovely and the Lost', author: 'Jennifer Lynn Barnes', why: "Another Barnes mystery in her signature tightly plotted style, following a girl raised by search-and-rescue wolves. Perfect gateway for readers new to Barnes.", genre: 'thriller' },
      { title: 'One of Us Is Lying', author: 'Karen M. McManus', why: "Five students enter detention; one doesn't come out alive. The same locked-setting mystery, group dynamic tension, and compulsive readability.", genre: 'thriller' },
      { title: 'Knives Out (novelization/related)', author: 'Rian Johnson', why: "The Benoit Blanc mystery that redefined the genre. If you love the puzzle-box secrets and eccentric wealthy family of Inheritance Games, the Knives Out universe is required viewing and reading.", genre: 'thriller' },
      { title: 'The Gilded Wolves', author: 'Roshani Chokshi', why: "Paris, 1889 — a diverse crew races through a labyrinthine treasure hunt built on secrets and alliances. The intricate puzzle-solving and ensemble dynamics match Inheritance Games perfectly.", genre: 'fiction' },
      { title: 'Truly Devious', author: 'Maureen Johnson', why: "A genius girl solves a decades-old cold case at an elite school built for gifted students. The same heady mix of mystery, dark secrets, and off-kilter charm.", genre: 'thriller' },
      { title: 'The Last Heir', author: 'Jennifer Lynn Barnes', why: "If you love the Hawthorne world, The Grandest Game continues it with a new protagonist and a new deadly game — perfect for readers who finished the original trilogy.", genre: 'thriller' },
      { title: 'The Atlas Six', author: 'Olivie Blake', why: "Six magicians. One deadly society. A survival game where trust is a luxury nobody can afford. The intellectual rivalry and shadowy institution will satisfy Inheritance Games fans craving darker stakes.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'bridgerton',
    sourceTitle: 'Bridgerton',
    sourceShortName: 'Bridgerton',
    tagline: 'Witty Regency romance, Society scandals, and swoon-worthy heroes',
    description:
      "Julia Quinn's Bridgerton series set the gold standard for Regency romance with its sparkling wit, steamy tension, and lovable Bridgerton family. If you devoured the books (or the Netflix show), these novels offer the same blend of sparkling banter, unexpected love stories, and lush period settings.",
    keywords: [
      'books like Bridgerton',
      'Regency romance books like Bridgerton',
      'books similar to Julia Quinn',
      'historical romance novels like Bridgerton',
      'books to read after Bridgerton',
      'romance books like Netflix Bridgerton',
    ],
    recommendations: [
      { title: 'The Viscount Who Loved Me', author: 'Julia Quinn', why: "If you started with Season 1 / Daphne's book, this is Book 2 and the basis for Season 2 — Anthony and Kate's enemies-to-lovers story is widely considered the best in the series.", genre: 'romance' },
      { title: "Devil in Winter", author: 'Lisa Kleypas', why: "A brooding rake forced into marriage with a shy heiress — their slow-burn transformation into genuine partners is pitch-perfect Regency romance with all the emotional depth of Bridgerton.", genre: 'romance' },
      { title: 'The Wallflowers series', author: 'Lisa Kleypas', why: "Four wallflower friends make a marriage pact — each book delivers exactly the witty banter, Regency society intrigue, and character warmth that Bridgerton fans love.", genre: 'romance' },
      { title: 'A Week to Be Wicked', author: 'Tessa Dare', why: "A bluestocking and a rake embark on a cross-country adventure that becomes something neither expected. Tessa Dare's voice is the closest in the genre to Julia Quinn's trademark humor.", genre: 'romance' },
      { title: 'An Extraordinary Union', author: 'Alyssa Cole', why: "Historical romance at its most gripping — a spy during the Civil War, a forbidden attraction, and a plot that never lets up. For Bridgerton fans who want emotional depth with their swoon.", genre: 'romance' },
      { title: 'The Duke and I', author: 'Julia Quinn', why: "If you only watched the show, you'll love the added depth, humor, and internal monologue of the original novel that inspired Season 1.", genre: 'romance' },
      { title: 'Clockwork Prince', author: 'Cassandra Clare', why: "Forbidden feelings, impossible choices, and a love triangle set in Victorian London with a supernatural twist — for Bridgerton fans ready for something darker and more fantastical.", genre: 'fantasy' },
      { title: 'A Lady for a Duke', author: 'Alexis Hall', why: "A gorgeous, emotionally generous Regency romance between a trans woman and her childhood best friend — smart, warm, and utterly swoony in the Bridgerton tradition.", genre: 'romance' },
    ],
  },
  {
    slug: 'kingkiller-chronicle',
    sourceTitle: 'The Kingkiller Chronicle',
    sourceShortName: 'Kingkiller',
    tagline: 'A legendary hero tells his own story — one day at a time',
    description:
      "Patrick Rothfuss's Kingkiller Chronicle set a new bar for fantasy prose and world-building. While waiting for The Doors of Stone, these novels offer the same exceptional writing quality, deeply realized magic systems, and characters you can't stop thinking about.",
    keywords: [
      'books like Kingkiller Chronicle',
      'books similar to Patrick Rothfuss',
      'fantasy books like Name of the Wind',
      'books to read while waiting for Doors of Stone',
      'epic fantasy like Kingkiller Chronicle',
      'literary fantasy like Patrick Rothfuss',
    ],
    recommendations: [
      { title: 'The Way of Kings', author: 'Brandon Sanderson', why: "Massive, meticulous world-building; a protagonist forged through suffering who becomes something extraordinary. Stormlight Archive shares Kingkiller's epic scope and deeply introspective heroes — and book 5 just came out.", genre: 'fantasy' },
      { title: 'The Lies of Locke Lamora', author: 'Scott Lynch', why: "A brilliant, charming rogue navigating a city of crime — one of the few fantasy novels that matches Rothfuss's prose quality and Kvothe's clever, performative charisma.", genre: 'fantasy' },
      { title: 'A Little Hatred', author: 'Joe Abercrombie', why: "Gritty, character-driven epic fantasy where no one is purely heroic and the world refuses to be simple. Abercrombie's prose is as confident and subversive as Rothfuss's best.", genre: 'fantasy' },
      { title: 'The Black Prism', author: 'Brent Weeks', why: "A stunning magic system built around light and color, a hero carrying impossible secrets, and a plot that escalates relentlessly. The Lightbringer series delivers the same page-turning momentum as Kingkiller.", genre: 'fantasy' },
      { title: 'Jonathan Strange & Mr Norrell', author: 'Susanna Clarke', why: "Deeply literary fantasy with extraordinary attention to voice and detail — and a complete story, unlike the Kingkiller wait. Clarke's approach to magic feels as grounded and internally consistent as Rothfuss's Alar.", genre: 'fantasy' },
      { title: 'The Eye of the World', author: 'Robert Jordan', why: "The gold standard for epic scope — 14 books that actually reached their ending. For Kingkiller fans who want a fully completed master work while the wait continues.", genre: 'fantasy' },
      { title: 'Elantris', author: 'Brandon Sanderson', why: "A tight, self-contained fantasy with a unique magic system and satisfying resolution in a single volume — perfect for readers who want the satisfaction of a complete story while waiting for Doors of Stone.", genre: 'fantasy' },
      { title: 'The Night Circus', author: 'Erin Morgenstern', why: "Gorgeous, immersive literary fantasy with prose as lush as Rothfuss's — two young magicians bound in an unseen contest, a world soaked in atmosphere and longing.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'the-witcher',
    sourceTitle: 'The Witcher',
    sourceShortName: 'Witcher',
    tagline: 'A morally grey monster hunter in a brutal, beautiful world',
    description:
      "Andrzej Sapkowski's Witcher saga is dark, literary fantasy with a deeply human heart. These books capture the same moral complexity, subverted tropes, exceptional world-building, and unforgettable characters that made Geralt of Rivia a legend — perfect for Witcher fans between reads or looking for their next obsession.",
    keywords: [
      'books like The Witcher',
      'fantasy books like Witcher series',
      'books similar to Andrzej Sapkowski',
      'dark fantasy like Witcher',
      'books like Geralt of Rivia',
      'grimdark fantasy like Witcher',
    ],
    recommendations: [
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "The same exceptional literary prose, a legendary protagonist narrating his own extraordinary past, and a world-building depth that rewards rereading. Many consider Kvothe the Geralt of his generation.", genre: 'fantasy' },
      { title: 'The Blade Itself', author: 'Joe Abercrombie', why: "Abercrombie is the king of grimdark — morally compromised characters, a world without clean heroes, and brutal honesty about the cost of violence. The closest modern equivalent to Sapkowski's tone.", genre: 'fantasy' },
      { title: 'The Lies of Locke Lamora', author: 'Scott Lynch', why: "A brilliant, charming rogue in a fantastically realized city, the same dark wit and street-level intimacy as The Last Wish. Locke Lamora is Geralt in a heist fantasy.", genre: 'fantasy' },
      { title: 'The Way of Kings', author: 'Brandon Sanderson', why: "Massive scope, an intricate magic system, and a world shaped by war and ancient mystery — for Witcher fans who want the epic canvas of the novel saga rather than the short story texture.", genre: 'fantasy' },
      { title: 'The Dragon Republic', author: 'R.F. Kuang', why: "War, empire, and a protagonist grappling with catastrophic power she can't fully control — R.F. Kuang's Poppy War trilogy shares Sapkowski's willingness to go to genuinely dark places.", genre: 'fantasy' },
      { title: 'Jonathan Strange & Mr Norrell', author: 'Susanna Clarke', why: "Deeply researched historical fantasy with an ironic, literary voice — for readers who love Sapkowski's intelligence and his eye for what folklore and fairy tale really mean at their roots.", genre: 'fantasy' },
      { title: 'Blood of Elves', author: 'Andrzej Sapkowski', why: "If you came to the Witcher through the games or Netflix, start here — or better yet start with The Last Wish. The novels expand the world in ways no other medium has managed.", genre: 'fantasy' },
      { title: 'The Poppy War', author: 'R.F. Kuang', why: "The same refusal to flinch, war portrayed without glory, and a protagonist forged into something terrible — Rin's story is as morally complex as anything in the Witcher saga.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'twisted',
    sourceTitle: 'Twisted Series',
    sourceShortName: 'Twisted',
    tagline: 'Wealthy alpha heroes, slow burns, and unforgettable BookTok romance',
    description:
      "Ana Huang's Twisted Series set the template for the BookTok dark romance era. These books deliver the same morally grey billionaire heroes, electric tension, and satisfying emotional payoffs — perfect for readers who devoured Twisted Love and want their next obsession.",
    keywords: [
      'books like Twisted Love',
      'books like Ana Huang',
      'dark romance like Twisted series',
      'books similar to Twisted Love Ana Huang',
      'romance books like Twisted series',
      'BookTok romance like Twisted',
    ],
    recommendations: [
      { title: 'Twisted Games', author: 'Ana Huang', why: "The next book in the series — Rhys and Bridget's bodyguard romance is considered many fans' favorite of the Twisted books, with incredible chemistry and a swoony forbidden dynamic.", genre: 'romance' },
      { title: 'Icebreaker', author: 'Hannah Grace', why: "Two college athletes, enemies-to-lovers tension, and the same addictive slow-burn that made Twisted Love unforgettable. Hannah Grace is Ana Huang's closest creative kin.", genre: 'romance' },
      { title: 'People We Meet on Vacation', author: 'Emily Henry', why: "Best-friends-to-lovers with devastating emotional payoff. Emily Henry delivers the same slow-build tension and emotional depth as Ana Huang's best, with a literary voice that lingers.", genre: 'romance' },
      { title: 'The Spanish Love Deception', author: 'Elena Armas', why: "Fake-dating with simmering chemistry, a large cast of lovable side characters, and all the will-they-won't-they tension that Twisted Lies fans will recognize immediately.", genre: 'romance' },
      { title: 'Things We Never Got Over', author: 'Lucy Score', why: "Small-town setting, an irresistible grumpy hero, and a heroine who surprises everyone including herself. Lucy Score has the same easy readability and emotional satisfaction as Ana Huang.", genre: 'romance' },
      { title: 'It Ends with Us', author: 'Colleen Hoover', why: "The CoHo classic that lives at the intersection of swoon and heartbreak — for Twisted readers who want emotional depth alongside their romance.", genre: 'romance' },
      { title: 'The Love Hypothesis', author: 'Ali Hazelwood', why: "Academic fake-dating with a nerdy heroine and a secretly soft alpha — the same lighthearted-but-swoony energy as Twisted Lies, in a STEM setting.", genre: 'romance' },
      { title: 'Ugly Love', author: 'Colleen Hoover', why: "Friends with benefits spiral into something neither character is prepared for. The intensity and emotional whiplash are the same signature high as Twisted Love's angstiest moments.", genre: 'romance' },
    ],
  },
  {
    slug: 'shatter-me',
    sourceTitle: 'Shatter Me Series',
    sourceShortName: 'Shatter Me',
    tagline: 'Lyrical YA fantasy with superpowers, forbidden love, and breathtaking prose',
    description:
      "Tahereh Mafi's Shatter Me series rewrote what YA dystopian fiction could feel like — lush, poetic prose wrapped around a slow-burn love triangle, a girl whose touch can kill, and a world teetering on collapse. These picks share the same intoxicating mix of romance and power.",
    keywords: [
      'books like Shatter Me',
      'books like Tahereh Mafi',
      'YA fantasy like Shatter Me',
      'books similar to Shatter Me series',
      'dystopian romance like Shatter Me',
      'YA books with superpowers and romance',
    ],
    recommendations: [
      { title: 'Ignite Me', author: 'Tahereh Mafi', why: "The series climax where everything clicks — Warner finally gets his full due, the prose hits its peak, and readers who loved the first book find out why Shatter Me never really ended.", genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "Ruthless empire, forbidden love across enemy lines, and a heroine who discovers her own power — Tahir's Roman-inspired fantasy has the same fierce emotional core as Shatter Me.", genre: 'fantasy' },
      { title: 'Shadow and Bone', author: 'Leigh Bardugo', why: "Grisha powers, a morally complex villain-love-interest, and gorgeous world-building — the Grishaverse is the closest artistic cousin to Shatter Me's mix of romance and superpower fantasy.", genre: 'fantasy' },
      { title: 'Red Queen', author: 'Victoria Aveyard', why: "A girl with hidden power in a world divided by blood — Mare Barrow's story has the same propulsive tension, shifting loyalties, and will-he-won't-he romance that keeps Shatter Me fans reading.", genre: 'fantasy' },
      { title: 'The Cruel Prince', author: 'Holly Black', why: "Dark fae courts, a fierce and flawed heroine, and a villain who reads as dangerous and magnetic as Warner at his most morally grey — Holly Black writes forbidden attraction with the same electricity.", genre: 'fantasy' },
      { title: 'Six of Crows', author: 'Leigh Bardugo', why: "The same Grishaverse but noir: six morally grey thieves on a heist, with the most intricate character dynamics in YA fantasy. Perfect for Shatter Me readers ready for something more ensemble.", genre: 'fantasy' },
      { title: 'Daughter of the Moon Goddess', author: 'Sue Lynn Tan', why: "Lyrical prose, a heroine defined by love and sacrifice, and a richly imagined mythology — Tan's writing has the same poetic quality that makes Mafi's style unforgettable.", genre: 'fantasy' },
      { title: 'The Sky Is Everywhere', author: 'Jandy Nelson', why: "Not fantasy, but Mafi has cited Jandy Nelson's lyrical, emotionally devastating YA as an influence. If you love how Shatter Me reads more than how it plots, start here.", genre: 'romance' },
    ],
  },
  {
    slug: 'atlas-six',
    sourceTitle: 'The Atlas Six',
    sourceShortName: 'Atlas Six',
    tagline: 'Dark academia fantasy with morally complex characters and deadly stakes',
    description:
      "Olivie Blake's The Atlas Six drops six brilliant magicians into a secret society where only five will survive — and explores what power, knowledge, and ambition cost when pushed to their extremes. These picks match its dark academia energy, its ensemble of antiheroes, and its willingness to ask uncomfortable questions.",
    keywords: [
      'books like The Atlas Six',
      'books like Olivie Blake',
      'dark academia fantasy like Atlas Six',
      'books similar to The Atlas Six',
      'morally grey fantasy ensemble books',
      'secret society fantasy books',
    ],
    recommendations: [
      { title: 'The Atlas Paradox', author: 'Olivie Blake', why: "Book 2 — the allegiances are already cracking and the philosophical stakes have doubled. Everything Atlas Six set up pays off in increasingly dark ways here.", genre: 'fantasy' },
      { title: 'The Secret History', author: 'Donna Tartt', why: "The dark academia original: a tight circle of classics students, a terrible secret, and a narrator obsessed with beauty and belonging. Tartt's novel is the moral ancestor of The Atlas Six.", genre: 'thriller' },
      { title: 'Babel', author: 'R.F. Kuang', why: "Oxford magic, colonial power, and a group of brilliant outsiders forced to reckon with what institutions cost — R.F. Kuang writes the same intersection of academic ambition and moral compromise.", genre: 'fantasy' },
      { title: 'If We Were Villains', author: 'M.L. Rio', why: "Seven Shakespeare students, one death, and ten years of secrets — this is The Secret History for theatre kids and The Atlas Six for readers who prefer literary over spectacle.", genre: 'thriller' },
      { title: 'A Deadly Education', author: 'Naomi Novik', why: "A school where the building itself is trying to kill you, a prickly protagonist of enormous untapped power, and wry dark humor throughout — Novik hits the same 'brilliance vs. survival' chord.", genre: 'fantasy' },
      { title: 'Ninth House', author: 'Leigh Bardugo', why: "Yale's secret magical societies, a heroine who sees things she shouldn't, and genuine darkness handled without apology — Bardugo's adult debut lives in the same moral universe as Blake's work.", genre: 'fantasy' },
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "A young genius navigating a legendary academy with limited resources and limitless ambition — Kvothe's story shares the Atlas Six's obsession with the cost of being the smartest person in any room.", genre: 'fantasy' },
      { title: 'Jonathan Strange & Mr Norrell', author: 'Susanna Clarke', why: "Philosophical, literary, and concerned with what magic really means as a form of power — for Atlas Six readers who want the intellectual density without the morally grey ensemble.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'hunger-games',
    sourceTitle: 'The Hunger Games',
    sourceShortName: 'Hunger Games',
    tagline: 'Dystopian survival, revolution, and unforgettable heroines',
    description:
      "The Hunger Games redefined YA dystopia and set the template for a decade of survival fiction. These picks match its propulsive pacing, its morally complex heroines, and its willingness to go to genuinely dark places — perfect for readers waiting for Sunrise on the Reaping (March 2026).",
    keywords: [
      'books like Hunger Games',
      'books like Suzanne Collins',
      'dystopian books like Hunger Games',
      'books similar to Hunger Games',
      'YA survival books like Hunger Games',
      'books like Katniss Everdeen',
    ],
    recommendations: [
      { title: 'Sunrise on the Reaping', author: 'Suzanne Collins', why: "The next Hunger Games book — Haymitch Abernathy's own Hunger Games, the 50th (Second Quarter Quell), set 24 years before Katniss was born. Out March 2026.", genre: 'sci-fi' },
      { title: 'The Ballad of Songbirds and Snakes', author: 'Suzanne Collins', why: "Young Coriolanus Snow mentors a District 12 tribute in the 10th Hunger Games — essential context for the whole universe, and a genuinely unsettling portrait of how a villain is made.", genre: 'sci-fi' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "A brutal empire, death-defying trials, and a heroine fighting from the inside — Tahir's Roman-fantasy setting has the same high-stakes survival energy as the Games, with a romance that burns just as hot.", genre: 'fantasy' },
      { title: 'Red Rising', author: 'Pierce Brown', why: "A boy from the lowest caste infiltrates the ruling class in a deadly academy — the most direct literary heir to The Hunger Games, but with scope that expands into a six-book space opera.", genre: 'sci-fi' },
      { title: 'Legend', author: 'Marie Lu', why: "A teenage criminal and a military prodigy on opposite sides of a dystopian divide — Marie Lu's dual-POV structure and propulsive pacing make Legend the most direct Hunger Games successor in YA.", genre: 'sci-fi' },
      { title: 'Divergent', author: 'Veronica Roth', why: "A girl who doesn't fit any faction in a divided society, forced into brutal initiation trials. Divergent captured the same readership as Hunger Games for exactly the same reasons.", genre: 'sci-fi' },
      { title: 'The Maze Runner', author: 'James Dashner', why: "Boys trapped in a deadly maze with no memory of their past — the same survival-puzzle energy as the Games, built around a mystery that unravels book by book.", genre: 'sci-fi' },
      { title: 'Scythe', author: 'Neal Shusterman', why: "A future where death is abolished except by the Scythe — chosen to cull the population. Shusterman's meticulous world-building and moral complexity make this the most literary Hunger Games successor.", genre: 'sci-fi' },
    ],
  },
  {
    slug: 'wheel-of-time',
    sourceTitle: 'The Wheel of Time',
    sourceShortName: 'Wheel of Time',
    tagline: 'Epic fantasy at its most ambitious — world-spanning, character-deep',
    description:
      "Robert Jordan's Wheel of Time set the bar for what epic fantasy could be — intricate magic, an enormous cast, and a world built with the same rigor as our own. These picks share its scale, its commitment to lore, and its willingness to let characters evolve across thousands of pages.",
    keywords: [
      'books like Wheel of Time',
      'books like Robert Jordan',
      'epic fantasy like Wheel of Time',
      'books similar to Wheel of Time',
      'long fantasy series like WoT',
      'fantasy books like Eye of the World',
    ],
    recommendations: [
      { title: 'The Way of Kings', author: 'Brandon Sanderson', why: "Sanderson finished the Wheel of Time — and The Stormlight Archive is his own answer to Jordan's scope. Roshar is as deeply realized as Randland, and the magic system is arguably the most innovative in fantasy.", genre: 'fantasy' },
      { title: 'A Game of Thrones', author: 'George R.R. Martin', why: "The other colossus of 90s epic fantasy. Where Jordan builds a hopeful world under existential threat, Martin deconstructs genre tropes with ruthless political realism and devastating character deaths.", genre: 'fantasy' },
      { title: 'The Eye of the World', author: 'Robert Jordan', why: "If you haven't started the Wheel of Time yet, start here. Five villagers, one dragon, and a world about to end — Jordan's opening volume matches Tolkien for scope and inverts the genre's assumptions about who the hero is.", genre: 'fantasy' },
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "The other great unfinished fantasy epic — literary, intimate, and astonishingly good. Kvothe's story has the same mythic texture as Rand al'Thor's, with prose that reads like music.", genre: 'fantasy' },
      { title: 'Memories of Ice', author: 'Steven Erikson', why: "The third book in the Malazan Book of the Fallen — the series that matches Wheel of Time's scope and arguably exceeds it for ambition. Start with Gardens of the Moon, but Memories of Ice is the masterpiece.", genre: 'fantasy' },
      { title: 'The Blade Itself', author: 'Joe Abercrombie', why: "The anti-Wheel of Time: same epic scope but from a grimdark perspective where magic is ugly and heroes are morally compromised. A perfect next step for WoT readers ready for something darker.", genre: 'fantasy' },
      { title: 'Tigana', author: 'Guy Gavriel Kay', why: "A single standalone fantasy about a land whose name has been erased from memory — profound, heartbreaking, and written with the same density of world-building as Jordan, at a fraction of the page count.", genre: 'fantasy' },
      { title: 'The Priory of the Orange Tree', author: 'Samantha Shannon', why: "A standalone epic with dragons, multiple POVs, and a world-map that rewards obsessive study — for WoT readers who want the scale but want it finished in one volume.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'poppy-war',
    sourceTitle: 'The Poppy War',
    sourceShortName: 'Poppy War',
    tagline: 'Dark military fantasy that unflinchingly confronts history and power',
    description:
      "R.F. Kuang's Poppy War trilogy changed what fantasy could do with history. These picks share its willingness to go to genuinely dark places, its non-Western influences, and its insistence that power — including magical power — always has a cost.",
    keywords: [
      'books like The Poppy War',
      'books like R.F. Kuang',
      'dark fantasy like Poppy War',
      'books similar to Poppy War',
      'books like Babel RF Kuang',
      'Asian-inspired dark fantasy books',
    ],
    recommendations: [
      { title: 'Babel', author: 'R.F. Kuang', why: "Kuang's own follow-up — Oxford silver-working fantasy about colonialism, translation, and the violence institutions require. More literary and more devastating than the Poppy War trilogy.", genre: 'fantasy' },
      { title: 'The Dragon Republic', author: 'R.F. Kuang', why: "Book 2 of the trilogy — the war escalates, Rin's power becomes uncontrollable, and the political complexity deepens. Essential if you finished The Poppy War.", genre: 'fantasy' },
      { title: 'The Burning God', author: 'R.F. Kuang', why: "The trilogy conclusion — the most emotionally devastating entry, where every choice made in Books 1 and 2 comes due.", genre: 'fantasy' },
      { title: 'The Poppy War', author: 'R.F. Kuang', why: "If you loved Babel or Yellowface and haven't read the trilogy yet — this is where Kuang's career began. Darker and more violent than her standalones, and absolutely essential.", genre: 'fantasy' },
      { title: 'A Little Hatred', author: 'Joe Abercrombie', why: "Industrial-age grimdark fantasy where the revolution has begun and nothing is heroic — Abercrombie's Age of Madness trilogy shares Kuang's refusal to glorify violence or power.", genre: 'fantasy' },
      { title: 'She Who Became the Sun', author: 'Shelley Parker-Chan', why: "Ming-dynasty China, a girl who steals her dead brother's destiny and leads armies to heaven's mandate — Parker-Chan's debut shares Kuang's ferocity, historical depth, and queer complexity.", genre: 'fantasy' },
      { title: 'The Priory of the Orange Tree', author: 'Samantha Shannon', why: "A standalone epic with East-Asian-influenced world-building, dragons without a hint of Euro-fantasy, and a scope that rewards the same dedicated reading Kuang demands.", genre: 'fantasy' },
      { title: 'Yellowface', author: 'R.F. Kuang', why: "Kuang's sharpest, most accessible work — a literary satire about race and authorship in publishing. Not fantasy, but it shows the full range of one of the best writers in any genre right now.", genre: 'fiction' },
    ],
  },
  {
    slug: 'dark-tower',
    sourceTitle: 'The Dark Tower',
    sourceShortName: 'Dark Tower',
    tagline: 'Genre-defying epic spanning Western, horror, fantasy, and science fiction',
    description:
      "Stephen King's Dark Tower series invented its own genre — a Western epic that bleeds into horror, fantasy, and science fiction, with a Gunslinger at its center who has become one of literature's great tragic heroes. These picks share its mythic scope, its genre-blending audacity, and its willingness to take years to resolve.",
    keywords: [
      'books like Dark Tower',
      'books like Stephen King Dark Tower',
      'fantasy like The Dark Tower',
      'books similar to Dark Tower series',
      'gunslinger books like Dark Tower',
      'Stephen King multiverse books',
    ],
    recommendations: [
      { title: 'The Wind Through the Keyhole', author: 'Stephen King', why: "If you've read through Wizard and Glass, don't skip this — a story within a story within a story that adds a mythic layer to Roland's world.", genre: 'fantasy' },
      { title: 'The Stand', author: 'Stephen King', why: "King's other epic — a post-apocalyptic battle between good and evil across the American landscape. Randall Flagg appears in both; The Stand is the closest King ever came to replicating the Tower's mythic scale.", genre: 'horror' },
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "A legendary hero tells his own story from a quiet inn — the framing device, the mythic past-vs.-present structure, and the sense of a world-shaking story almost too large to contain all echo the Dark Tower.", genre: 'fantasy' },
      { title: 'American Gods', author: 'Neil Gaiman', why: "Old gods of the immigrant world vs. new gods of media in a mythic American landscape — Gaiman's America feels like a world Roland might ride through, where mythology bleeds into every diner and highway.", genre: 'fantasy' },
      { title: 'The Blade Itself', author: 'Joe Abercrombie', why: "A legendary warrior past his prime, a world unraveling, and no clear villain — Abercrombie's First Law trilogy shares the Tower's subversive take on heroic archetypes.", genre: 'fantasy' },
      { title: 'A Wizard of Earthsea', author: 'Ursula K. Le Guin', why: "The source from which all mythic-quest fantasy flows — Le Guin's spare prose and deep world create the same sense of a world with history stretching back thousands of years.", genre: 'fantasy' },
      { title: 'Piranesi', author: 'Susanna Clarke', why: "A man living alone in a house of infinite halls and endless seas — Clarke's mystery unfolds with the same sense of a world that is also a symbol, logic you can feel but not quite state.", genre: 'fantasy' },
      { title: 'Good Omens', author: 'Terry Pratchett and Neil Gaiman', why: "Not the same tone, but for readers who love the Tower's collision of mythologies and genres — Pratchett and Gaiman blending apocalyptic stakes with comedy proves genre-blending at its most joyful.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'harry-potter',
    sourceTitle: 'Harry Potter',
    tagline: 'Magic systems, chosen heroes, and worlds hiding in plain sight',
    description:
      "Harry Potter opened millions of readers to fantasy — a hidden magical world, a young hero discovering their own power, and a school where the lessons are more dangerous than the exams. These books capture that same sense of wonder: magic that feels real, friendships forged under pressure, and the feeling that there is a bigger, stranger world just around the corner.",
    keywords: [
      'books like Harry Potter',
      'books similar to Harry Potter',
      'fantasy books like Harry Potter for adults',
      'magic school books like Harry Potter',
      'if you loved Harry Potter what to read next',
      'books like Harry Potter for adults',
      'fantasy books with magic schools',
      'chosen one fantasy novels',
      'books to read after Harry Potter',
    ],
    recommendations: [
      { title: 'The Name of the Wind', author: 'Patrick Rothfuss', why: "A legendary wizard tells his own story at an inn — his childhood, his time at a magic university, and how he became a myth. The most acclaimed adult equivalent to Harry Potter, with a magic system built on logic and a sense of wondrous discovery in every chapter.", genre: 'fantasy' },
      { title: 'Percy Jackson and the Olympians', author: 'Rick Riordan', why: "A twelve-year-old discovers he's the son of a Greek god and that mythology is real and dangerous. The closest match to Harry Potter's energy — funny, action-packed, and built on a world hiding in plain sight. A perfect bridge for younger readers and beloved by adults.", genre: 'fantasy' },
      { title: 'The Magicians', author: 'Lev Grossman', why: "Often called the adult Harry Potter — a Brooklyn teenager discovers a secret university for real magicians. Grossman deconstructs the magic school fantasy with sharp wit and emotional depth, examining what it would really feel like to live in a chosen-hero story.", genre: 'fantasy' },
      { title: 'Jonathan Strange & Mr Norrell', author: 'Susanna Clarke', why: "Two magicians compete to restore English magic during the Napoleonic Wars. Clarke's footnote-laden alternate history creates one of fantasy's most complete alternate worlds — British, scholarly, and full of a magic that feels genuinely old.", genre: 'fantasy' },
      { title: 'The Night Circus', author: 'Erin Morgenstern', why: "A competition between two young magicians plays out inside a mysterious travelling circus that only appears at night. Morgenstern's prose is pure enchantment — atmospheric, sensory, and suffused with wonder.", genre: 'fantasy' },
      { title: 'Eragon', author: 'Christopher Paolini', why: "A farm boy discovers a dragon egg and is pulled into an ancient conflict. Written by a teenager, it captures the same coming-of-age energy as Potter — a young hero, a vast world, and a sense that the hero's destiny is written into the stars.", genre: 'fantasy' },
      { title: 'Carry On', author: 'Rainbow Rowell', why: "Explicitly inspired by Harry Potter fanfiction, Carry On follows Simon Snow — the Chosen One at a magical boarding school — in a story that both celebrates and gently interrogates everything the genre is built on. Funny, romantic, and warm.", genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "A military empire, a secret resistance, and two young people on opposite sides. Tahir's world is brutal and layered — the school setting, the sense of danger in every lesson, and the slow-burn intensity all resonate strongly with Potter fans.", genre: 'fantasy' },
    ],
  },
  {
    slug: 'shadow-and-bone',
    sourceTitle: 'Shadow and Bone',
    sourceShortName: 'Grishaverse',
    tagline: 'Dark powers, forbidden romance, and a world that wants to use you',
    description:
      "Shadow and Bone introduced millions of readers to the Grishaverse — Alina Starkov's discovery of her powers, the seductive Darkling, and a fantasy Russia built from myth and shadow. These books share the same qualities: a heroine who is special but uncertain, a morally complex villain with charisma, dark magic in a lush historical world, and a romance that burns.",
    keywords: [
      'books like Shadow and Bone',
      'books like Grishaverse',
      'books like Leigh Bardugo',
      'Grishaverse reading order',
      'books like the Darkling',
      'dark fantasy romance like Shadow and Bone',
      'enemies to lovers fantasy books',
      'fantasy books with dark heroes',
      'books like Six of Crows',
      'what to read after Shadow and Bone',
    ],
    recommendations: [
      { title: 'Six of Crows', author: 'Leigh Bardugo', why: "The natural next step — the same Grishaverse world, but a heist crew of criminals instead of a chosen girl. Kaz Brekker and his crew are among fantasy's most beloved characters. If you haven't read it, start here; if you have, the rest of this list is for you.", genre: 'fantasy' },
      { title: 'An Ember in the Ashes', author: 'Sabaa Tahir', why: "A military empire, forbidden powers, and an enemies-to-lovers tension that burns. Laia and Elias are as compelling as Alina and Mal, and Tahir's world rivals Bardugo's in richness and brutality.", genre: 'fantasy' },
      { title: 'The Cruel Prince', author: 'Holly Black', why: "A mortal girl kidnapped to faerie who decides to seize power herself — and a ruthless fae prince who is her most dangerous obstacle. The Darkling's charisma, the political intrigue, and the slow-burn antagonism are all here.", genre: 'fantasy' },
      { title: 'Children of Blood and Bone', author: 'Tomi Adeyemi', why: "Magic has been stripped from West African-inspired world by a king who fears it. A young woman discovers she can bring it back. The chosen-one energy, the lush magical system, and the stakes are as high as any in Bardugo.", genre: 'fantasy' },
      { title: 'Red Queen', author: 'Victoria Aveyard', why: "A girl with no powers discovers she has the rarest gift in a world divided by blood — and is forced to pass as one of the ruling Silver elite. The political plotting and the question of who to trust echo Alina's court intrigue.", genre: 'fantasy' },
      { title: 'Serpent & Dove', author: 'Shelby Mahurin', why: "A witch hiding in a world that hunts her kind is forced to marry a witch hunter. The slow-burn forced proximity, the tension between power and vulnerability, and the lush European setting will feel immediately comfortable to Shadow and Bone fans.", genre: 'fantasy' },
      { title: 'A Deadly Education', author: 'Naomi Novik', why: "A magic school where the monsters are real and the students die if they're not careful — El, a girl with catastrophic dark powers she refuses to use, narrates with sharp wit. Novik's Scholomance trilogy is the smartest dark fantasy school story since Bardugo.", genre: 'fantasy' },
      { title: 'The Bear and the Nightingale', author: 'Katherine Arden', why: "A girl in medieval Russia who can see the spirits of her homeland — while the old ways are being suppressed by the church. Arden's Winternight trilogy is the most atmospheric Slavic fantasy in the genre, perfect for readers who loved Shadow and Bone's world-building.", genre: 'fantasy' },
    ],
  },
];

export function getBooksLike(slug: string): BooksLikeEntry | undefined {
  return RECOMMENDATIONS.find((r) => r.slug === slug);
}

export const ALL_BOOKS_LIKE_SLUGS = RECOMMENDATIONS.map((r) => r.slug);
