export interface SeriesDefinition {
  slug: string;
  name: string;
  shortName?: string;
  author: string;
  authorQuery: string;
  genre: string;
  description: string;
  searchTerms: string[];
}

export const SERIES: SeriesDefinition[] = [
  {
    slug: 'acotar',
    name: 'A Court of Thorns and Roses',
    shortName: 'ACOTAR',
    author: 'Sarah J. Maas',
    authorQuery: 'Sarah J. Maas',
    genre: 'fantasy',
    description:
      'A Court of Thorns and Roses (ACOTAR) is the bestselling romantic fantasy series by Sarah J. Maas, following Feyre Archeron into a dangerous world of fae courts, ancient magic, and forbidden love. Spanning six books including A Court of Silver Flames and A Court of Frost and Starlight, ACOTAR has defined a generation of fantasy readers.',
    searchTerms: [
      'A Court of Thorns and Roses Sarah J. Maas',
      'ACOTAR new book',
      'Sarah J. Maas fantasy novel 2026',
      'Sarah J. Maas fantasy novel 2027',
    ],
  },
  {
    slug: 'throne-of-glass',
    name: 'Throne of Glass',
    shortName: 'ToG',
    author: 'Sarah J. Maas',
    authorQuery: 'Sarah J. Maas',
    genre: 'fantasy',
    description:
      'Throne of Glass (ToG) is the epic fantasy series by Sarah J. Maas following Celaena Sardothien, a legendary assassin navigating kingdoms, magic, and war. Spanning eight books from Throne of Glass to Kingdom of the Wicked, ToG launched Sarah J. Maas as a dominant force in fantasy fiction.',
    searchTerms: [
      'Throne of Glass Sarah J. Maas',
      'Celaena Sardothien new book',
    ],
  },
  {
    slug: 'crescent-city',
    name: 'Crescent City',
    author: 'Sarah J. Maas',
    authorQuery: 'Sarah J. Maas',
    genre: 'fantasy',
    description:
      'Crescent City is the urban fantasy series by Sarah J. Maas set in the city of Lunathion, blending fae mythology with a neon-lit contemporary world. House of Earth and Blood, House of Sky and Breath, and House of Flame and Shadow deliver high-stakes action, complex romance, and a richly layered world that intersects with ACOTAR and ToG.',
    searchTerms: [
      'Crescent City Sarah J. Maas',
      'House of Earth and Blood sequel',
      'Sarah J. Maas House of new book',
    ],
  },
  {
    slug: 'a-song-of-ice-and-fire',
    name: 'A Song of Ice and Fire',
    shortName: 'GoT',
    author: 'George R.R. Martin',
    authorQuery: 'George R.R. Martin',
    genre: 'fantasy',
    description:
      "A Song of Ice and Fire (GoT) is George R.R. Martin's landmark epic fantasy series and the source material for HBO's Game of Thrones. Millions of fans worldwide await The Winds of Winter — the long-anticipated sixth book following A Dance with Dragons (2011) — and the eventual final volume, A Dream of Spring.",
    searchTerms: [
      'George R.R. Martin Winds of Winter',
      'A Song of Ice and Fire new book',
      'George R.R. Martin new novel',
      'Winds of Winter release date',
    ],
  },
  {
    slug: 'fourth-wing',
    name: 'Fourth Wing',
    shortName: 'Empyrean',
    author: 'Rebecca Yarros',
    authorQuery: 'Rebecca Yarros',
    genre: 'fantasy',
    description:
      'Fourth Wing and Iron Flame launched Rebecca Yarros\'s Empyrean series into a worldwide phenomenon. Set in a military dragon-riding academy, the series blends pulse-pounding action with enemies-to-lovers romance. Fans eagerly await the next installments in this record-breaking fantasy saga.',
    searchTerms: [
      'Fourth Wing Rebecca Yarros',
      'Empyrean series Rebecca Yarros new book',
      'Iron Flame sequel Rebecca Yarros',
      'Rebecca Yarros new novel 2026',
    ],
  },
  {
    slug: 'colleen-hoover',
    name: 'Colleen Hoover',
    shortName: 'CoHo',
    author: 'Colleen Hoover',
    authorQuery: 'Colleen Hoover',
    genre: 'romance',
    description:
      "Colleen Hoover (CoHo) is the #1 New York Times bestselling author whose emotionally gripping romance and new adult fiction has taken the world by storm. From Ugly Love and It Ends with Us to Reminders of Him and Confess, CoHo's books dominate bestseller lists and BookTok alike.",
    searchTerms: [
      'Colleen Hoover new novel 2026',
      'Colleen Hoover romance book',
      'Colleen Hoover 2027',
    ],
  },
  {
    slug: 'mistborn',
    name: 'Mistborn',
    author: 'Brandon Sanderson',
    authorQuery: 'Brandon Sanderson',
    genre: 'fantasy',
    description:
      "Mistborn is Brandon Sanderson's beloved fantasy series featuring a unique magic system built on ingesting metals. Spanning multiple eras — from the original trilogy to the Wax & Wayne books and the upcoming Era 3 — Mistborn is the crown jewel of Sanderson's vast Cosmere universe.",
    searchTerms: [
      'Mistborn Brandon Sanderson new book',
      'Brandon Sanderson Mistborn Era 3',
      'Brandon Sanderson Cosmere 2026',
    ],
  },
  {
    slug: 'stormlight-archive',
    name: 'The Stormlight Archive',
    author: 'Brandon Sanderson',
    authorQuery: 'Brandon Sanderson',
    genre: 'fantasy',
    description:
      "The Stormlight Archive is Brandon Sanderson's magnum opus — a sprawling 10-book epic fantasy set on the storm-wracked world of Roshar. Wind and Truth (Book 5) concluded the first arc, and the next five books will follow a new generation of characters in a transformed world. Stormlight is essential reading for any serious fantasy fan.",
    searchTerms: [
      'Stormlight Archive Brandon Sanderson',
      'Brandon Sanderson Wind and Truth sequel',
      'Stormlight Archive book 6',
    ],
  },
  {
    slug: 'six-of-crows',
    name: 'Six of Crows',
    shortName: 'Grishaverse',
    author: 'Leigh Bardugo',
    authorQuery: 'Leigh Bardugo',
    genre: 'fantasy',
    description:
      "Six of Crows and Crooked Kingdom by Leigh Bardugo are the crown jewels of the Grishaverse — a high-stakes heist duology set in a city of crime and power. Combined with the Shadow and Bone trilogy and King of Scars, Leigh Bardugo has built one of the most beloved fantasy universes in modern fiction, now also a Netflix series.",
    searchTerms: [
      'Leigh Bardugo new book',
      'Six of Crows sequel Leigh Bardugo',
      'Grishaverse new novel 2026',
      'King of Scars sequel',
    ],
  },
  {
    slug: 'shadowhunters',
    name: 'The Shadowhunter Chronicles',
    shortName: 'Shadowhunters',
    author: 'Cassandra Clare',
    authorQuery: 'Cassandra Clare',
    genre: 'fantasy',
    description:
      "Cassandra Clare's Shadowhunter Chronicles is one of the best-selling YA fantasy series of all time, following Clary Fray and the Nephilim who hunt demons in a hidden magical world. Spanning The Mortal Instruments, The Infernal Devices, The Dark Artifices, and multiple spin-offs, the Shadowhunter universe shows no signs of slowing down.",
    searchTerms: [
      'Cassandra Clare new book',
      'Shadowhunters new novel 2026',
      'Mortal Instruments Cassandra Clare sequel',
      'Cassandra Clare Shadowhunter Chronicles 2027',
    ],
  },
  {
    slug: 'percy-jackson',
    name: 'Percy Jackson & The Olympians',
    shortName: 'Percy Jackson',
    author: 'Rick Riordan',
    authorQuery: 'Rick Riordan',
    genre: 'fantasy',
    description:
      "Rick Riordan's Percy Jackson & The Olympians redefined middle-grade and YA fantasy, spawning the Heroes of Olympus, The Kane Chronicles, Magnus Chase, and The Trials of Apollo. With a hit Disney+ adaptation and a devoted multigenerational fanbase, Riordan's mythological worlds remain must-reads — and new stories keep arriving.",
    searchTerms: [
      'Rick Riordan new book',
      'Percy Jackson new novel 2026',
      'Heroes of Olympus Rick Riordan sequel',
      'Rick Riordan mythology book 2027',
    ],
  },
  {
    slug: 'outlander',
    name: 'Outlander',
    author: 'Diana Gabaldon',
    authorQuery: 'Diana Gabaldon',
    genre: 'fiction',
    description:
      "Diana Gabaldon's Outlander series is a sweeping historical epic blending time travel, romance, and adventure across 18th-century Scotland. Nine novels deep — from Outlander to Go Tell the Bees That I Am Gone — the series has captivated millions of readers and inspired a long-running Starz TV series. Fans eagerly await Book 9 and beyond.",
    searchTerms: [
      'Diana Gabaldon new book',
      'Outlander new novel 2026',
      'Diana Gabaldon Outlander Book 9',
      'Outlander sequel Diana Gabaldon',
    ],
  },
  {
    slug: 'folk-of-the-air',
    name: 'The Folk of the Air',
    author: 'Holly Black',
    authorQuery: 'Holly Black',
    genre: 'fantasy',
    description:
      "Holly Black's The Folk of the Air trilogy — The Cruel Prince, The Wicked King, and The Queen of Nothing — is dark, addictive fae fantasy at its finest. Jude Duarte's ruthless rise through the treacherous courts of Faerie captivated a generation of readers. Holly Black continues expanding her fae universe with companion stories and new projects.",
    searchTerms: [
      'Holly Black new book',
      'Folk of the Air Holly Black sequel',
      'Holly Black fae novel 2026',
      'Cruel Prince sequel Holly Black',
    ],
  },
  {
    slug: 'shades-of-magic',
    name: 'Shades of Magic',
    shortName: 'V.E. Schwab',
    author: 'V.E. Schwab',
    authorQuery: 'V.E. Schwab',
    genre: 'fantasy',
    description:
      "V.E. Schwab's Shades of Magic trilogy — A Darker Shade of Magic, A Gathering of Shadows, A Conjuring of Light — follows a rare magician who can travel between parallel Londons. Schwab is also the author of the Villains duology (Vicious, Vengeful) and The Invisible Life of Addie LaRue, a modern literary fantasy phenomenon.",
    searchTerms: [
      'V.E. Schwab new book',
      'Shades of Magic V.E. Schwab sequel',
      'Victoria Schwab new novel 2026',
      'V.E. Schwab fantasy book 2027',
    ],
  },
  {
    slug: 'red-rising',
    name: 'Red Rising',
    author: 'Pierce Brown',
    authorQuery: 'Pierce Brown',
    genre: 'sci-fi',
    description:
      "Pierce Brown's Red Rising saga is a brutal, brilliantly plotted sci-fi epic set in a future where humanity has colonized the solar system under a rigid color-coded caste system. Beginning with Red Rising and continuing through six books to Light Bringer and Red God, the series blends the scope of Game of Thrones with the urgency of The Hunger Games.",
    searchTerms: [
      'Pierce Brown new book',
      'Red Rising sequel Pierce Brown',
      'Pierce Brown Red God 2026',
      'Red Rising saga new novel',
    ],
  },
  {
    slug: 'emily-henry',
    name: 'Emily Henry',
    author: 'Emily Henry',
    authorQuery: 'Emily Henry',
    genre: 'romance',
    description:
      "Emily Henry is the #1 New York Times bestselling author of witty, emotionally resonant romance novels including Beach Read, People We Meet on Vacation, Book Lovers, Happy Place, and Funny Story. Known for smart heroines and slow-burn tension, Henry has become the defining voice of the modern literary romance genre.",
    searchTerms: [
      'Emily Henry new book',
      'Emily Henry romance novel 2026',
      'Emily Henry new novel 2027',
      'Emily Henry upcoming book',
    ],
  },
  {
    slug: 'taylor-jenkins-reid',
    name: 'Taylor Jenkins Reid',
    author: 'Taylor Jenkins Reid',
    authorQuery: 'Taylor Jenkins Reid',
    genre: 'fiction',
    description:
      "Taylor Jenkins Reid writes sweeping, character-driven fiction that captures the texture of fame, love, and ambition across decades. The author of The Seven Husbands of Evelyn Hugo, Daisy Jones & The Six, Malibu Rising, and Carrie Soto Is Back, Reid has established herself as one of the most essential voices in contemporary fiction.",
    searchTerms: [
      'Taylor Jenkins Reid new book',
      'Taylor Jenkins Reid novel 2026',
      'Taylor Jenkins Reid upcoming 2027',
      'Evelyn Hugo sequel Taylor Jenkins Reid',
    ],
  },
  {
    slug: 'blood-and-ash',
    name: 'Blood and Ash',
    shortName: 'Blood & Ash',
    author: 'Jennifer L. Armentrout',
    authorQuery: 'Jennifer L. Armentrout',
    genre: 'fantasy',
    description:
      "Jennifer L. Armentrout's Blood and Ash series is a sweeping romantic fantasy following Poppy, a Maiden chosen by the gods, whose world unravels when she meets the guard Hawke. Beginning with From Blood and Ash and continuing through six books, the series blends epic world-building, passionate romance, and shocking plot twists. Armentrout has become one of the most prolific bestselling authors in romantic fantasy.",
    searchTerms: [
      'Jennifer L. Armentrout new book',
      'From Blood and Ash sequel',
      'Blood and Ash new book 2026',
      'Jennifer Armentrout upcoming novel',
      'From Blood and Ash reading order',
    ],
  },
  {
    slug: 'inheritance-games',
    name: 'The Inheritance Games',
    shortName: 'Inheritance Games',
    author: 'Jennifer Lynn Barnes',
    authorQuery: 'Jennifer Lynn Barnes',
    genre: 'thriller',
    description:
      "Jennifer Lynn Barnes's The Inheritance Games series is a compulsively readable YA mystery following Avery Grambs, who inherits the fortune of a billionaire she's never met — and gets entangled with his four grandsons, the Hawthorne brothers. Spanning The Inheritance Games, The Hawthorne Legacy, The Final Gambit, and The Brothers Hawthorne, with The Grandest Game launching a spinoff, the series has become a YA phenomenon.",
    searchTerms: [
      'Jennifer Lynn Barnes new book',
      'Inheritance Games sequel',
      'The Grandest Game Jennifer Lynn Barnes',
      'Inheritance Games reading order',
      'Hawthorne brothers next book',
    ],
  },
  {
    slug: 'bridgerton',
    name: 'Bridgerton',
    shortName: 'Bridgerton',
    author: 'Julia Quinn',
    authorQuery: 'Julia Quinn',
    genre: 'romance',
    description:
      "Julia Quinn's Bridgerton series is the beloved Regency romance saga following the eight Bridgerton siblings — Daphne, Anthony, Benedict, Colin, Eloise, Francesca, Hyacinth, and Gregory — as they each find love in London's glittering ton. The Netflix adaptation by Shonda Rhimes turned the series into a global phenomenon, drawing millions of new readers to Quinn's witty, swoony prose.",
    searchTerms: [
      'Julia Quinn new book',
      'Bridgerton book series order',
      'Julia Quinn romance novel 2026',
      'Bridgerton series reading order',
      'Julia Quinn upcoming book',
    ],
  },
  {
    slug: 'kingkiller-chronicle',
    name: 'The Kingkiller Chronicle',
    shortName: 'Kingkiller',
    author: 'Patrick Rothfuss',
    authorQuery: 'Patrick Rothfuss',
    genre: 'fantasy',
    description:
      "Patrick Rothfuss's Kingkiller Chronicle is one of the most celebrated fantasy series ever written, following the legendary Kvothe as he recounts his extraordinary life in The Name of the Wind and The Wise Man's Fear. Fans worldwide have waited over a decade for the concluding volume, The Doors of Stone — widely regarded as the most anticipated book in fantasy.",
    searchTerms: [
      'Patrick Rothfuss new book',
      'Doors of Stone release date',
      'Kingkiller Chronicle book 3',
      'Patrick Rothfuss Doors of Stone 2026',
      'Name of the Wind sequel Patrick Rothfuss',
    ],
  },
  {
    slug: 'the-witcher',
    name: 'The Witcher',
    shortName: 'Witcher',
    author: 'Andrzej Sapkowski',
    authorQuery: 'Andrzej Sapkowski',
    genre: 'fantasy',
    description:
      "Andrzej Sapkowski's The Witcher saga follows Geralt of Rivia, a professional monster hunter in a brutal, morally ambiguous fantasy world. Beginning with short story collections The Last Wish and Sword of Destiny, the saga continues through five novels — Blood of Elves, Time of Contempt, Baptism of Fire, Tower of the Swallow, and Lady of the Lake — as Geralt searches for Ciri, his adopted daughter. The Witcher became a global phenomenon through CD Projekt Red's acclaimed video games and a popular Netflix series.",
    searchTerms: [
      'Witcher reading order',
      'Andrzej Sapkowski new book',
      'Witcher book series order',
      'Witcher books before games',
      'Geralt of Rivia book series',
    ],
  },
  {
    slug: 'twisted',
    name: 'Twisted Series',
    shortName: 'Twisted',
    author: 'Ana Huang',
    authorQuery: 'Ana Huang',
    genre: 'romance',
    description:
      "Ana Huang's Twisted Series is a smoldering contemporary romance saga featuring wealthy, morally grey alpha heroes and the bold women who challenge them. Each book in the series can be read as a standalone with its own HEA, while interconnected characters and a shared world reward readers who start from the beginning. The series became a BookTok phenomenon, with millions of copies sold worldwide.",
    searchTerms: [
      'Ana Huang new book',
      'Twisted series reading order',
      'Ana Huang romance novel 2026',
      'Twisted Love Ana Huang',
      'Ana Huang upcoming book',
    ],
  },
  {
    slug: 'shatter-me',
    name: 'Shatter Me',
    shortName: 'Shatter Me',
    author: 'Tahereh Mafi',
    authorQuery: 'Tahereh Mafi',
    genre: 'fantasy',
    description:
      "Tahereh Mafi's Shatter Me series is a lush, prose-driven YA dystopian fantasy following Juliette, a girl whose touch is lethal. The series spans three original novels (Shatter Me, Unravel Me, Ignite Me), three novellas from Warner's POV (Destroy Me, Fracture Me, Shadow Me), and three continuation novels (Restore Me, Defy Me, Imagine Me) — plus a prequel novel. Known for its poetic writing style and passionate fans, Shatter Me is one of the most beloved YA series of the past decade.",
    searchTerms: [
      'Tahereh Mafi new book',
      'Shatter Me reading order',
      'Shatter Me series next book',
      'Juliette and Warner new book',
      'Tahereh Mafi upcoming novel 2026',
    ],
  },
  {
    slug: 'atlas-six',
    name: 'The Atlas Six',
    shortName: 'Atlas Six',
    author: 'Olivie Blake',
    authorQuery: 'Olivie Blake',
    genre: 'fantasy',
    description:
      "Olivie Blake's The Atlas Six is a dark, morally complex fantasy about six magicians recruited into the Alexandrian Society — an ancient secret organization that curates the world's most powerful knowledge. Each candidate's admission requires eliminating one of their peers. Spanning three books (The Atlas Six, The Atlas Paradox, The Atlas Complex), the series is renowned for its unreliable narrators, philosophically dense prose, and compulsively readable intrigue.",
    searchTerms: [
      'Olivie Blake new book',
      'Atlas Six reading order',
      'The Atlas Complex sequel',
      'Olivie Blake upcoming novel 2026',
      'Atlas Six series order',
    ],
  },
  {
    slug: 'hunger-games',
    name: 'The Hunger Games',
    shortName: 'Hunger Games',
    author: 'Suzanne Collins',
    authorQuery: 'Suzanne Collins',
    genre: 'sci-fi',
    description:
      "Suzanne Collins' The Hunger Games is the landmark YA dystopian series set in Panem, a future North America divided into twelve districts ruled by the Capitol. The trilogy follows Katniss Everdeen — a tribute forced into televised death-matches who becomes the face of a revolution. The Ballad of Songbirds and Snakes (2020) and the forthcoming Sunrise on the Reaping (March 2026) expand the universe with Capitol president Snow's origin story and Haymitch Abernathy's Games.",
    searchTerms: [
      'Suzanne Collins new book',
      'Hunger Games new book',
      'Sunrise on the Reaping release date',
      'Hunger Games series order',
      'Hunger Games prequel',
      'Sunrise on the Reaping 2026',
    ],
  },
  {
    slug: 'wheel-of-time',
    name: 'The Wheel of Time',
    shortName: 'Wheel of Time',
    author: 'Robert Jordan',
    authorQuery: 'Robert Jordan Brandon Sanderson',
    genre: 'fantasy',
    description:
      "Robert Jordan's The Wheel of Time is one of the greatest epic fantasy series ever written — fourteen novels plus a prequel spanning over 11,000 pages of world-building, prophecy, and war. Rand al'Thor discovers he is the Dragon Reborn, destined to save the world and break it. Jordan passed away in 2007 having written eleven books; Brandon Sanderson completed the trilogy from Jordan's notes. The Amazon Prime series brought an entire new generation to the Wheel.",
    searchTerms: [
      'Robert Jordan new book',
      'Wheel of Time reading order',
      'Wheel of Time series order',
      'Wheel of Time next book',
      'Wheel of Time Amazon show',
      'WoT reading order',
    ],
  },
  {
    slug: 'poppy-war',
    name: 'The Poppy War',
    shortName: 'Poppy War',
    author: 'R.F. Kuang',
    authorQuery: 'R.F. Kuang',
    genre: 'fantasy',
    description:
      "R.F. Kuang's The Poppy War trilogy is a brutal, devastating military fantasy inspired by 20th-century Chinese history. Rin, a war orphan, tests into the most elite military school in the Nikara Empire — and discovers a shamanic power that will make her the most feared weapon in a genocidal war. Followed by Babel (2022), a standalone Oxford fantasy, and Yellowface (2023), Kuang has become one of the most important literary voices in modern speculative fiction.",
    searchTerms: [
      'R.F. Kuang new book',
      'Poppy War reading order',
      'RF Kuang new book 2026',
      'Babel R.F. Kuang',
      'R.F. Kuang upcoming novel',
      'Poppy War series next book',
    ],
  },
  {
    slug: 'dark-tower',
    name: 'The Dark Tower',
    shortName: 'Dark Tower',
    author: 'Stephen King',
    authorQuery: 'Stephen King',
    genre: 'fantasy',
    description:
      "Stephen King's The Dark Tower is his magnum opus — an eight-novel epic blending fantasy, science fiction, horror, and Western mythology. Roland Deschain, the last Gunslinger, pursues the Man in Black across a post-apocalyptic landscape toward the Dark Tower, the axis of all realities. The series spans The Gunslinger through The Wind Through the Keyhole and intersects with dozens of King's other novels, creating a vast shared universe known as the King Multiverse.",
    searchTerms: [
      'Stephen King new book',
      'Dark Tower reading order',
      'Dark Tower series order',
      'Dark Tower new book',
      'Roland Deschain new book',
      'Stephen King Dark Tower 9',
    ],
  },
  {
    slug: 'dune',
    name: 'Dune',
    shortName: 'Dune',
    author: 'Frank Herbert',
    authorQuery: 'Frank Herbert',
    genre: 'sci-fi',
    description:
      "Frank Herbert's Dune is the bestselling science fiction novel of all time — a sweeping saga of politics, ecology, religion, and destiny set on the desert planet Arrakis. The original Dune Saga spans six novels by Herbert; Brian Herbert and Kevin J. Anderson have continued the universe across many prequel and sequel novels. After the Denis Villeneuve film adaptations, Dune has introduced a new generation of readers to the spice, the Fremen, and the fate of Paul Atreides.",
    searchTerms: [
      'Dune Frank Herbert',
      'Dune reading order',
      'Dune book series order',
      'Dune 3 release date',
      'Brian Herbert Dune new book',
    ],
  },
  {
    slug: 'divergent',
    name: 'Divergent',
    shortName: 'Divergent',
    author: 'Veronica Roth',
    authorQuery: 'Veronica Roth',
    genre: 'fiction',
    description:
      "Veronica Roth's Divergent trilogy is the defining YA dystopian series of the 2010s, following Beatrice 'Tris' Prior through a Chicago divided into five factions — Dauntless, Abnegation, Erudite, Amity, and Candor. The trilogy (Divergent, Insurgent, Allegiant) plus novellas delivered one of the decade's most-read YA series, with over 35 million copies sold worldwide.",
    searchTerms: [
      'Veronica Roth new book',
      'Divergent reading order',
      'Divergent series order',
      'Divergent books in order',
    ],
  },
  {
    slug: 'vampire-academy',
    name: 'Vampire Academy',
    shortName: 'Vampire Academy',
    author: 'Richelle Mead',
    authorQuery: 'Richelle Mead',
    genre: 'romance',
    description:
      "Richelle Mead's Vampire Academy series follows Rose Hathaway, a half-vampire guardian bonded to Lissa Dragomir, a Moroi princess, through St. Vladimir's Academy and beyond. The six-book series (plus the six-book Bloodlines spinoff) defined paranormal YA romance for a generation, blending boarding school drama, forbidden love, and supernatural world-building.",
    searchTerms: [
      'Richelle Mead new book',
      'Vampire Academy reading order',
      'Vampire Academy books in order',
      'Bloodlines series order',
    ],
  },
  {
    slug: 'eragon',
    name: 'Inheritance Cycle',
    shortName: 'Eragon',
    author: 'Christopher Paolini',
    authorQuery: 'Christopher Paolini',
    genre: 'fantasy',
    description:
      "Christopher Paolini began writing Eragon at fifteen years old — the story of a farm boy who finds a dragon egg and becomes a Dragon Rider in the land of Alagaësia. The Inheritance Cycle spans four novels (Eragon, Eldest, Brisingr, Inheritance) and has sold over 35 million copies worldwide. Paolini returned to Alagaësia with the standalone novel Murtagh (2023), continuing the world with a new focus on the antihero.",
    searchTerms: [
      'Christopher Paolini new book',
      'Eragon reading order',
      'Inheritance Cycle order',
      'Christopher Paolini Murtagh',
      'Alagaësia new book',
    ],
  },
  {
    slug: 'maze-runner',
    name: 'The Maze Runner',
    shortName: 'Maze Runner',
    author: 'James Dashner',
    authorQuery: 'James Dashner',
    genre: 'fiction',
    description:
      "James Dashner's Maze Runner trilogy begins in the Glade — a community of teenage boys with no memories, enclosed by a massive stone maze that closes every night and fills with mechanical monsters called Grievers. Thomas arrives with no memory and a sense that he's seen this place before. The Maze Runner is a high-concept survival thriller that launched one of the defining YA dystopian film franchises of the 2010s.",
    searchTerms: [
      'James Dashner new book',
      'Maze Runner reading order',
      'Maze Runner series order',
      'Maze Runner books in order',
    ],
  },
  {
    slug: 'red-queen',
    name: 'Red Queen',
    shortName: 'Red Queen',
    author: 'Victoria Aveyard',
    authorQuery: 'Victoria Aveyard',
    genre: 'fiction',
    description:
      "Victoria Aveyard's Red Queen series is set in a world divided by blood — Silvers with superhuman abilities rule over Reds who serve them. Mare Barrow is Red, born without abilities, but when she discovers she has Silver-level powers nobody can explain, she's thrust into the Silver court with a fake noble identity and a dangerous secret. The Red Queen series spans 4 novels and is known for its shocking betrayal twists.",
    searchTerms: [
      'Victoria Aveyard new book',
      'Red Queen reading order',
      'Red Queen series order',
      'Red Queen books in order',
    ],
  },
  {
    slug: 'legend',
    name: 'Legend',
    shortName: 'Legend',
    author: 'Marie Lu',
    authorQuery: 'Marie Lu',
    genre: 'fiction',
    description:
      "Marie Lu's Legend trilogy is set in a future United States split between the Republic and the Colonies, where Day is the Republic's most-wanted criminal and June is its most brilliant military prodigy. When June is sent to hunt Day, what she discovers about the Republic changes everything. The trilogy is known for its dual-POV structure, kinetic pacing, and the electric relationship between its two protagonists.",
    searchTerms: [
      'Marie Lu new book',
      'Legend reading order',
      'Legend series Marie Lu',
      'Legend books in order',
    ],
  },
  {
    slug: 'selection',
    name: 'The Selection',
    shortName: 'Selection',
    author: 'Kiera Cass',
    authorQuery: 'Kiera Cass',
    genre: 'romance',
    description:
      "Kiera Cass's Selection series is set in a future America called Illea, where a prince must choose his bride from 35 girls selected from across the castes in a televised competition. America Singer didn't want to enter — but the palace, the prince, and the truth about her world will change everything. The Selection is a dystopian romance series beloved for its addictive competition premise and love triangle.",
    searchTerms: [
      'Kiera Cass new book',
      'Selection reading order',
      'Selection series order',
      'Selection books in order',
    ],
  },
  {
    slug: 'harry-potter',
    name: 'Harry Potter',
    shortName: 'Harry Potter',
    author: 'J.K. Rowling',
    authorQuery: 'J.K. Rowling',
    genre: 'fantasy',
    description:
      "J.K. Rowling's Harry Potter series is the best-selling book series in history, with over 600 million copies sold worldwide. The seven novels follow Harry Potter from his discovery that he is a wizard through seven years at Hogwarts School of Witchcraft and Wizardry, culminating in his final confrontation with Lord Voldemort. The series is beloved for its richly imagined magical world, its themes of friendship, death, and love, and its ability to grow with its readers across a decade of books.",
    searchTerms: [
      'Harry Potter new book',
      'Harry Potter reading order',
      'Harry Potter books in order',
      'J.K. Rowling new book',
      'Hogwarts new book',
    ],
  },
  {
    slug: 'shadow-and-bone',
    name: 'Grishaverse (Shadow and Bone)',
    shortName: 'Shadow and Bone',
    author: 'Leigh Bardugo',
    authorQuery: 'Leigh Bardugo',
    genre: 'fantasy',
    description:
      "Leigh Bardugo's Grishaverse is one of the most expansive fantasy universes in modern YA, spanning the Shadow and Bone trilogy, the Six of Crows duology, the King of Scars duology, and multiple novellas. The Shadow and Bone trilogy follows Alina Starkov, a soldier who discovers she is a Sun Summoner — the one person who can destroy the Fold, a swath of permanent darkness across Ravka. The world combines Eastern European folklore with a military fantasy setting and has been adapted into a major Netflix series.",
    searchTerms: [
      'Leigh Bardugo new book',
      'Shadow and Bone reading order',
      'Grishaverse reading order',
      'Shadow and Bone books in order',
    ],
  },
  {
    slug: 'twilight',
    name: 'Twilight Saga',
    shortName: 'Twilight',
    author: 'Stephenie Meyer',
    authorQuery: 'Stephenie Meyer',
    genre: 'romance',
    description:
      "Stephenie Meyer's Twilight saga is a four-book paranormal romance series that launched a cultural phenomenon. The series follows Bella Swan, who moves to the rainy town of Forks, Washington, and falls in love with Edward Cullen, a vampire who has been 17 for a century. The tension between Bella's mortality and Edward's immortality, and the rival claim of werewolf Jacob Black, drives the saga through supernatural war and a conclusion that redefined paranormal romance for a generation.",
    searchTerms: [
      'Stephenie Meyer new book',
      'Twilight reading order',
      'Twilight books in order',
      'Twilight saga order',
      'Midnight Sun Stephenie Meyer',
    ],
  },
  {
    slug: 'an-ember-in-the-ashes',
    name: 'An Ember in the Ashes',
    shortName: 'Ember in the Ashes',
    author: 'Sabaa Tahir',
    authorQuery: 'Sabaa Tahir',
    genre: 'fantasy',
    description:
      "Sabaa Tahir's An Ember in the Ashes series is a four-book fantasy saga set in a Roman-inspired empire where Scholar slaves serve the Martial regime. The series follows two protagonists — Laia, a Scholar girl who goes undercover as a slave to save her brother, and Elias, the empire's greatest soldier who wants nothing more than to be free — as their paths collide and the revolution they never meant to start catches up with them. Known for its brutal world-building, dual-POV structure, and exceptional emotional depth.",
    searchTerms: [
      'Sabaa Tahir new book',
      'Ember in the Ashes reading order',
      'An Ember in the Ashes books in order',
      'Sabaa Tahir series order',
    ],
  },
  {
    slug: 'scythe',
    name: 'Arc of a Scythe',
    shortName: 'Scythe',
    author: 'Neal Shusterman',
    authorQuery: 'Neal Shusterman',
    genre: 'sci-fi',
    description:
      "Neal Shusterman's Arc of a Scythe trilogy is set in a post-mortal world where disease and war have been eliminated by a benevolent AI called the Thunderhead, and an order of Scythes administers the only remaining death to control population. Two teenagers are apprenticed to a Scythe in Book 1 and discover the institution is being corrupted from within. The series is a philosophical YA thriller that asks what the value of human life is when it has been stripped of natural death — and what happens when the people who decide who dies gain absolute power.",
    searchTerms: [
      'Neal Shusterman new book',
      'Scythe reading order',
      'Arc of a Scythe order',
      'Scythe books in order',
    ],
  },
  {
    slug: 'the-giver',
    name: 'The Giver Quartet',
    shortName: 'The Giver',
    author: 'Lois Lowry',
    authorQuery: 'Lois Lowry',
    genre: 'fiction',
    description:
      "Lois Lowry's The Giver (1993) is one of the most widely assigned novels in American schools — a slim, devastating story about a twelve-year-old boy named Jonas who lives in a Community of enforced Sameness, where suffering, color, and memory have all been eliminated. When Jonas is chosen as the Receiver of Memory, he inherits all the pain, joy, and complexity his community has surrendered. The book won the 1994 Newbery Medal and has never gone out of print. Three companion novels (Gathering Blue, Messenger, Son) expand the world across different communities.",
    searchTerms: [
      'Lois Lowry new book',
      'The Giver reading order',
      'Giver Quartet order',
      'The Giver books in order',
    ],
  },
  {
    slug: 'unwind',
    name: 'Unwind Dystology',
    shortName: 'Unwind',
    author: 'Neal Shusterman',
    authorQuery: 'Neal Shusterman',
    genre: 'sci-fi',
    description:
      "Neal Shusterman's Unwind Dystology is set in a future America where the Second Civil War ended with the Bill of Life — abortion is illegal, but parents can retroactively 'unwind' a teenager aged 13 to 18, having them taken to harvest camps where their body parts are divided and donated to others. The series begins with three teenagers who escape their unwinding and discover how deep the system goes. Unwind is known for the most disturbing single chapter in YA fiction and a moral architecture that refuses easy answers.",
    searchTerms: [
      'Neal Shusterman Unwind',
      'Unwind reading order',
      'Unwind books in order',
      'Unwind series order',
    ],
  },
  {
    slug: 'handmaids-tale',
    name: "The Handmaid's Tale",
    shortName: "Handmaid's Tale",
    author: 'Margaret Atwood',
    authorQuery: 'Margaret Atwood',
    genre: 'fiction',
    description:
      "Margaret Atwood's The Handmaid's Tale (1985) is the defining dystopian novel of the 20th century — a speculative fiction about Offred, a handmaid in the theocratic Republic of Gilead, where fertile women are forced to bear children for the ruling class. The novel's influence has only grown since the 2017 Hulu adaptation starring Elisabeth Moss. The Testaments (2019) is a direct sequel told from three new perspectives, set 15 years after the original, and won the Booker Prize.",
    searchTerms: [
      'Margaret Atwood new book',
      "Handmaid's Tale reading order",
      "Handmaid's Tale books in order",
      'The Testaments reading order',
    ],
  },
  {
    slug: 'children-of-blood-and-bone',
    name: 'Legacy of Orïsha',
    shortName: 'Blood and Bone',
    author: 'Tomi Adeyemi',
    authorQuery: 'Tomi Adeyemi',
    genre: 'fantasy',
    description:
      "Tomi Adeyemi's Legacy of Orïsha series is a West African-inspired epic fantasy set in a Nigeria where magic existed until a king ordered all Maji exterminated. Seventeen years later, Zélie Adebola discovers a scroll that could restore magic — if she can survive long enough to use it. Children of Blood and Bone became a #1 New York Times bestseller before it was published and sparked a bidding war for film rights. The series draws on Yoruba mythology to create a richly textured world that feels unlike anything else in YA fantasy.",
    searchTerms: [
      'Tomi Adeyemi new book',
      'Children of Blood and Bone reading order',
      'Legacy of Orïsha order',
      'Tomi Adeyemi next book',
    ],
  },
  {
    slug: 'matched',
    name: 'Matched Trilogy',
    shortName: 'Matched',
    author: 'Ally Condie',
    authorQuery: 'Ally Condie',
    genre: 'fiction',
    description:
      "Ally Condie's Matched trilogy is set in the Society — a future civilization that controls every aspect of citizens' lives, including who they love. Cassia Reyes has always trusted the Society's Matching system, which pairs citizens with their ideal lifelong partner. But when Cassia's Match data shows two faces — her best friend Xander and the mysterious Ky Markham — she begins to question the Society's control for the first time. The trilogy launched alongside The Hunger Games and Divergent as one of the defining YA dystopian series of the early 2010s.",
    searchTerms: [
      'Ally Condie new book',
      'Matched reading order',
      'Matched trilogy books in order',
      'Matched series order',
    ],
  },
  {
    slug: 'three-dark-crowns',
    name: 'Three Dark Crowns',
    shortName: 'Three Dark Crowns',
    author: 'Kendare Blake',
    authorQuery: 'Kendare Blake',
    genre: 'fantasy',
    description:
      "Kendare Blake's Three Dark Crowns series is set on the island of Fennbirn, where every generation three triplet queens are born — each with a different power — and they must fight each other to the death to claim the crown. Katharine is the poisoner, immune to all poisons; Mirabella commands the elements; Arsinoe has a wild nature power. As the Quickening approaches, alliances form, betrayals multiply, and the island's darkest secrets surface. The four-book series is one of the most inventive dark YA fantasy series of the 2010s.",
    searchTerms: [
      'Kendare Blake new book',
      'Three Dark Crowns reading order',
      'Three Dark Crowns series order',
      'Three Dark Crowns books in order',
    ],
  },
  {
    slug: 'first-law',
    name: 'First Law World',
    shortName: 'First Law',
    author: 'Joe Abercrombie',
    authorQuery: 'Joe Abercrombie',
    genre: 'fantasy',
    description:
      "Joe Abercrombie's First Law World is a grimdark fantasy universe that began with the First Law Trilogy (The Blade Itself, Before They Are Hanged, Last Argument of Kings) and has expanded into six additional novels. The original trilogy follows three morally compromised protagonists — a barbarian trying to leave his violent past, a torturer who was once a great swordsman, and a vain soldier who thinks he's the hero — across a continent-spanning war orchestrated by the First of the Magi. Abercrombie is known for his dark humor, his subversion of fantasy heroism, and his endings, which consistently refuse to be satisfying in the ways fantasy endings usually are.",
    searchTerms: [
      'Joe Abercrombie new book',
      'First Law reading order',
      'First Law trilogy order',
      'Blade Itself reading order',
    ],
  },
  {
    slug: 'carry-on',
    name: 'Simon Snow Trilogy',
    shortName: 'Carry On',
    author: 'Rainbow Rowell',
    authorQuery: 'Rainbow Rowell',
    genre: 'fantasy',
    description:
      "Rainbow Rowell's Simon Snow trilogy reimagines the chosen-hero-at-magical-school genre through a YA fantasy lens — and specifically through a same-sex romance between Simon Snow, the chosen one who doesn't quite fit the prophecy, and Baz, his vampire roommate who Simon has always assumed wants to kill him. The trilogy began with Carry On (2015), which originated as a fanfiction-within-fanfiction in Rowell's novel Fangirl. The series is known for its warm humor, its deep affection for fantasy genre conventions, and its central love story.",
    searchTerms: [
      'Rainbow Rowell new book',
      'Carry On reading order',
      'Simon Snow books in order',
      'Wayward Son reading order',
    ],
  },
  {
    slug: 'shiver',
    name: 'Wolves of Mercy Falls',
    shortName: 'Shiver',
    author: 'Maggie Stiefvater',
    authorQuery: 'Maggie Stiefvater',
    genre: 'romance',
    description:
      "Maggie Stiefvater's Wolves of Mercy Falls trilogy is a YA paranormal romance about Grace Brisbane, who has been fascinated by the yellow-eyed wolves behind her house since one saved her life as a child, and Sam Roth, the wolf in question — who shifts between human and wolf form based on temperature, becoming wolf in cold weather and human in warmth. As Sam ages, he spends more and more time as wolf; their romance is shadowed by the certainty that he will eventually stop returning. The trilogy is known for its lyrical prose and its bittersweet romance.",
    searchTerms: [
      'Maggie Stiefvater new book',
      'Shiver reading order',
      'Wolves of Mercy Falls books in order',
      'Shiver series order',
    ],
  },
  {
    slug: 'daughter-of-smoke-and-bone',
    name: 'Daughter of Smoke and Bone',
    shortName: 'Smoke & Bone',
    author: 'Laini Taylor',
    authorQuery: 'Laini Taylor',
    genre: 'fantasy',
    description:
      "Laini Taylor's Daughter of Smoke and Bone trilogy follows Karou, a teenage art student in Prague with naturally blue hair who was raised by a family of chimera — supernatural beings who collect teeth and grant wishes. When Karou's world collides with a war between angels and demons she was never supposed to know about, she discovers the truth of who she really is. The trilogy moves between modern Prague and Eretz, a fantasy world where the angel-chimera war has raged for millennia. Taylor's prose is among the most lush and literary in YA fantasy, and the series has a devoted cult following.",
    searchTerms: [
      'Laini Taylor new book',
      'Daughter of Smoke and Bone reading order',
      'Days of Blood and Starlight order',
      'Smoke and Bone trilogy order',
    ],
  },
  {
    slug: 'long-way-to-a-small-angry-planet',
    name: 'Wayfarers',
    shortName: 'Wayfarers',
    author: 'Becky Chambers',
    authorQuery: 'Becky Chambers',
    genre: 'sci-fi',
    description:
      "Becky Chambers's Wayfarers series is a loosely connected science fiction series set in a universe where humanity has traveled to the stars and joined a multi-species interstellar community. Each book follows a different cast of characters in the same universe, emphasizing relationships, ethics, and the question of what home means across the galaxy. The series is known for its warmth, its diverse cast of species and genders, and its focus on the ordinary lives of people in an extraordinary setting. The Long Way to a Small, Angry Planet (2014) won the Alex Award; A Psalm for the Wild-Built (also by Chambers, though in a different universe) won the Hugo Award.",
    searchTerms: [
      'Becky Chambers new book',
      'Wayfarers reading order',
      'Long Way Small Angry Planet sequel',
      'Becky Chambers books in order',
    ],
  },
  {
    slug: 'scorpio-races',
    name: 'The Scorpio Races',
    shortName: 'Scorpio Races',
    author: 'Maggie Stiefvater',
    authorQuery: 'Maggie Stiefvater',
    genre: 'fantasy',
    description:
      "Maggie Stiefvater's The Scorpio Races (2011) is a standalone novel set on the fictional island of Thisby, where every November water horses — capaill uisce — emerge from the Atlantic and the fastest riders in the world race them along the beach. The race kills multiple riders every year. Sean Kendrick has won four times; Puck Connolly will be the first woman to enter. The novel is a Newbery Honor book and is widely considered one of Stiefvater's finest standalone works. It draws on Celtic mythology around water horses and is completely unrelated to the Raven Cycle.",
    searchTerms: [
      'Maggie Stiefvater new book',
      'Scorpio Races sequel',
      'is Scorpio Races a series',
      'Scorpio Races reading order',
    ],
  },
  {
    slug: 'caraval',
    name: 'Caraval Trilogy',
    shortName: 'Caraval',
    author: 'Stephanie Garber',
    authorQuery: 'Stephanie Garber',
    genre: 'fantasy',
    description:
      "Stephanie Garber's Caraval trilogy is set in a world dominated by the mysterious Dragna family and the legendary performance called Caraval — a magical game played by a master called Legend, where participants must find what's hidden before the game ends, and where nothing is entirely what it seems. The trilogy follows two sisters, Scarlett and Tella, across three games. Garber's world is known for its lush, theatrical atmosphere, its unreliable-reality structure, and its morally complex male leads. She also wrote Once Upon a Broken Heart, a separate series in the same world.",
    searchTerms: [
      'Stephanie Garber new book',
      'Caraval reading order',
      'Caraval series order',
      'Caraval books in order',
    ],
  },
  {
    slug: 'strange-the-dreamer',
    name: 'Strange the Dreamer',
    shortName: 'Strange the Dreamer',
    author: 'Laini Taylor',
    authorQuery: 'Laini Taylor',
    genre: 'fantasy',
    description:
      "Laini Taylor's Strange the Dreamer duology follows Lazlo Strange, an orphan librarian obsessed with a city called Weep that has been erased from all maps and all memory. When a mysterious expedition passes through his city recruiting people to travel to Weep, Lazlo joins it. There he discovers the city is ruled by titanic metal hands floating in the sky and a population of godspawn — the half-human children of dead gods — including Sarai, a girl who can walk into human dreams. Taylor is known for her lush, distinctive prose style and for the Daughter of Smoke and Bone trilogy.",
    searchTerms: [
      'Laini Taylor new book',
      'Strange the Dreamer reading order',
      'Strange the Dreamer sequel',
      'Muse of Nightmares order',
    ],
  },
  {
    slug: 'legends-and-lattes',
    name: 'Legends & Lattes',
    shortName: 'Legends & Lattes',
    author: 'Travis Baldree',
    authorQuery: 'Travis Baldree',
    genre: 'fantasy',
    description:
      "Travis Baldree's Legends & Lattes (2022) is a cozy fantasy novel following Viv, an orc barbarian who retires from a life of adventuring to open the first coffee shop in the city of Thune — a city that has never heard of coffee and doesn't know if it wants any. The book is widely cited as one of the founding texts of the cozy fantasy genre alongside The House in the Cerulean Sea. Baldree originally self-published the novel before it was acquired by Tor and became a bestseller, winning the Goodreads Choice Award for both fantasy and romance. A prequel, Bookshops & Bonedust (2023), follows a younger Viv fifteen years earlier.",
    searchTerms: [
      'Travis Baldree new book',
      'Legends and Lattes sequel',
      'Legends and Lattes reading order',
      'Bookshops and Bonedust order',
    ],
  },
  {
    slug: 'circe',
    name: 'Circe',
    shortName: 'Circe',
    author: 'Madeline Miller',
    authorQuery: 'Madeline Miller',
    genre: 'fantasy',
    description:
      "Madeline Miller's Circe (2018) is a standalone literary fantasy novel retelling the life of the witch from Greek mythology — the daughter of the sun god Helios who is exiled to the island of Aeaea after discovering she has the power to transform both things and people. Over millennia of exile, Circe encounters Daedalus and the Minotaur, sails with the crew of the Argonauts, hosts Odysseus, and finally comes into open conflict with the gods. Miller's prose is lyrical and precise, and the novel is as interested in what the myths say about power, gender, and divinity as it is in retelling them. Circe won the Goodreads Choice Award for Fantasy and was a New York Times bestseller.",
    searchTerms: [
      'Madeline Miller new book',
      'Circe sequel',
      'is Circe a series',
      'Circe and Song of Achilles order',
    ],
  },
  {
    slug: 'goblin-emperor',
    name: 'The Goblin Emperor',
    shortName: 'Goblin Emperor',
    author: 'Katherine Addison',
    authorQuery: 'Katherine Addison',
    genre: 'fantasy',
    description:
      "Katherine Addison's The Goblin Emperor (2014) is a standalone fantasy novel about Maia — the half-goblin, half-elf fourth son of the Emperor of the Elflands — who unexpectedly becomes Emperor when his father and three older brothers are killed in an airship accident. Raised in exile by an abusive caretaker, Maia knows nothing about court and has no allies. The novel follows his first months ruling through kindness in a court built around cruelty. The Goblin Emperor is frequently cited as one of the foundational texts of cozy fantasy. Addison also wrote The Witness for the Dead (2021) and The Grief of Stones (2022), companion novels set in the same world.",
    searchTerms: [
      'Katherine Addison new book',
      'Goblin Emperor sequel',
      'Goblin Emperor series',
      'is Goblin Emperor a standalone',
    ],
  },
  {
    slug: 'raven-cycle',
    name: 'Raven Cycle',
    shortName: 'Raven Cycle',
    author: 'Maggie Stiefvater',
    authorQuery: 'Maggie Stiefvater',
    genre: 'fantasy',
    description:
      "Maggie Stiefvater's Raven Cycle is a four-book YA fantasy series set in Henrietta, Virginia, where ley lines concentrate supernatural energy. Blue Sargent comes from a family of psychics but has no visions herself — only the ability to amplify others'. She has been told her whole life that kissing her true love will kill him. When she meets four prep school boys searching for the sleeping Welsh king Glendower along the ley lines, she becomes entangled in a quest that will cost more than any of them expected. Stiefvater's writing is distinctive — lyrical, atmospheric, and funny in the same breath — and the series has a devoted cult following.",
    searchTerms: [
      'Maggie Stiefvater new book',
      'Raven Cycle reading order',
      'Raven Boys books in order',
      'Dreamer Trilogy reading order',
    ],
  },
  {
    slug: 'piranesi',
    name: 'Piranesi',
    shortName: 'Piranesi',
    author: 'Susanna Clarke',
    authorQuery: 'Susanna Clarke',
    genre: 'fantasy',
    description:
      "Susanna Clarke's Piranesi (2020) is a standalone novel unlike anything else in contemporary fantasy. Piranesi lives alone in a vast House — a building of infinite halls and tidal hallways, every surface lined with statues, including a hall filled with stars. He keeps meticulous journals about the House's ecology. He knows of only two other people who exist. Then he finds entries in his own journals that he has no memory of writing, and begins to question who he is and how he got there. Piranesi won the Women's Prize for Fiction in 2021. It is Clarke's second novel, completely unrelated to Jonathan Strange & Mr Norrell.",
    searchTerms: [
      'Susanna Clarke new book',
      'Piranesi sequel',
      'is Piranesi a series',
      'Piranesi and Jonathan Strange',
    ],
  },
  {
    slug: 'house-in-the-cerulean-sea',
    name: 'Cerulean Chronicles',
    shortName: 'House in the Cerulean Sea',
    author: 'TJ Klune',
    authorQuery: 'TJ Klune',
    genre: 'fantasy',
    description:
      "TJ Klune's The House in the Cerulean Sea (2020) is the defining cozy fantasy novel of the early 2020s. Linus Baker works as a caseworker for the Department in Charge of Magical Youth, evaluating orphanages for dangerous magical children. When he is sent to a mysterious island orphanage — the most unusual the department has — he finds something he wasn't looking for. The novel is a gentle, funny, deeply moving love story between two men and a defense of being different. A companion novel, Somewhere Beyond the Sea (2024), continues their story.",
    searchTerms: [
      'TJ Klune new book',
      'House in the Cerulean Sea reading order',
      'House in the Cerulean Sea sequel',
      'Somewhere Beyond the Sea TJ Klune',
    ],
  },
  {
    slug: 'jonathan-strange',
    name: 'Jonathan Strange & Mr Norrell',
    shortName: 'Jonathan Strange',
    author: 'Susanna Clarke',
    authorQuery: 'Susanna Clarke',
    genre: 'fantasy',
    description:
      "Susanna Clarke's Jonathan Strange & Mr Norrell (2004) is a standalone epic fantasy of approximately 1000 pages, structured as a Victorian novel. Set in an alternate Napoleonic England where magic once existed and has been absent for centuries, it follows Mr Norrell — a reclusive scholar who has collected every book of magic in England and refuses to share them — and Jonathan Strange, a gentleman who discovers a natural gift for practical magic. Their collaboration to restore English magic during the Napoleonic Wars attracts the attention of a powerful and sinister fairy. Clarke spent ten years writing the novel, and its detailed fictional history is so complete that it won the Hugo, Locus, and World Fantasy Awards.",
    searchTerms: [
      'Susanna Clarke new book',
      'Jonathan Strange Mr Norrell sequel',
      'is Jonathan Strange a series',
      'Jonathan Strange reading order',
    ],
  },
  {
    slug: 'bear-and-the-nightingale',
    name: 'Winternight Trilogy',
    shortName: 'Bear and the Nightingale',
    author: 'Katherine Arden',
    authorQuery: 'Katherine Arden',
    genre: 'fantasy',
    description:
      "Katherine Arden's Winternight Trilogy is a historical fantasy set in medieval Russia, following Vasilisa Petrovna — a girl born able to see the old Slavic spirits that Russian Orthodox Christianity has been working to extinguish. As the church's power grows and the village neglects its protective spirits, Vasya must navigate between the human world, the Church, and the increasingly dangerous spirit world. Arden studied Russian at Middlebury College and the trilogy draws on authentic Slavic mythology and medieval Russian history. The prose is lyrical and atmospheric, the magic is treated as real and dangerous, and the world is more complex than any binary of Christianity vs. paganism suggests.",
    searchTerms: [
      'Katherine Arden new book',
      'Bear and the Nightingale reading order',
      'Winternight Trilogy order',
      'Bear and the Nightingale books in order',
    ],
  },
  {
    slug: 'a-memory-called-empire',
    name: 'Teixcalaan',
    shortName: 'Teixcalaan',
    author: 'Arkady Martine',
    authorQuery: 'Arkady Martine',
    genre: 'sci-fi',
    description:
      "Arkady Martine's Teixcalaan series is a Hugo Award–winning space opera duology following Mahit Dzmare, the ambassador from a tiny independent mining station, who arrives at the capital of the Teixcalaan empire to find that her predecessor was murdered. Mahit carries a neurological implant containing a copy of her predecessor's memories — which may be failing. The series draws on Byzantine imperial history (Martine is a Byzantine historian) and explores empire, assimilation, identity, and the appeal of belonging to something vast and beautiful. Both novels won the Hugo Award for Best Novel.",
    searchTerms: [
      'Arkady Martine new book',
      'A Memory Called Empire reading order',
      'Teixcalaan series order',
      'A Memory Called Empire sequel',
    ],
  },
  {
    slug: 'daughter-of-the-moon-goddess',
    name: 'Celestial Kingdom',
    shortName: 'Daughter of the Moon Goddess',
    author: 'Sue Lynn Tan',
    authorQuery: 'Sue Lynn Tan',
    genre: 'fantasy',
    description:
      "Sue Lynn Tan's Celestial Kingdom duology is a lyrical fantasy drawing on Chinese mythology — specifically the legend of Chang'e, the moon goddess exiled to the moon, and her daughter Xingyin. When Xingyin accidentally reveals her powers to the Celestial Emperor, she flees the moon and must make her way in the celestial realm without revealing her identity. The duology is known for its gorgeous prose, its rooting in authentic Chinese mythological tradition, and its emotional depth — a story about sacrifice, identity, and the relationship between mothers and daughters across an immortal world.",
    searchTerms: [
      'Sue Lynn Tan new book',
      'Daughter of the Moon Goddess reading order',
      'Celestial Kingdom series order',
      'Heart of the Sun Warrior reading order',
    ],
  },
  {
    slug: 'night-circus',
    name: 'The Night Circus',
    shortName: 'Night Circus',
    author: 'Erin Morgenstern',
    authorQuery: 'Erin Morgenstern',
    genre: 'fantasy',
    description:
      "Erin Morgenstern's The Night Circus (2011) is a standalone fantasy novel set in a mysterious black-and-white circus that arrives without warning and is open only at night. Inside the Cirque des Rêves, two young magicians — Celia Bowen and Marco Alisdair — are unwitting competitors in an ancient contest arranged by their teachers. They must build and maintain the circus's wonders, but they were never told the rules, or how the game ends. The Night Circus became a cult classic for its dreamlike prose, intricate world-building, and the sense that the circus itself is the true protagonist.",
    searchTerms: [
      'Erin Morgenstern new book',
      'Night Circus reading order',
      'Night Circus sequel',
      'is Night Circus a series',
    ],
  },
  {
    slug: 'city-of-brass',
    name: 'Daevabad Trilogy',
    shortName: 'City of Brass',
    author: 'S.A. Chakraborty',
    authorQuery: 'S.A. Chakraborty',
    genre: 'fantasy',
    description:
      "S.A. Chakraborty's Daevabad trilogy is set in the hidden city of Daevabad, home to six tribes of djinn who have been at war for millennia. Nahri is a young con artist in 18th-century Cairo who discovers she has real healing powers — and a hidden identity that ties her to the djinn world. When a warrior djinn named Dara accidentally summons himself while she's performing a ritual, they are both pulled to Daevabad, and into a conflict far older than either of them. The trilogy draws on Islamic mythology, djinn folklore, and the history of the medieval Islamic world.",
    searchTerms: [
      'S.A. Chakraborty new book',
      'City of Brass reading order',
      'Daevabad trilogy order',
      'City of Brass series order',
    ],
  },
  {
    slug: 'priory-of-the-orange-tree',
    name: 'The Priory of the Orange Tree',
    shortName: 'Priory of the Orange Tree',
    author: 'Samantha Shannon',
    authorQuery: 'Samantha Shannon',
    genre: 'fantasy',
    description:
      "Samantha Shannon's The Priory of the Orange Tree (2019) is a standalone epic fantasy of nearly 850 pages, set in a world divided between dragon-worshipping cultures and dragon-slaying ones. Four narrators — a queen's bodyguard, a dragon rider, a scholar, and a warrior — converge as an ancient dragon god stirs from its imprisonment beneath the sea. The novel is notable for its all-female central cast, its intricate world map (spanning three distinct civilizations), and its exploration of how mythology is constructed and weaponized by the powerful.",
    searchTerms: [
      'Samantha Shannon new book',
      'Priory of the Orange Tree sequel',
      'Priory of the Orange Tree reading order',
      'is Priory of the Orange Tree a series',
    ],
  },
  {
    slug: 'young-elites',
    name: 'The Young Elites',
    shortName: 'Young Elites',
    author: 'Marie Lu',
    authorQuery: 'Marie Lu',
    genre: 'fantasy',
    description:
      "Marie Lu's Young Elites is a dark YA fantasy trilogy about Adelina Amouteru, a survivor of the blood fever who bears marks — and discovers she has terrifying powers. Recruited by the Dagger Society, a secret group of marked rebels called Young Elites, Adelina must decide who she really is. Unlike most YA protagonists, Adelina is not a hero but a villain-in-waiting, and watching her fall is the central drama of the trilogy. Darker than Legend or Warcross, the Young Elites trilogy is Marie Lu at her most morally complex.",
    searchTerms: [
      'Marie Lu new book',
      'Young Elites reading order',
      'Young Elites books in order',
      'The Young Elites series order',
    ],
  },
  {
    slug: 'delirium',
    name: 'Delirium',
    shortName: 'Delirium',
    author: 'Lauren Oliver',
    authorQuery: 'Lauren Oliver',
    genre: 'fiction',
    description:
      "Lauren Oliver's Delirium trilogy is set in a future United States where love has been classified as a disease — Amor Deliria Nervosa — and cured at age eighteen. Lena Haloway has always believed in the cure, counting the days to her procedure, until she meets Alex and falls desperately in love ninety-five days before her appointment. The trilogy is a lyrical, romantic YA dystopia that launched alongside Matched and Divergent as part of the early-2010s wave that followed The Hunger Games. Oliver's prose is more literary than most YA contemporaries.",
    searchTerms: [
      'Lauren Oliver new book',
      'Delirium reading order',
      'Delirium trilogy books in order',
      'Delirium series Lauren Oliver',
    ],
  },
  {
    slug: 'gentleman-bastard',
    name: 'Gentleman Bastard Sequence',
    shortName: 'Gentleman Bastard',
    author: 'Scott Lynch',
    authorQuery: 'Scott Lynch',
    genre: 'fantasy',
    description:
      "Scott Lynch's Gentleman Bastard Sequence is an ongoing adult heist fantasy series set in Camorr, a city modeled on Renaissance Venice, ruled by the Capa Barsavi and his criminal network. Locke Lamora is a priest-thief leading the Gentleman Bastards, an elite crew of con artists who steal not just money but entire identities. The series is known for its intricate heist plots, Lynch's sharp wit, the bond between Locke and his best friend Jean Tannen, and the city of Camorr itself — one of the most detailed fantasy cities in modern fiction. Darker and more adult in tone than most fantasy heist fiction.",
    searchTerms: [
      'Scott Lynch new book',
      'Gentleman Bastard reading order',
      'Lies of Locke Lamora reading order',
      'Gentleman Bastard books in order',
    ],
  },
  {
    slug: 'warcross',
    name: 'Warcross',
    shortName: 'Warcross',
    author: 'Marie Lu',
    authorQuery: 'Marie Lu',
    genre: 'sci-fi',
    description:
      "Marie Lu's Warcross duology is set in a near-future world where a virtual reality game called Warcross has become the world's most popular sport and pastime, with billions of players. Emika Chen is a teenage bounty hunter who accidentally glitches into the opening ceremony of the Warcross Championships — and is immediately recruited by the game's reclusive billionaire creator Hideo Tanaka to go undercover in the tournament and find a hacker. The duology combines high-stakes action with Lu's signature dual-POV storytelling and a twisty conspiracy thriller.",
    searchTerms: [
      'Marie Lu new book',
      'Warcross reading order',
      'Warcross books in order',
      'Warcross duology order',
    ],
  },
  {
    slug: 'ariadne',
    name: 'Ariadne',
    author: 'Jennifer Saint',
    authorQuery: 'Jennifer Saint',
    genre: 'fiction',
    description:
      "Jennifer Saint's Ariadne is a standalone literary fantasy retelling the myth of Theseus and the Minotaur from the perspective of the women at its center — Ariadne and Phaedra, daughters of King Minos of Crete. Saint has since written companion standalones (Elektra, Atalanta) in the same mythological world.",
    searchTerms: [
      'Jennifer Saint new book',
      'Ariadne reading order',
      'Jennifer Saint mythology books',
    ],
  },
  {
    slug: 'stardust',
    name: 'Stardust',
    author: 'Neil Gaiman',
    authorQuery: 'Neil Gaiman',
    genre: 'fantasy',
    description:
      "Neil Gaiman's Stardust is a standalone fairy tale novel about a young man who crosses the wall into the magical land of Faerie to retrieve a fallen star for the girl he thinks he loves — and discovers that the star is a person, and that he may not know what he actually wants.",
    searchTerms: [
      'Neil Gaiman new book',
      'Stardust reading order',
      'Neil Gaiman fantasy novels',
    ],
  },
  {
    slug: 'a-psalm-for-the-wild-built',
    name: 'Monk and Robot',
    shortName: 'Monk and Robot',
    author: 'Becky Chambers',
    authorQuery: 'Becky Chambers',
    genre: 'sci-fi',
    description:
      "Becky Chambers' Monk and Robot is a gentle, philosophical cozy science fiction duology set in a world where humans have retreated to smaller, sustainable settlements after giving robots their freedom. When a robot wanders back from the wilderness to ask what humans need, the answer turns out to be harder than expected.",
    searchTerms: [
      'Becky Chambers new book',
      'Monk and Robot reading order',
      'Psalm for the Wild-Built reading order',
      'Monk and Robot series order',
    ],
  },
  {
    slug: 'rage-of-dragons',
    name: 'The Burning',
    shortName: 'The Burning',
    author: 'Evan Winter',
    authorQuery: 'Evan Winter',
    genre: 'fantasy',
    description:
      "Evan Winter's The Burning is a complete two-book African-inspired epic fantasy duology. Following Tau, a Lower Caste warrior who trains himself to become the greatest swordsman who ever lived in order to avenge his father, the series draws on Xhosa culture and Zulu history for world-building that stands apart from European-derived epic fantasy.",
    searchTerms: [
      'Evan Winter new book',
      'Rage of Dragons reading order',
      'The Burning reading order',
      'The Burning duology order',
    ],
  },
  {
    slug: 'his-dark-materials',
    name: 'His Dark Materials',
    author: 'Philip Pullman',
    authorQuery: 'Philip Pullman',
    genre: 'fantasy',
    description:
      "Philip Pullman's His Dark Materials is a complete three-book fantasy trilogy that begins as a children's adventure in an alternate Oxford where every human's soul is externalized as an animal companion, and deepens into one of the most philosophically ambitious works of speculative fiction ever written. The series follows Lyra Belacqua across multiple worlds as she becomes the figure at the center of a conflict between the forces of authority and freedom.",
    searchTerms: [
      'Philip Pullman new book',
      'His Dark Materials reading order',
      'Golden Compass reading order',
      'His Dark Materials books in order',
      'Book of Dust reading order',
    ],
  },
  {
    slug: 'the-expanse',
    name: 'The Expanse',
    author: 'James S.A. Corey',
    authorQuery: 'James S.A. Corey',
    genre: 'sci-fi',
    description:
      "James S.A. Corey's The Expanse is a complete nine-book science fiction series set 200 years in the future, when humanity has colonized the solar system and the gap between Earth, Mars, and the Belt has produced three distinct civilizations in conflict. The series is acclaimed for its hard science, political realism, and the discovery of something in the asteroid belt that changes humanity's place in the universe.",
    searchTerms: [
      'James Corey new book',
      'The Expanse reading order',
      'Expanse books in order',
      'Leviathan Wakes reading order',
      'Expanse series order',
    ],
  },
  {
    slug: 'project-hail-mary',
    name: 'Project Hail Mary',
    author: 'Andy Weir',
    authorQuery: 'Andy Weir',
    genre: 'sci-fi',
    description:
      "Andy Weir's Project Hail Mary is a standalone science fiction novel about Ryland Grace, who wakes alone on a spacecraft with no memory and must piece together the mission he has been sent on: preventing Earth's extinction. The novel is structured around Grace's memories surfacing as he works the problem — and around a first-contact encounter with the only being who can help him.",
    searchTerms: [
      'Andy Weir new book',
      'Project Hail Mary reading order',
      'Andy Weir books to read',
    ],
  },
  {
    slug: 'legendborn',
    name: 'Legendborn',
    shortName: 'Legendborn Cycle',
    author: 'Tracy Deonn',
    authorQuery: 'Tracy Deonn',
    genre: 'fantasy',
    description:
      "Tracy Deonn's Legendborn is an ongoing YA fantasy series set at the University of North Carolina at Chapel Hill, where a secret society of Arthurian legend descendants has been hiding for centuries. Bree Matthews arrives on campus and discovers her family's connection to the magical world runs deeper than she knew.",
    searchTerms: [
      'Tracy Deonn new book',
      'Legendborn reading order',
      'Legendborn Cycle books in order',
    ],
  },
  {
    slug: 'winners-curse',
    name: "The Winner's Trilogy",
    shortName: "Winner's Trilogy",
    author: 'Marie Rutkoski',
    authorQuery: 'Marie Rutkoski',
    genre: 'fantasy',
    description:
      "Marie Rutkoski's The Winner's Trilogy is a complete three-book YA fantasy series about Kestrel, a Valorian general's daughter who buys a Herrani slave and sets in motion a political and personal crisis neither of them can control. The series is notable for its portrayal of colonialism, political maneuvering, and a morally complex enemies-to-lovers romance.",
    searchTerms: [
      'Marie Rutkoski new book',
      "Winner's Curse reading order",
      "Winner's Trilogy books in order",
      "Winner's Trilogy reading order",
    ],
  },
  {
    slug: 'enders-game',
    name: "Ender's Game",
    author: 'Orson Scott Card',
    authorQuery: 'Orson Scott Card',
    genre: 'sci-fi',
    description:
      "Orson Scott Card's Ender's Game is a classic science fiction novel about Andrew 'Ender' Wiggin, a child genius trained at Battle School to command humanity's fleet against an alien species called the Formics. The novel stands alone as a complete story and is one of the most widely read science fiction novels ever published. The series continues in two parallel tracks: the Ender track (Speaker for the Dead) and the Shadow track (Ender's Shadow).",
    searchTerms: [
      "Ender's Game reading order",
      "Ender's Game series order",
      "Ender's Shadow reading order",
      'Orson Scott Card new book',
    ],
  },
  {
    slug: 'a-deadly-education',
    name: 'The Scholomance',
    shortName: 'Scholomance',
    author: 'Naomi Novik',
    authorQuery: 'Naomi Novik',
    genre: 'fantasy',
    description:
      "Naomi Novik's The Scholomance trilogy is a complete three-book YA fantasy series about a magical school that kills students for survival rather than malice. The protagonist El has a prophesied ability to destroy everything, which everyone around her assumes means she is destined to become a dark mage — a problem she is extremely tired of.",
    searchTerms: [
      'Naomi Novik new book',
      'A Deadly Education reading order',
      'Scholomance reading order',
      'Scholomance books in order',
    ],
  },
  {
    slug: 'american-gods',
    name: 'American Gods',
    author: 'Neil Gaiman',
    authorQuery: 'Neil Gaiman',
    genre: 'fantasy',
    description:
      "Neil Gaiman's American Gods is a standalone novel about Shadow Moon, who discovers that the old gods brought to America by immigrants are dying — and that a war between them and the new gods of technology and media is coming. The companion novel Anansi Boys is set in the same world but has no shared plot.",
    searchTerms: [
      'Neil Gaiman new book',
      'American Gods reading order',
      'Neil Gaiman books to read',
    ],
  },
  {
    slug: 'foundation',
    name: 'Foundation',
    author: 'Isaac Asimov',
    authorQuery: 'Isaac Asimov',
    genre: 'sci-fi',
    description:
      "Isaac Asimov's Foundation is a classic science fiction series about the fall of a galactic empire and mathematician Hari Seldon's plan to reduce the resulting dark age from 30,000 years to 1,000 years using psychohistory — a mathematical science that predicts the behavior of large populations. The original trilogy is complete in itself; Asimov later added prequels and sequels.",
    searchTerms: [
      'Foundation reading order',
      'Foundation series order',
      'Isaac Asimov new book',
      'Foundation books in order',
    ],
  },
  {
    slug: 'hyperion',
    name: 'Hyperion Cantos',
    shortName: 'Hyperion',
    author: 'Dan Simmons',
    authorQuery: 'Dan Simmons',
    genre: 'sci-fi',
    description:
      "Dan Simmons' Hyperion Cantos is a four-book science fiction series set in a future interstellar civilization on the eve of collapse. The first two books — Hyperion and The Fall of Hyperion — form a complete story structured as a Canterbury Tales-style pilgrimage in which seven characters tell their stories on the way to a dangerous world.",
    searchTerms: [
      'Dan Simmons new book',
      'Hyperion reading order',
      'Hyperion Cantos reading order',
      'Hyperion books in order',
    ],
  },
  {
    slug: 'uprooted',
    name: 'Uprooted',
    author: 'Naomi Novik',
    authorQuery: 'Naomi Novik',
    genre: 'fantasy',
    description:
      "Naomi Novik's Uprooted is a complete standalone dark fantasy novel inspired by Eastern European folklore. Agnieszka lives in a valley on the edge of a corrupted magical forest called the Wood, where the Dragon — a cold, powerful wizard — takes one girl every ten years to serve him. Agnieszka's relationship to magic, and to the Dragon, is nothing like what either of them expected.",
    searchTerms: [
      'Naomi Novik new book',
      'Uprooted reading order',
      'Uprooted Naomi Novik sequel',
    ],
  },
  {
    slug: 'recursion',
    name: 'Recursion',
    author: 'Blake Crouch',
    authorQuery: 'Blake Crouch',
    genre: 'sci-fi',
    description:
      "Blake Crouch's Recursion is a complete standalone science fiction thriller about memory, time, and what it would mean to be able to go back and change the worst moment of your life. A neuroscientist and an NYPD detective independently uncover the mechanism behind a new phenomenon called False Memory Syndrome — and discover it threatens the fabric of reality.",
    searchTerms: [
      'Blake Crouch new book',
      'Recursion reading order',
      'Blake Crouch books to read',
    ],
  },
  {
    slug: 'left-hand-of-darkness',
    name: 'The Left Hand of Darkness',
    author: 'Ursula K. Le Guin',
    authorQuery: 'Ursula K. Le Guin',
    genre: 'sci-fi',
    description:
      "Ursula K. Le Guin's The Left Hand of Darkness is a Hugo and Nebula Award-winning standalone science fiction novel about a human envoy sent to a planet where human beings are neither male nor female. Set in Le Guin's Hainish Cycle shared universe, it uses its speculative premise to examine what gender does to perception, politics, and personal relationships.",
    searchTerms: [
      'Ursula Le Guin new book',
      'Left Hand of Darkness reading order',
      'Hainish Cycle reading order',
      'Ursula Le Guin books to read',
    ],
  },
  {
    slug: 'old-mans-war',
    name: "Old Man's War",
    author: 'John Scalzi',
    authorQuery: 'John Scalzi',
    genre: 'sci-fi',
    description:
      "John Scalzi's Old Man's War series is ongoing military science fiction about retired humans who join an interstellar military in young bodies to fight for habitable planets. Known for its dark humor, fast pacing, and the moral complexity of a war humanity did not ask for but cannot stop fighting.",
    searchTerms: [
      'John Scalzi new book',
      "Old Man's War reading order",
      "Old Man's War series order",
    ],
  },
  {
    slug: 'kingdom-of-the-wicked',
    name: 'Kingdom of the Wicked',
    shortName: 'Kingdom of the Wicked',
    author: 'Kerri Maniscalco',
    authorQuery: 'Kerri Maniscalco',
    genre: 'fantasy',
    description:
      "Kerri Maniscalco's Kingdom of the Wicked is a complete three-book YA dark fantasy trilogy set in 1888 Sicily, where Emilia di Carlo summons a demon — the Prince of Wrath — to help investigate her twin sister's murder. The series combines enemies-to-lovers romance with supernatural mystery and gothic atmosphere.",
    searchTerms: [
      'Kerri Maniscalco new book',
      'Kingdom of the Wicked reading order',
      'Kingdom of the Wicked series order',
    ],
  },
  {
    slug: 'spinning-silver',
    name: 'Spinning Silver',
    author: 'Naomi Novik',
    authorQuery: 'Naomi Novik',
    genre: 'fantasy',
    description:
      "Naomi Novik's Spinning Silver is a complete standalone dark fairy tale novel drawing on Russian and Jewish folklore. When Miryem discovers she can turn silver into gold through her skill as a moneylender, the Staryk king — a being of winter — takes notice. The novel retells elements of Rumpelstiltskin with multiple POV characters in a medieval Russia-inspired world, and won the Hugo Award for Best Novel.",
    searchTerms: [
      'Naomi Novik new book',
      'Spinning Silver reading order',
      'Spinning Silver sequel',
    ],
  },
  {
    slug: 'parable-of-the-sower',
    name: 'Parable Series',
    shortName: 'Parable',
    author: 'Octavia Butler',
    authorQuery: 'Octavia Butler',
    genre: 'sci-fi',
    description:
      "Octavia Butler's Parable series is a two-book speculative fiction duology following Lauren Olamina, a Black teenager with hyperempathy, who survives the collapse of near-future California and builds a new community around a philosophy called Earthseed. The duology is considered one of the most prescient American science fiction works of the 20th century.",
    searchTerms: [
      'Octavia Butler new book',
      'Parable of the Sower reading order',
      'Parable series order',
      'Octavia Butler books to read',
    ],
  },
  {
    slug: 'station-eleven',
    name: 'Station Eleven',
    author: 'Emily St. John Mandel',
    authorQuery: 'Emily St. John Mandel',
    genre: 'fiction',
    description:
      "Emily St. John Mandel's Station Eleven is a standalone literary fiction novel set 20 years after a flu pandemic kills most of the global population, following a traveling Shakespeare company in the Great Lakes region. The novel interweaves the post-pandemic present with the night before the pandemic — when a famous actor collapses on a Toronto stage.",
    searchTerms: [
      'Emily St. John Mandel new book',
      'Station Eleven reading order',
      'Station Eleven companion books',
    ],
  },
  {
    slug: 'midnight-library',
    name: 'The Midnight Library',
    author: 'Matt Haig',
    authorQuery: 'Matt Haig',
    genre: 'fiction',
    description:
      "Matt Haig's The Midnight Library is a standalone literary fiction novel about Nora Seed, who discovers at the moment of ending her life a library between life and death where every book is a version of the life she didn't live. The novel is a meditation on regret, alternate lives, and what we actually need to be content.",
    searchTerms: [
      'Matt Haig new book',
      'Midnight Library reading order',
      'Matt Haig books to read',
    ],
  },
  {
    slug: 'kindred',
    name: 'Kindred',
    author: 'Octavia Butler',
    authorQuery: 'Octavia Butler',
    genre: 'sci-fi',
    description:
      "Octavia Butler's Kindred is a standalone science fiction novel about Dana, a Black woman living in 1976 Los Angeles who is repeatedly transported back to antebellum Maryland — where she discovers she is compelled to protect a white slaveholder's son who may be her ancestor. The novel uses time travel to place a contemporary consciousness inside the experience of American slavery.",
    searchTerms: [
      'Octavia Butler new book',
      'Kindred reading order',
      'Octavia Butler books to read',
    ],
  },
  {
    slug: 'the-road',
    name: 'The Road',
    author: 'Cormac McCarthy',
    authorQuery: 'Cormac McCarthy',
    genre: 'fiction',
    description: "Cormac McCarthy's Pulitzer Prize–winning standalone novel about a man and his young son walking south through a burned, post-apocalyptic America, carrying fire and clinging to the idea that goodness can survive catastrophe. Widely considered one of the defining American novels of the 21st century.",
    searchTerms: ['the road reading order', 'cormac mccarthy reading order', 'books like the road', 'books like cormac mccarthy', 'post-apocalyptic literary fiction', 'cormac mccarthy books'],
  },
  {
    slug: 'beloved',
    name: 'Beloved',
    author: 'Toni Morrison',
    authorQuery: 'Toni Morrison',
    genre: 'fiction',
    description: "Toni Morrison's Pulitzer Prize–winning standalone novel about Sethe, a formerly enslaved woman in 1873 Ohio who is haunted by the ghost of the daughter she killed rather than allow to be taken back into slavery. Widely considered one of the greatest American novels and a major work of 20th-century literature.",
    searchTerms: ['beloved reading order', 'toni morrison reading order', 'books like beloved', 'books like toni morrison', 'toni morrison novels', 'american slavery literature'],
  },
  {
    slug: 'underground-railroad',
    name: 'The Underground Railroad',
    author: 'Colson Whitehead',
    authorQuery: 'Colson Whitehead',
    genre: 'fiction',
    description: "Colson Whitehead's Pulitzer Prize and National Book Award–winning standalone novel about Cora, an enslaved woman who escapes on a literal underground railroad — in Whitehead's alternate history, an actual subterranean railway — and passes through different versions of American racial history in each state she crosses.",
    searchTerms: ['the underground railroad reading order', 'colson whitehead reading order', 'books like the underground railroad', 'books like colson whitehead', 'colson whitehead books', 'speculative historical fiction slavery'],
  },
  {
    slug: 'a-man-called-ove',
    name: 'A Man Called Ove',
    author: 'Fredrik Backman',
    authorQuery: 'Fredrik Backman',
    genre: 'fiction',
    description: "Fredrik Backman's bestselling standalone novel about Ove, a 59-year-old recently widowed man with rules for everything and contempt for everyone, who is planning to end his life and is repeatedly interrupted by his new neighbors. A novel about grief, community, and the specific way a person can become disconnected from the world around them.",
    searchTerms: ['a man called ove reading order', 'fredrik backman reading order', 'books like a man called ove', 'books like fredrik backman', 'fredrik backman books', 'swedish literary fiction'],
  },
  {
    slug: 'eleanor-oliphant',
    name: 'Eleanor Oliphant Is Completely Fine',
    shortName: 'Eleanor Oliphant',
    author: 'Gail Honeyman',
    authorQuery: 'Gail Honeyman',
    genre: 'fiction',
    description: "Gail Honeyman's bestselling standalone debut novel about Eleanor Oliphant, 29, whose severely regimented life of identical routines and near-total human isolation is disrupted when she becomes obsessed with a musician and befriends a coworker named Raymond. A novel about profound isolation and what it takes to break out of it.",
    searchTerms: ['eleanor oliphant is completely fine reading order', 'eleanor oliphant reading order', 'gail honeyman books', 'books like eleanor oliphant', 'books like eleanor oliphant is completely fine', 'eleanor oliphant is completely fine sequel'],
  },
  {
    slug: 'beartown',
    name: 'Beartown',
    author: 'Fredrik Backman',
    authorQuery: 'Fredrik Backman',
    genre: 'fiction',
    description: "Fredrik Backman's trilogy set in a struggling Swedish hockey town that fractures after its star player is accused of assault. More serious and emotionally demanding than Backman's other work, the trilogy follows Beartown's community across a decade as individuals reckon with who they were in the moment the town chose silence over justice.",
    searchTerms: ['beartown reading order', 'beartown series order', 'beartown trilogy order', 'fredrik backman beartown', 'beartown books in order', 'us against you beartown'],
  },
  {
    slug: 'anxious-people',
    name: 'Anxious People',
    author: 'Fredrik Backman',
    authorQuery: 'Fredrik Backman',
    genre: 'fiction',
    description: "Fredrik Backman's standalone comic-melancholy novel about eight strangers held hostage in a Stockholm apartment by an accidental bank robber. Structured as a mystery, the novel is really about the private catastrophes people carry and the accidental ways they end up saving each other.",
    searchTerms: ['anxious people reading order', 'anxious people sequel', 'fredrik backman anxious people', 'books like anxious people', 'anxious people series'],
  },
  {
    slug: 'dark-matter',
    name: 'Dark Matter',
    author: 'Blake Crouch',
    authorQuery: 'Blake Crouch',
    genre: 'sci-fi',
    description: "Blake Crouch's standalone thriller about a Chicago physicist who is abducted and wakes in a version of his life where he made different choices. A fast-paced, emotionally grounded thriller that uses quantum mechanics and many-worlds theory to examine identity, regret, and the life unlived.",
    searchTerms: ['dark matter reading order', 'blake crouch dark matter sequel', 'dark matter series', 'books like dark matter', 'blake crouch books in order'],
  },
  {
    slug: 'where-the-crawdads-sing',
    name: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    authorQuery: 'Delia Owens',
    genre: 'fiction',
    description: "Delia Owens's bestselling standalone novel about Kya Clark, the Marsh Girl, who was abandoned in the North Carolina marshes as a young child and grew up entirely alone — teaching herself to read, becoming a naturalist, surviving on what the marsh provided — and is accused of murder as an adult. A mystery, a coming-of-age story, and a natural history of the American coastal South.",
    searchTerms: ['where the crawdads sing reading order', 'where the crawdads sing sequel', 'delia owens books', 'books like where the crawdads sing', 'crawdads sing series'],
  },
  {
    slug: 'first-fifteen-lives',
    name: 'The First Fifteen Lives of Harry August',
    shortName: 'Harry August',
    author: 'Claire North',
    authorQuery: 'Claire North',
    genre: 'sci-fi',
    description: "Claire North's standalone literary science fiction novel about Harry August, a man who is reborn at the moment of his birth with full memory of all previous lives, who learns in his eleventh life that the world is ending earlier with each cycle and must find out why. A character study about identity and choice that happens to use a science fiction mechanism.",
    searchTerms: ['first fifteen lives of harry august reading order', 'harry august sequel', 'claire north books', 'books like first fifteen lives of harry august', 'harry august series'],
  },
  {
    slug: 'seven-deaths-evelyn-hardcastle',
    name: 'The 7½ Deaths of Evelyn Hardcastle',
    shortName: 'Evelyn Hardcastle',
    author: 'Stuart Turton',
    authorQuery: 'Stuart Turton',
    genre: 'fiction',
    description: "Stuart Turton's standalone puzzle-box mystery: a man must solve Evelyn Hardcastle's murder before he runs out of chances, living the same country-house day over and over in the body of a different guest each time. A love letter to Agatha Christie that uses time-loop mechanics to push the country-house mystery to its structural limits.",
    searchTerms: ['7 deaths of evelyn hardcastle reading order', 'seven deaths evelyn hardcastle sequel', 'stuart turton books', 'books like 7 deaths of evelyn hardcastle', 'evelyn hardcastle series'],
  },
  {
    slug: 'life-after-life',
    name: 'Life After Life',
    author: 'Kate Atkinson',
    authorQuery: 'Kate Atkinson',
    genre: 'fiction',
    description: "Kate Atkinson's Booker-longlisted novel about Ursula Todd, born in England in 1910, who dies and is reborn repeatedly — with no explicit memory of previous lives but a growing instinct about what to do differently. Followed by A God in Ruins (2015), a companion novel about Ursula's brother Teddy.",
    searchTerms: ['life after life reading order', 'life after life sequel', 'kate atkinson books in order', 'books like life after life', 'a god in ruins series order'],
  },
  {
    slug: 'replay',
    name: 'Replay',
    author: 'Ken Grimwood',
    authorQuery: 'Ken Grimwood',
    genre: 'sci-fi',
    description: "Ken Grimwood's World Fantasy Award–winning standalone novel about a man who dies in 1988 and wakes in his 1963 college dorm room with full memory of the life he just lived, and must live it again — and again. The foundational text of the modern time-loop novel, directly influencing Recursion, Dark Matter, The First Fifteen Lives of Harry August, and dozens of others.",
    searchTerms: ['replay ken grimwood reading order', 'replay sequel', 'ken grimwood books', 'books like replay', 'replay series'],
  },
  {
    slug: 'big-little-lies',
    name: 'Big Little Lies',
    author: 'Liane Moriarty',
    authorQuery: 'Liane Moriarty',
    genre: 'fiction',
    description: "Liane Moriarty's bestselling standalone domestic mystery about three women in an elite Sydney school community whose friendship leads to a death at trivia night. A dark comedy and a serious examination of domestic abuse, social pressure, and the secrets communities keep. Adapted into an Emmy-winning HBO series with Reese Witherspoon and Nicole Kidman.",
    searchTerms: ['big little lies reading order', 'big little lies sequel', 'liane moriarty books in order', 'books like big little lies', 'liane moriarty series'],
  },
  {
    slug: 'whered-you-go-bernadette',
    name: "Where'd You Go, Bernadette",
    shortName: 'Bernadette',
    author: 'Maria Semple',
    authorQuery: 'Maria Semple',
    genre: 'fiction',
    description: "Maria Semple's dark comedy about Bernadette Fox, a brilliant and agoraphobic former architect living in Seattle who begins disappearing — told through the documents her teenage daughter Bee assembles to figure out what happened. A satirical novel about Seattle tech culture, creative genius, collapse, and recovery.",
    searchTerms: ["where'd you go bernadette reading order", 'bernadette sequel', 'maria semple books', "books like where'd you go bernadette", 'bernadette series'],
  },
  {
    slug: 'a-little-life',
    name: 'A Little Life',
    author: 'Hanya Yanagihara',
    authorQuery: 'Hanya Yanagihara',
    genre: 'fiction',
    description: "Hanya Yanagihara's Booker Prize–finalist standalone novel about four college friends whose friendship over decades in New York centers increasingly on Jude St. Francis and the history of childhood abuse that shapes everything about his adult life. One of the most emotionally extreme novels in contemporary American literature and a profound study of friendship, love, and what sustained damage does to a person's inner life. Contains extremely graphic depictions of abuse and self-harm.",
    searchTerms: ['a little life reading order', 'a little life sequel', 'hanya yanagihara books', 'books like a little life', 'a little life series'],
  },
  {
    slug: 'the-secret-history',
    name: 'The Secret History',
    author: 'Donna Tartt',
    authorQuery: 'Donna Tartt',
    genre: 'fiction',
    description: "Donna Tartt's debut novel about an elite group of classics students at a small Vermont college who commit a murder — the novel tells the story of how and why from the beginning, opening with the revelation of the victim. The novel that defined the dark academia aesthetic and popularized the reverse-mystery structure in literary fiction.",
    searchTerms: ['the secret history reading order', 'the secret history sequel', 'donna tartt books in order', 'books like the secret history', 'dark academia novels'],
  },
  {
    slug: 'little-fires-everywhere',
    name: 'Little Fires Everywhere',
    author: 'Celeste Ng',
    authorQuery: 'Celeste Ng',
    genre: 'fiction',
    description: "Celeste Ng's bestselling standalone novel about two families in the planned community of Shaker Heights, Ohio — the Richardsons, pillars of the community, and Mia Warren and her daughter Pearl, a photographer and her daughter who have been moving from place to place — and the collision between them over a custody dispute involving a Chinese-American baby. An examination of race, class, and the idea that good planning can prevent disaster.",
    searchTerms: ['little fires everywhere reading order', 'little fires everywhere sequel', 'celeste ng books', 'books like little fires everywhere', 'celeste ng reading order'],
  },
  {
    slug: 'nine-perfect-strangers',
    name: 'Nine Perfect Strangers',
    author: 'Liane Moriarty',
    authorQuery: 'Liane Moriarty',
    genre: 'fiction',
    description: "Liane Moriarty's bestselling standalone about nine people at a luxury Australian wellness retreat run by the charismatic Masha, who has a specific treatment plan for each of them that none of them signed up for. A dark comedy about healing, grief, and the specific vulnerability that makes unorthodox gurus possible.",
    searchTerms: ['nine perfect strangers reading order', 'nine perfect strangers sequel', 'liane moriarty books in order', 'books like nine perfect strangers', 'nine perfect strangers series'],
  },
  {
    slug: 'the-forever-war',
    name: 'The Forever War',
    author: 'Joe Haldeman',
    authorQuery: 'Joe Haldeman',
    genre: 'sci-fi',
    description: "Joe Haldeman's Hugo and Nebula Award–winning military science fiction novel about soldiers fighting an interstellar war while relativistic travel ages Earth decades between each deployment — written as a direct response to Vietnam and to Heinlein's Starship Troopers. The founding text of the 'war is alienating' tradition in military SF.",
    searchTerms: ['the forever war reading order', 'forever war series order', 'joe haldeman books', 'books like the forever war', 'forever war books in order'],
  },
  {
    slug: 'the-goldfinch',
    name: 'The Goldfinch',
    author: 'Donna Tartt',
    authorQuery: 'Donna Tartt',
    genre: 'fiction',
    description: "Donna Tartt's Pulitzer Prize–winning standalone novel about Theo Decker, who survives a New York museum bombing that kills his mother and takes a small Dutch masterpiece — Carel Fabritius's The Goldfinch — from the wreckage, carrying it through foster care, Las Vegas, the antiques world, and a climax in Amsterdam over the following decades.",
    searchTerms: ['the goldfinch reading order', 'the goldfinch sequel', 'donna tartt books in order', 'books like the goldfinch', 'donna tartt goldfinch'],
  },
  {
    slug: 'normal-people',
    name: 'Normal People',
    author: 'Sally Rooney',
    authorQuery: 'Sally Rooney',
    genre: 'romance',
    description: "Sally Rooney's Costa Novel Award–winning standalone about Connell and Marianne, who meet in secondary school in rural Sligo, Ireland — where Connell is popular and Marianne is not — and follow each other to Trinity College Dublin, where everything is reversed. The novel traces the loop of their relationship over four years. Adapted into a celebrated BBC/Hulu series in 2020.",
    searchTerms: ['normal people reading order', 'normal people sequel', 'sally rooney books in order', 'books like normal people', 'sally rooney reading order'],
  },
  {
    slug: 'the-vanishing-half',
    name: 'The Vanishing Half',
    author: 'Brit Bennett',
    authorQuery: 'Brit Bennett',
    genre: 'fiction',
    description: "Brit Bennett's bestselling standalone novel about twin sisters from a light-skinned Black Louisiana town: Stella, who passes as white and disappears into white America, and Desiree, who returns to their hometown with a dark-skinned daughter. The novel traces both sisters across forty years and asks what identity means when it can be chosen.",
    searchTerms: ['the vanishing half reading order', 'the vanishing half sequel', 'brit bennett books', 'books like the vanishing half', 'the vanishing half series'],
  },
  {
    slug: 'if-we-were-villains',
    name: 'If We Were Villains',
    author: 'M.L. Rio',
    authorQuery: 'M.L. Rio',
    genre: 'fiction',
    description: "M.L. Rio's dark academia debut novel about seven Shakespeare students at an elite performing arts conservatory who share roles in the plays they perform — until one is found dead and another convicted of murder. Told retrospectively by Oliver, one of the seven, the novel is the most celebrated successor to Donna Tartt's The Secret History.",
    searchTerms: ['if we were villains reading order', 'if we were villains sequel', 'ml rio books', 'books like if we were villains', 'dark academia novels'],
  },
  {
    slug: 'the-lovely-bones',
    name: 'The Lovely Bones',
    author: 'Alice Sebold',
    authorQuery: 'Alice Sebold',
    genre: 'fiction',
    description: "Alice Sebold's bestselling standalone novel narrated by Susie Salmon, a 14-year-old girl who was raped and murdered by a neighbor, from her personal heaven — watching her family, her killer, and the investigation below as the years pass. One of the defining literary bestsellers of the 2000s.",
    searchTerms: ['the lovely bones reading order', 'the lovely bones sequel', 'alice sebold books', 'books like the lovely bones', 'lovely bones series'],
  },
];

export function getSeriesBySlug(slug: string): SeriesDefinition | undefined {
  return SERIES.find((s) => s.slug === slug);
}
